pi-BEM: Parallel BEM Solver: bem_problem.cc File Reference
bem_problem.cc File Reference
#include "../include/bem_problem.h"
#include <deal.II/numerics/error_estimator.h>
#include <iomanip>
#include <iostream>
#include <memory>
#include "../include/laplace_kernel.h"
#include "../include/singular_kernel_integral.h"
#include "Teuchos_TimeMonitor.hpp"
Classes
struct EntryRaiiObject
Macros
#define ENTRY EntryRaiiObject obj##LINE(__FUNCTION__);
Variables
RCP< Time > ConstraintsTime
RCP< Time > AssembleTime = Teuchos::TimeMonitor::getNewTimer("Assemble Time")
RCP< Time > NormalsTime = Teuchos::TimeMonitor::getNewTimer("Normals Time")
RCP< Time > SurfaceGradientTime
RCP< Time > GradientTime = Teuchos::TimeMonitor::getNewTimer("Gradient Time")
RCP< Time > LacSolveTime = Teuchos::TimeMonitor::getNewTimer("LAC Solve Time")
RCP< Time > ReinitTime
Macro Definition Documentation
ENTRY
#define ENTRY EntryRaiiObject obj##LINE(__FUNCTION__);
Definition at line 20 of file bem_problem.cc.
Variable Documentation
AssembleTime
RCP<Time> AssembleTime = Teuchos::TimeMonitor::getNewTimer("Assemble Time")
Definition at line 47 of file bem_problem.cc.
Referenced by BEMProblem< dim >::assemble_system(), and BEMProblem< dim >::compute_gradients_hypersingular().
ConstraintsTime
RCP<Time> ConstraintsTime
Initial value:
=
  Teuchos::TimeMonitor::getNewTimer("Compute Constraints Time")
Definition at line 45 of file bem_problem.cc.
Referenced by BEMProblem< dim >::compute_constraints().
GradientTime
RCP<Time> GradientTime = Teuchos::TimeMonitor::getNewTimer("Gradient Time")
Definition at line 51 of file bem_problem.cc.
Referenced by BEMProblem< dim >::compute_gradients().
LacSolveTime
RCP<Time> LacSolveTime = Teuchos::TimeMonitor::getNewTimer("LAC Solve Time")
Definition at line 52 of file bem_problem.cc.
Referenced by BEMProblem< dim >::solve_system().
NormalsTime
RCP<Time> NormalsTime = Teuchos::TimeMonitor::getNewTimer("Normals Time")
Definition at line 48 of file bem_problem.cc.
Referenced by BEMProblem< dim >::compute_normals().
ReinitTime
RCP<Time> ReinitTime
Initial value:
=
  Teuchos::TimeMonitor::getNewTimer("BEM Reinitialisation Time")
Definition at line 53 of file bem_problem.cc.
Referenced by BEMProblem< dim >::reinit().
SurfaceGradientTime
RCP<Time> SurfaceGradientTime
Initial value:
=
  Teuchos::TimeMonitor::getNewTimer("SurfaceGradientTime Time")
Definition at line 49 of file bem_problem.cc.
Referenced by BEMProblem< dim >::compute_surface_gradients().