pi-BEM: Parallel BEM Solver: BoundaryConditions< dim > Class Template Reference
BoundaryConditions< dim > Class Template Reference
#include <boundary_conditions.h>
Public Types
typedef DoFHandler< dim-1, dim >::active_cell_iterator cell_it
Public Member Functions
BoundaryConditions (ComputationalDomain< dim > &comp_dom, BEMProblem< dim > &bem, const MPI_Comm comm=MPI_COMM_WORLD)
virtual void declare_parameters (ParameterHandler &prm) override
virtual void parse_parameters (ParameterHandler &prm) override
void prepare_bem_vectors ()
void solve_problem ()
void output_results (const std::string)
void compute_errors ()
const TrilinosWrappers::MPI::Vector & get_phi ()
const TrilinosWrappers::MPI::Vector & get_dphi_dn ()
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
unsigned int get_acceptor_id () const
virtual ~ParameterAcceptor () override
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from EnableObserverPointer
EnableObserverPointer ()
EnableObserverPointer (const EnableObserverPointer &)
EnableObserverPointer (EnableObserverPointer &&) noexcept
virtual ~EnableObserverPointer ()
EnableObserverPointer & operator= (const EnableObserverPointer &)
EnableObserverPointer & operator= (EnableObserverPointer &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Attributes
std::string output_file_name
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Protected Attributes
Functions::ParsedFunction< dim > wind
Functions::ParsedFunction< dim > potential
std::string node_displacement_type
SolverControl solver_control
ComputationalDomain< dim > & comp_dom
BEMProblem< dim > & bem
types::global_dof_index dofs_number
unsigned int output_frequency
TrilinosWrappers::MPI::Vector tmp_rhs
TrilinosWrappers::MPI::Vector phi
TrilinosWrappers::MPI::Vector dphi_dn
MPI_Comm mpi_communicator
unsigned int n_mpi_processes
unsigned int this_mpi_process
bool have_dirichlet_bc
IndexSet this_cpu_set
ConditionalOStream pcout
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from EnableObserverPointer
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Detailed Description
template<int dim>
class BoundaryConditions< dim >
BoundaryCondition. The class handles the boundary conditions. In particular
it reads the boundary conditions for the potential and its normal derivative;
given the peculiarities of the BEM, the boundary conditions represent the actual unknowns, thus it creates the vectors containing the variables and fills them with the proper data;
it performs the error analysis on both unknowns.
Definition at line 76 of file boundary_conditions.h.
Member Typedef Documentation
cell_it
template<int dim> DoFHandler<dim-1,dim>::active_cell_iterator BoundaryConditions< dim >::cell_it
Definition at line 94 of file boundary_conditions.h.
Constructor & Destructor Documentation
BoundaryConditions()
template<int dim> BoundaryConditions< dim >::BoundaryConditions (ComputationalDomain< dim > & comp_dom, BEMProblem< dim > & bem, const MPI_Comm comm = MPI_COMM_WORLD) inline
Definition at line 79 of file boundary_conditions.h.
References comm, BoundaryConditions< dim >::dofs_number, MPI, and BoundaryConditions< dim >::output_frequency.
Member Function Documentation
compute_errors()
template<int dim> void BoundaryConditions< dim >::compute_errors ()
Definition at line 347 of file boundary_conditions.cc.
References Vector< typename Number >::add(), DataOut< int dim, int spacedim >::attach_dof_handler(), DataComponentInterpretation::component_is_part_of_vector, d(), ErrorsTime, VectorTools::integrate_difference(), VectorTools::L2_norm, Vector< typename Number >::l2_norm(), Vector< typename Number >::linfty_norm(), and DoFTools::map_dofs_to_support_points().
declare_parameters()
template<int dim> void BoundaryConditions< dim >::declare_parameters (ParameterHandler & prm) override virtual
Reimplemented from ParameterAcceptor.
Definition at line 35 of file boundary_conditions.cc.
References ParameterHandler::declare_entry(), Functions::ParsedFunction< int dim >::declare_parameters(), ParameterHandler::enter_subsection(), ParameterHandler::leave_subsection(), and ParameterHandler::set().
get_dphi_dn()
template<int dim> const TrilinosWrappers::MPI::Vector & BoundaryConditions< dim >::get_dphi_dn ()
Definition at line 210 of file boundary_conditions.cc.
get_phi()
template<int dim> const TrilinosWrappers::MPI::Vector & BoundaryConditions< dim >::get_phi ()
Definition at line 203 of file boundary_conditions.cc.
output_results()
template<int dim> void BoundaryConditions< dim >::output_results (const std::string filename)
Definition at line 546 of file boundary_conditions.cc.
References DataOut< int dim, int spacedim >::attach_dof_handler(), DataComponentInterpretation::component_is_part_of_vector, and OutputTimer.
parse_parameters()
template<int dim> void BoundaryConditions< dim >::parse_parameters (ParameterHandler & prm) override virtual
Reimplemented from ParameterAcceptor.
Definition at line 71 of file boundary_conditions.cc.
References ParameterHandler::enter_subsection(), ParameterHandler::get(), Utilities::int_to_string(), and ParameterHandler::leave_subsection().
prepare_bem_vectors()
template<int dim> void BoundaryConditions< dim >::prepare_bem_vectors ()
Definition at line 219 of file boundary_conditions.cc.
References Assert, d(), DoFTools::map_dofs_to_support_points(), PrepareTime, update_JxW_values, update_normal_vectors, update_quadrature_points, and update_values.
solve_problem()
template<int dim> void BoundaryConditions< dim >::solve_problem ()
Definition at line 160 of file boundary_conditions.cc.
References DoFTools::get_subdomain_association(), DoFTools::map_dofs_to_support_points(), and shift().
Member Data Documentation
bem
template<int dim> BEMProblem<dim>& BoundaryConditions< dim >::bem protected
Definition at line 134 of file boundary_conditions.h.
comp_dom
template<int dim> ComputationalDomain<dim>& BoundaryConditions< dim >::comp_dom protected
Definition at line 132 of file boundary_conditions.h.
dofs_number
template<int dim> types::global_dof_index BoundaryConditions< dim >::dofs_number protected
Definition at line 136 of file boundary_conditions.h.
Referenced by BoundaryConditions< dim >::BoundaryConditions().
dphi_dn
template<int dim> TrilinosWrappers::MPI::Vector BoundaryConditions< dim >::dphi_dn protected
Definition at line 142 of file boundary_conditions.h.
have_dirichlet_bc
template<int dim> bool BoundaryConditions< dim >::have_dirichlet_bc protected
Definition at line 150 of file boundary_conditions.h.
mpi_communicator
template<int dim> MPI_Comm BoundaryConditions< dim >::mpi_communicator protected
Definition at line 144 of file boundary_conditions.h.
n_mpi_processes
template<int dim> unsigned int BoundaryConditions< dim >::n_mpi_processes protected
Definition at line 146 of file boundary_conditions.h.
node_displacement_type
template<int dim> std::string BoundaryConditions< dim >::node_displacement_type protected
Definition at line 128 of file boundary_conditions.h.
output_file_name
template<int dim> std::string BoundaryConditions< dim >::output_file_name
Definition at line 121 of file boundary_conditions.h.
output_frequency
template<int dim> unsigned int BoundaryConditions< dim >::output_frequency protected
Definition at line 138 of file boundary_conditions.h.
Referenced by BoundaryConditions< dim >::BoundaryConditions().
pcout
template<int dim> ConditionalOStream BoundaryConditions< dim >::pcout protected
Definition at line 154 of file boundary_conditions.h.
phi
template<int dim> TrilinosWrappers::MPI::Vector BoundaryConditions< dim >::phi protected
Definition at line 141 of file boundary_conditions.h.
potential
template<int dim> Functions::ParsedFunction<dim> BoundaryConditions< dim >::potential protected
Definition at line 126 of file boundary_conditions.h.
solver_control
template<int dim> SolverControl BoundaryConditions< dim >::solver_control protected
Definition at line 130 of file boundary_conditions.h.
this_cpu_set
template<int dim> IndexSet BoundaryConditions< dim >::this_cpu_set protected
Definition at line 152 of file boundary_conditions.h.
this_mpi_process
template<int dim> unsigned int BoundaryConditions< dim >::this_mpi_process protected
Definition at line 148 of file boundary_conditions.h.
tmp_rhs
template<int dim> TrilinosWrappers::MPI::Vector BoundaryConditions< dim >::tmp_rhs protected
Definition at line 140 of file boundary_conditions.h.
wind
template<int dim> Functions::ParsedFunction<dim> BoundaryConditions< dim >::wind protected
Definition at line 124 of file boundary_conditions.h.
The documentation for this class was generated from the following files:
boundary_conditions.h
boundary_conditions.cc