pi-BEM: Parallel BEM Solver: BEMProblem< dim > Class Template Reference
BEMProblem< dim > Class Template Reference
#include <bem_problem.h>
Public Types
typedef DoFHandler< dim-1, dim >::active_cell_iterator cell_it
Public Member Functions
BEMProblem (ComputationalDomain< dim > &comp_dom, const MPI_Comm comm=MPI_COMM_WORLD)
void solve (TrilinosWrappers::MPI::Vector &phi, TrilinosWrappers::MPI::Vector &dphi_dn, const TrilinosWrappers::MPI::Vector &tmp_rhs)
void reinit ()
const Quadrature< dim - 1 > & get_singular_quadrature (const unsigned int index) const
void compute_constraints (IndexSet &c_cpu_set, AffineConstraints< double > &constraints, const TrilinosWrappers::MPI::Vector &tmp_rhs)
virtual void declare_parameters (ParameterHandler &prm) override
virtual void parse_parameters (ParameterHandler &prm) override
void compute_hypersingular_free_coeffs ()
void compute_alpha ()
void assemble_system ()
void vmult (TrilinosWrappers::MPI::Vector &dst, const TrilinosWrappers::MPI::Vector &src) const
void compute_rhs (TrilinosWrappers::MPI::Vector &dst, const TrilinosWrappers::MPI::Vector &src) const
void assemble_preconditioner ()
void solve_system (TrilinosWrappers::MPI::Vector &phi, TrilinosWrappers::MPI::Vector &dphi_dn, const TrilinosWrappers::MPI::Vector &tmp_rhs)
void output_results (const std::string)
void compute_surface_gradients (const TrilinosWrappers::MPI::Vector &tmp_rhs)
void compute_gradients (const TrilinosWrappers::MPI::Vector &phi, const TrilinosWrappers::MPI::Vector &dphi_dn)
void compute_gradients_hypersingular (const TrilinosWrappers::MPI::Vector &phi, const TrilinosWrappers::MPI::Vector &dphi_dn)
void compute_normals ()
void compute_dirichlet_and_neumann_dofs_vectors ()
void compute_double_nodes_set ()
void compute_reordering_vectors ()
void adaptive_refinement (const TrilinosWrappers::MPI::Vector &error_vector)
BEMProblem (ComputationalDomain< 3 > &comp_dom, MPI_Comm comm)
BEMProblem (ComputationalDomain< 2 > &comp_dom, MPI_Comm comm)
const Quadrature< 2 > & get_singular_quadrature (const unsigned int index) const
const Quadrature< 1 > & get_singular_quadrature (const unsigned int index) const
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
unsigned int get_acceptor_id () const
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Attributes
ConditionalOStream pcout
ComputationalDomain< dim > & comp_dom
std::string scalar_fe_type
std::string vector_fe_type
unsigned int scalar_fe_order
unsigned int vector_fe_order
std::unique_ptr< FiniteElement< dim - 1, dim > > fe
std::unique_ptr< FiniteElement< dim - 1, dim > > gradient_fe
DoFHandler< dim - 1, dim > dh
DoFHandler< dim - 1, dim > gradient_dh
double refinement_threshold
double coarsening_threshold
Vector< double > map_vector
std::shared_ptr< Mapping< dim - 1, dim > > mapping
unsigned int mapping_degree
Vector< double > map_points
std::vector< std::set< types::global_dof_index > > double_nodes_set
std::vector< std::set< types::global_dof_index > > gradient_double_nodes_set
std::shared_ptr< Quadrature< dim - 1 > > quadrature
unsigned int quadrature_order
unsigned int singular_quadrature_order
TrilinosWrappers::SparsityPattern full_sparsity_pattern
TrilinosWrappers::SparseMatrix neumann_matrix
TrilinosWrappers::SparseMatrix dirichlet_matrix
TrilinosWrappers::MPI::Vector system_rhs
TrilinosWrappers::MPI::Vector sol
solution and alpha vectors
TrilinosWrappers::MPI::Vector alpha
TrilinosWrappers::MPI::Vector hyp_alpha
std::vector< TrilinosWrappers::MPI::Vector > C_ij
std::vector< TrilinosWrappers::MPI::Vector > b_i
TrilinosWrappers::MPI::Vector serv_phi
TrilinosWrappers::MPI::Vector serv_dphi_dn
TrilinosWrappers::MPI::Vector serv_tmp_rhs
AffineConstraints< double > constraints
std::string preconditioner_type
std::string mapping_type
std::string solution_method
SolverControl solver_control
TrilinosWrappers::PreconditionILU preconditioner
TrilinosWrappers::SparsityPattern preconditioner_sparsity_pattern
TrilinosWrappers::SparseMatrix band_system
types::global_dof_index preconditioner_band
bool is_preconditioner_initialized
bool continuos_gradient
MPI_Comm mpi_communicator
unsigned int n_mpi_processes
unsigned int this_mpi_process
TrilinosWrappers::MPI::Vector dirichlet_nodes
TrilinosWrappers::MPI::Vector neumann_nodes
IndexSet this_cpu_set
IndexSet ghosted_set
IndexSet vector_this_cpu_set
IndexSet constr_cpu_set
IndexSet edge_set
TrilinosWrappers::MPI::Vector vector_gradients_solution
TrilinosWrappers::MPI::Vector vector_surface_gradients_solution
TrilinosWrappers::MPI::Vector vector_normals_solution
std::vector< types::global_dof_index > start_per_process
std::vector< types::global_dof_index > vector_start_per_process
TrilinosWrappers::SparsityPattern vector_sparsity_pattern
AffineConstraints< double > vector_constraints
std::vector< types::global_dof_index > original_to_sub_wise
std::vector< types::global_dof_index > sub_wise_to_original
std::vector< types::global_dof_index > vec_original_to_sub_wise
std::vector< types::global_dof_index > vec_sub_wise_to_original
bool have_dirichlet_bc
BEMFMA< dim > fma
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Detailed Description
template<int dim>
class BEMProblem< dim >
BEMProblem. This class is the core of the BEM simulation
it receives the variables vector filled in with the proper boundary condition;
it creates the codimension 1 functional space setting up the BEM;
it solves the system using a preconditioned parallel GMRES solver;
it eventually interacts with the FMM accelerator.
Definition at line 120 of file bem_problem.h.
Member Typedef Documentation
cell_it
template<int dim> typedef DoFHandler<dim-1,dim>::active_cell_iterator BEMProblem< dim >::cell_it
Definition at line 123 of file bem_problem.h.
Constructor & Destructor Documentation
BEMProblem() [1/3]
template<int dim> BEMProblem< dim >::BEMProblem (ComputationalDomain< dim > & comp_dom, const MPI_Comm comm = MPI_COMM_WORLD)
BEMProblem() [2/3]
BEMProblem< 3 >::BEMProblem (ComputationalDomain< 3 > & comp_dom, MPI_Comm comm)
Definition at line 85 of file bem_problem.cc.
References comm, n_mpi_processes(), BEMProblem< dim >::pcout, ConditionalOStream::set_condition(), this_mpi_process(), BEMProblem< dim >::this_mpi_process, and tria.
BEMProblem() [3/3]
BEMProblem< 2 >::BEMProblem (ComputationalDomain< 2 > & comp_dom, MPI_Comm comm)
Definition at line 100 of file bem_problem.cc.
References comm, n_mpi_processes(), BEMProblem< dim >::pcout, ConditionalOStream::set_condition(), this_mpi_process(), BEMProblem< dim >::this_mpi_process, and tria.
Member Function Documentation
adaptive_refinement()
template<int dim> void BEMProblem< dim >::adaptive_refinement (const TrilinosWrappers::MPI::Vector & error_vector)
Definition at line 3021 of file bem_problem.cc.
References KellyErrorEstimator< dim, spacedim >::estimate(), and GridRefinement::refine_and_coarsen_fixed_number().
assemble_preconditioner()
template<int dim> void BEMProblem< dim >::assemble_preconditioner
The third method computes the product between the solution vector and the (fully populated) sytstem matrix. This function assembles in parallel the band preconditioner to be used in the direct resolution method.
Definition at line 2163 of file bem_problem.cc.
assemble_system()
template<int dim> void BEMProblem< dim >::assemble_system
This function assembles the full distributed matrices needed by the direct method. We compute both the Double Layer Operator (Neumann matrix) and Single Layer Operator (Dirichlet matrix). Then we have to use dirichlet and neumann vector to assemble properly the system matrix and its right hand side.
Definition at line 754 of file bem_problem.cc.
References Vector< class >::add(), AssembleTime, Assert, numbers::invalid_unsigned_int, LaplaceKernel::kernels(), DoFTools::map_dofs_to_support_points(), update_jacobians, update_JxW_values, update_normal_vectors, update_quadrature_points, and update_values.
compute_alpha()
template<int dim> void BEMProblem< dim >::compute_alpha
This function computes the fraction of solid angles seen by our domain. We use the Double Layer Operator (through the Neumann matrix) to determine it.
Definition at line 1558 of file bem_problem.cc.
References AssertThrow, TrilinosWrappers::MPI::Vector::reinit(), and TrilinosWrappers::MPI::Vector::size().
compute_constraints()
template<int dim> void BEMProblem< dim >::compute_constraints (IndexSet & c_cpu_set, AffineConstraints< double > & constraints, const TrilinosWrappers::MPI::Vector & tmp_rhs)
This function compute a very specific case, a double node that has a dirichlet-dirichlet condition. In this case there is a constraint for the normal derivative since we want a conitnuos velocity thus a conitnuos total gradient. We have solved this problem using an analytical expression for these constraints. Since we need to know all the double nodes set we have kept this function serial. We stress that it needs to be called only once.
Definition at line 1863 of file bem_problem.cc.
References AffineConstraints< class >::add_entry(), IndexSet::add_index(), AffineConstraints< class >::add_line(), AffineConstraints< class >::clear(), IndexSet::clear(), AffineConstraints< class >::close(), IndexSet::compress(), ConstraintsTime, e(), AffineConstraints< class >::get_constraint_entries(), DoFTools::get_subdomain_association(), index2(), AffineConstraints< class >::is_constrained(), DoFTools::make_hanging_node_constraints(), AffineConstraints< class >::merge(), pow(), AffineConstraints< class >::set_inhomogeneity(), IndexSet::set_size(), and TrilinosWrappers::MPI::Vector::size().
compute_dirichlet_and_neumann_dofs_vectors()
template<int dim> void BEMProblem< dim >::compute_dirichlet_and_neumann_dofs_vectors
this method is needed to separate Dirichlet dofs from Neumann nodes.
Definition at line 576 of file bem_problem.cc.
References dirichlet, and this_mpi_process().
compute_double_nodes_set()
template<int dim> void BEMProblem< dim >::compute_double_nodes_set
in the imported mesh, the nodes on the domain edges are doubled: this routine creates a std::vector of std::set which allows to relate each node to their double(s). Since the geometry is shared among all processors we can let every processors to compute_normals the overall double nodes set.
Definition at line 686 of file bem_problem.cc.
References e(), insert, and DoFTools::map_dofs_to_support_points().
compute_gradients()
template<int dim> void BEMProblem< dim >::compute_gradients (const TrilinosWrappers::MPI::Vector & phi, const TrilinosWrappers::MPI::Vector & dphi_dn)
We have parallelised the computation of gradients. We need a solution vector that has also ghost cells. for this reason we made use of a ghosted IndexSet that we have computed in the reinit function. After this we simply make use of deal.ii and its TrilinosWrappers to built and solve a mass matrix system. We want the gradients to be continuos so we need to make good use of both surface gradients and the normal derivative.
Definition at line 2262 of file bem_problem.cc.
References VectorOperation::add, Assert, TrilinosWrappers::SparseMatrix::compress(), TrilinosWrappers::MPI::Vector::compress(), gradient, GradientTime, TrilinosWrappers::PreconditionAMG::initialize(), DoFTools::map_dofs_to_support_points(), TrilinosWrappers::SparseMatrix::reinit(), TrilinosWrappers::MPI::Vector::reinit(), SolverGMRES< class >::solve(), this_mpi_process(), update_gradients, update_JxW_values, update_normal_vectors, update_quadrature_points, and update_values.
compute_gradients_hypersingular()
template<int dim> void BEMProblem< dim >::compute_gradients_hypersingular (const TrilinosWrappers::MPI::Vector & phi, const TrilinosWrappers::MPI::Vector & dphi_dn)
We compute the potential gradients also in an alternative way. Here we make use of the hypersingular integrals computed with the SingularKernelIntegral class
Definition at line 2573 of file bem_problem.cc.
References VectorOperation::add, AssembleTime, Assert, b(), C(), TrilinosWrappers::MPI::Vector::compress(), FullMatrix< class >::copy_to(), d(), SingularKernelIntegral< dim >::evaluate_VkNj_integrals(), SingularKernelIntegral< dim >::evaluate_WkNj_integrals(), VectorOperation::insert, numbers::invalid_unsigned_int, FullMatrix< class >::invert(), LaplaceKernel::kernels(), DoFTools::map_dofs_to_support_points(), update_JxW_values, update_normal_vectors, update_quadrature_points, and update_values.
compute_hypersingular_free_coeffs()
template<int dim> void BEMProblem< dim >::compute_hypersingular_free_coeffs
This function computes the free coefficients appearing in the hypersingular BIE.
Definition at line 1250 of file bem_problem.cc.
References acos(), VectorOperation::add, Assert, b(), compress(), d(), e(), SingularKernelIntegral< dim >::evaluate_free_term_b(), index, TrilinosWrappers::MPI::Vector::l2_norm(), Tensor< rank_, dim, class >::norm(), outer_product(), numbers::PI, TrilinosWrappers::MPI::Vector::sadd(), update_gradients, update_jacobian_grads, update_jacobians, update_JxW_values, update_normal_vectors, update_quadrature_points, and update_values.
compute_normals()
template<int dim> void BEMProblem< dim >::compute_normals
We have parallelised the computation of the L2 projection of the normal vector. We need a solution vector that has also ghost cells. for this reason we made use of a ghosted IndexSet that we have computed in the reinit function. After this we simply make use of deal.ii and its TrilinosWrappers to built and solve a mass matrix system. In this function we don't need any vector with ghost cells.
Definition at line 2915 of file bem_problem.cc.
References VectorOperation::add, TrilinosWrappers::SparseMatrix::compress(), TrilinosWrappers::MPI::Vector::compress(), TrilinosWrappers::PreconditionAMG::initialize(), NormalsTime, TrilinosWrappers::SparseMatrix::reinit(), SolverGMRES< class >::solve(), this_mpi_process(), update_gradients, update_JxW_values, update_normal_vectors, update_quadrature_points, and update_values.
compute_reordering_vectors()
template<int dim> void BEMProblem< dim >::compute_reordering_vectors
Definition at line 733 of file bem_problem.cc.
References DoFRenumbering::compute_subdomain_wise().
compute_rhs()
template<int dim> void BEMProblem< dim >::compute_rhs (TrilinosWrappers::MPI::Vector & dst, const TrilinosWrappers::MPI::Vector & src) const
The second method computes the right hand side vector of the system.
Definition at line 1651 of file bem_problem.cc.
References AssertThrow, and TrilinosWrappers::MPI::Vector::reinit().
compute_surface_gradients()
template<int dim> void BEMProblem< dim >::compute_surface_gradients (const TrilinosWrappers::MPI::Vector & tmp_rhs)
We have parallelised the computation of the surface gradients. We need a solution vector that has also ghost cells. for this reason we made use of a ghosted IndexSet that we have computed in the reinit function. After this we simply make use of deal.ii and its TrilinosWrappers to built and solve a mass matrix system.
Definition at line 2426 of file bem_problem.cc.
References VectorOperation::add, Assert, TrilinosWrappers::SparseMatrix::compress(), TrilinosWrappers::MPI::Vector::compress(), gradient, TrilinosWrappers::PreconditionAMG::initialize(), DoFTools::map_dofs_to_support_points(), TrilinosWrappers::SparseMatrix::reinit(), TrilinosWrappers::MPI::Vector::reinit(), SolverGMRES< class >::solve(), SurfaceGradientTime, this_mpi_process(), update_gradients, update_JxW_values, update_normal_vectors, update_quadrature_points, and update_values.
declare_parameters()
template<int dim> void BEMProblem< dim >::declare_parameters (ParameterHandler & prm) override virtual
We declare the parameters needed by the class. We made good use of the deal.ii SwissArmyKnife library. The parameters will be read from a file if it is existent or a file will be created. The class need a controller for the GMRES solver, quadrature rules, resolution strategy (direct or fma).
Reimplemented from ParameterAcceptor.
Definition at line 460 of file bem_problem.cc.
References ParameterHandler::declare_entry(), ParameterHandler::enter_subsection(), and ParameterHandler::leave_subsection().
get_singular_quadrature() [1/3]
template<int dim> const Quadrature< dim - 1 > & BEMProblem< dim >::get_singular_quadrature (const unsigned int index) const
get_singular_quadrature() [2/3]
const Quadrature< 2 > & BEMProblem< 3 >::get_singular_quadrature (const unsigned int index) const
Definition at line 423 of file bem_problem.cc.
References Assert, and index.
get_singular_quadrature() [3/3]
const Quadrature< 1 > & BEMProblem< 2 >::get_singular_quadrature (const unsigned int index) const
Definition at line 444 of file bem_problem.cc.
References Assert, and index.
output_results()
template<int dim> void BEMProblem< dim >::output_results (const std::string)
parse_parameters()
template<int dim> void BEMProblem< dim >::parse_parameters (ParameterHandler & prm) override virtual
We declare the parameters needed by the class. We made good use of the deal.ii SwissArmyKnife library.
Reimplemented from ParameterAcceptor.
Definition at line 525 of file bem_problem.cc.
References ParameterHandler::enter_subsection(), ParameterHandler::get(), ParameterHandler::get_bool(), ParameterHandler::get_double(), ParameterHandler::get_integer(), and ParameterHandler::leave_subsection().
reinit()
template<int dim> void BEMProblem< dim >::reinit
This function takes care of the proper initialization of all the elements needed by the bem problem class. Since we need to sum elements associated with scalar and vectorial Finite Element spaces we have chosen to renumber the dofs and force the the IndexSet for the parallel partitioning to be consistent. Without this enforcing we are getting in trouble with ghost elements. We set up the two TrilinosSparsityPattern to be used in our computations (assemble system and compute_normals-gradients).
Definition at line 154 of file bem_problem.cc.
References IndexSet::clear(), DoFRenumbering::component_wise(), DoFTools::dof_indices_with_subdomain_association(), VectorTools::get_position_vector(), DoFTools::get_subdomain_association(), DoFTools::make_hanging_node_constraints(), DoFTools::make_sparsity_pattern(), reinit(), ReinitTime, DoFRenumbering::subdomain_wise(), and this_mpi_process().
solve()
template<int dim> void BEMProblem< dim >::solve (TrilinosWrappers::MPI::Vector & phi, TrilinosWrappers::MPI::Vector & dphi_dn, const TrilinosWrappers::MPI::Vector & tmp_rhs)
Definition at line 1837 of file bem_problem.cc.
References AssertThrow.
solve_system()
template<int dim> void BEMProblem< dim >::solve_system (TrilinosWrappers::MPI::Vector & phi, TrilinosWrappers::MPI::Vector & dphi_dn, const TrilinosWrappers::MPI::Vector & tmp_rhs)
This is the function that guides the execution of the BEM problem. Depending on the resolution stategy we go whether for the direct or fma strategy.
Definition at line 1701 of file bem_problem.cc.
References AssertThrow, TrilinosWrappers::MPI::Vector::compress(), ConstrainedOperator< VEC, MATRIX >::distribute_rhs(), VectorOperation::insert, LacSolveTime, and SolverGMRES< class >::solve().
vmult()
template<int dim> void BEMProblem< dim >::vmult (TrilinosWrappers::MPI::Vector & dst, const TrilinosWrappers::MPI::Vector & src) const
The next three methods are needed by the GMRES solver: the first provides result of the product of the system matrix (a combination of Neumann and Dirichlet matrices) by the vector src. The result is stored in the vector dst.
Definition at line 1591 of file bem_problem.cc.
References VectorOperation::add, AssertThrow, TrilinosWrappers::MPI::Vector::compress(), TrilinosWrappers::MPI::Vector::l2_norm(), TrilinosWrappers::MPI::Vector::reinit(), and TrilinosWrappers::MPI::Vector::scale().
Member Data Documentation
alpha
template<int dim> TrilinosWrappers::MPI::Vector BEMProblem< dim >::alpha
Definition at line 353 of file bem_problem.h.
b_i
template<int dim> std::vector<TrilinosWrappers::MPI::Vector> BEMProblem< dim >::b_i
a set of distributed vectors which contain all the entries of the b_i vector appearing in the hypersingular BIE
Definition at line 362 of file bem_problem.h.
band_system
template<int dim> TrilinosWrappers::SparseMatrix BEMProblem< dim >::band_system
Definition at line 383 of file bem_problem.h.
C_ij
template<int dim> std::vector<TrilinosWrappers::MPI::Vector> BEMProblem< dim >::C_ij
a set of distributed vectors which contain all the entries of the C_ij tensor appearing in the hypersingular BIE
Definition at line 359 of file bem_problem.h.
coarsening_threshold
template<int dim> double BEMProblem< dim >::coarsening_threshold
Definition at line 310 of file bem_problem.h.
comp_dom
template<int dim> ComputationalDomain<dim>& BEMProblem< dim >::comp_dom
Definition at line 298 of file bem_problem.h.
constr_cpu_set
template<int dim> IndexSet BEMProblem< dim >::constr_cpu_set
Definition at line 421 of file bem_problem.h.
constraints
template<int dim> AffineConstraints<double> BEMProblem< dim >::constraints
Definition at line 368 of file bem_problem.h.
continuos_gradient
template<int dim> bool BEMProblem< dim >::continuos_gradient
Definition at line 389 of file bem_problem.h.
dh
template<int dim> DoFHandler<dim - 1, dim> BEMProblem< dim >::dh
Definition at line 304 of file bem_problem.h.
dirichlet_matrix
template<int dim> TrilinosWrappers::SparseMatrix BEMProblem< dim >::dirichlet_matrix
Definition at line 347 of file bem_problem.h.
dirichlet_nodes
template<int dim> TrilinosWrappers::MPI::Vector BEMProblem< dim >::dirichlet_nodes
the following vector is needed to treat Dirichlet nodes. Each component is null if it corresponds to a Dirichlet node, and zero if it corresponds to a Neumann node.
Definition at line 403 of file bem_problem.h.
double_nodes_set
template<int dim> std::vector<std::set<types::global_dof_index> > BEMProblem< dim >::double_nodes_set
these are the std::vectors of std::sets containing informations on multiple nodes on the edges: one vector is created for the points associated with the degrees of freedom of the potential function, and one is created for the points associated with the degrees of freedom of its gradient (a vector field)
Definition at line 331 of file bem_problem.h.
edge_set
template<int dim> IndexSet BEMProblem< dim >::edge_set
Definition at line 423 of file bem_problem.h.
fe
template<int dim> std::unique_ptr<FiniteElement<dim - 1, dim> > BEMProblem< dim >::fe
Definition at line 302 of file bem_problem.h.
fma
template<int dim> BEMFMA<dim> BEMProblem< dim >::fma
Definition at line 449 of file bem_problem.h.
full_sparsity_pattern
template<int dim> TrilinosWrappers::SparsityPattern BEMProblem< dim >::full_sparsity_pattern
Definition at line 345 of file bem_problem.h.
ghosted_set
template<int dim> IndexSet BEMProblem< dim >::ghosted_set
The IndexSet for the problem considering every ghost element for the scalar FE
Definition at line 416 of file bem_problem.h.
gradient_dh
template<int dim> DoFHandler<dim - 1, dim> BEMProblem< dim >::gradient_dh
Definition at line 305 of file bem_problem.h.
gradient_double_nodes_set
template<int dim> std::vector<std::set<types::global_dof_index> > BEMProblem< dim >::gradient_double_nodes_set
Definition at line 332 of file bem_problem.h.
gradient_fe
template<int dim> std::unique_ptr<FiniteElement<dim - 1, dim> > BEMProblem< dim >::gradient_fe
Definition at line 303 of file bem_problem.h.
have_dirichlet_bc
template<int dim> bool BEMProblem< dim >::have_dirichlet_bc
Definition at line 447 of file bem_problem.h.
hyp_alpha
template<int dim> TrilinosWrappers::MPI::Vector BEMProblem< dim >::hyp_alpha
an alternatively computed alpha vector (obtained with geometric computations)
Definition at line 356 of file bem_problem.h.
is_preconditioner_initialized
template<int dim> bool BEMProblem< dim >::is_preconditioner_initialized
Definition at line 387 of file bem_problem.h.
map_points
template<int dim> Vector<double> BEMProblem< dim >::map_points
Definition at line 319 of file bem_problem.h.
map_vector
template<int dim> Vector<double> BEMProblem< dim >::map_vector
An Eulerian Mapping is created to deal with the free surface and boat mesh deformation
Definition at line 316 of file bem_problem.h.
mapping
template<int dim> std::shared_ptr<Mapping<dim - 1, dim> > BEMProblem< dim >::mapping
Definition at line 317 of file bem_problem.h.
mapping_degree
template<int dim> unsigned int BEMProblem< dim >::mapping_degree
Definition at line 318 of file bem_problem.h.
mapping_type
template<int dim> std::string BEMProblem< dim >::mapping_type
Definition at line 372 of file bem_problem.h.
mpi_communicator
template<int dim> MPI_Comm BEMProblem< dim >::mpi_communicator
Definition at line 391 of file bem_problem.h.
n_mpi_processes
template<int dim> unsigned int BEMProblem< dim >::n_mpi_processes
Definition at line 393 of file bem_problem.h.
neumann_matrix
template<int dim> TrilinosWrappers::SparseMatrix BEMProblem< dim >::neumann_matrix
Definition at line 346 of file bem_problem.h.
neumann_nodes
template<int dim> TrilinosWrappers::MPI::Vector BEMProblem< dim >::neumann_nodes
The vector has instead null entries for Dirichlet nodes, and ones for Neumann nodes
Definition at line 407 of file bem_problem.h.
original_to_sub_wise
template<int dim> std::vector<types::global_dof_index> BEMProblem< dim >::original_to_sub_wise
Definition at line 439 of file bem_problem.h.
pcout
template<int dim> ConditionalOStream BEMProblem< dim >::pcout
Definition at line 297 of file bem_problem.h.
Referenced by BEMProblem< dim >::BEMProblem(), and BEMProblem< dim >::BEMProblem().
preconditioner
template<int dim> TrilinosWrappers::PreconditionILU BEMProblem< dim >::preconditioner
Definition at line 379 of file bem_problem.h.
preconditioner_band
template<int dim> types::global_dof_index BEMProblem< dim >::preconditioner_band
Definition at line 385 of file bem_problem.h.
preconditioner_sparsity_pattern
template<int dim> TrilinosWrappers::SparsityPattern BEMProblem< dim >::preconditioner_sparsity_pattern
Definition at line 381 of file bem_problem.h.
preconditioner_type
template<int dim> std::string BEMProblem< dim >::preconditioner_type
Definition at line 370 of file bem_problem.h.
quadrature
template<int dim> std::shared_ptr<Quadrature<dim - 1> > BEMProblem< dim >::quadrature
Definition at line 336 of file bem_problem.h.
quadrature_order
template<int dim> unsigned int BEMProblem< dim >::quadrature_order
Definition at line 337 of file bem_problem.h.
refinement_threshold
template<int dim> double BEMProblem< dim >::refinement_threshold
Definition at line 310 of file bem_problem.h.
scalar_fe_order
template<int dim> unsigned int BEMProblem< dim >::scalar_fe_order
Definition at line 301 of file bem_problem.h.
scalar_fe_type
template<int dim> std::string BEMProblem< dim >::scalar_fe_type
Definition at line 300 of file bem_problem.h.
serv_dphi_dn
template<int dim> TrilinosWrappers::MPI::Vector BEMProblem< dim >::serv_dphi_dn mutable
Definition at line 365 of file bem_problem.h.
serv_phi
template<int dim> TrilinosWrappers::MPI::Vector BEMProblem< dim >::serv_phi mutable
Definition at line 364 of file bem_problem.h.
serv_tmp_rhs
template<int dim> TrilinosWrappers::MPI::Vector BEMProblem< dim >::serv_tmp_rhs
Definition at line 366 of file bem_problem.h.
singular_quadrature_order
template<int dim> unsigned int BEMProblem< dim >::singular_quadrature_order
the number of standard quadrature points and singular kernel quadrature to be used
Definition at line 342 of file bem_problem.h.
sol
template<int dim> TrilinosWrappers::MPI::Vector BEMProblem< dim >::sol
solution and alpha vectors
Definition at line 352 of file bem_problem.h.
solution_method
template<int dim> std::string BEMProblem< dim >::solution_method
Definition at line 374 of file bem_problem.h.
solver_control
template<int dim> SolverControl BEMProblem< dim >::solver_control
Definition at line 376 of file bem_problem.h.
start_per_process
template<int dim> std::vector<types::global_dof_index> BEMProblem< dim >::start_per_process
Definition at line 431 of file bem_problem.h.
sub_wise_to_original
template<int dim> std::vector<types::global_dof_index> BEMProblem< dim >::sub_wise_to_original
Definition at line 441 of file bem_problem.h.
system_rhs
template<int dim> TrilinosWrappers::MPI::Vector BEMProblem< dim >::system_rhs
Definition at line 349 of file bem_problem.h.
this_cpu_set
template<int dim> IndexSet BEMProblem< dim >::this_cpu_set
The IndexSet for the problem without considering any ghost element for the scalar FE
Definition at line 413 of file bem_problem.h.
this_mpi_process
template<int dim> unsigned int BEMProblem< dim >::this_mpi_process
Definition at line 395 of file bem_problem.h.
Referenced by BEMProblem< dim >::BEMProblem(), and BEMProblem< dim >::BEMProblem().
vec_original_to_sub_wise
template<int dim> std::vector<types::global_dof_index> BEMProblem< dim >::vec_original_to_sub_wise
Definition at line 443 of file bem_problem.h.
vec_sub_wise_to_original
template<int dim> std::vector<types::global_dof_index> BEMProblem< dim >::vec_sub_wise_to_original
Definition at line 445 of file bem_problem.h.
vector_constraints
template<int dim> AffineConstraints<double> BEMProblem< dim >::vector_constraints
Definition at line 437 of file bem_problem.h.
vector_fe_order
template<int dim> unsigned int BEMProblem< dim >::vector_fe_order
Definition at line 301 of file bem_problem.h.
vector_fe_type
template<int dim> std::string BEMProblem< dim >::vector_fe_type
Definition at line 300 of file bem_problem.h.
vector_gradients_solution
template<int dim> TrilinosWrappers::MPI::Vector BEMProblem< dim >::vector_gradients_solution
Definition at line 425 of file bem_problem.h.
vector_normals_solution
template<int dim> TrilinosWrappers::MPI::Vector BEMProblem< dim >::vector_normals_solution
Definition at line 429 of file bem_problem.h.
vector_sparsity_pattern
template<int dim> TrilinosWrappers::SparsityPattern BEMProblem< dim >::vector_sparsity_pattern
Definition at line 435 of file bem_problem.h.
vector_start_per_process
template<int dim> std::vector<types::global_dof_index> BEMProblem< dim >::vector_start_per_process
Definition at line 433 of file bem_problem.h.
vector_surface_gradients_solution
template<int dim> TrilinosWrappers::MPI::Vector BEMProblem< dim >::vector_surface_gradients_solution
Definition at line 427 of file bem_problem.h.
vector_this_cpu_set
template<int dim> IndexSet BEMProblem< dim >::vector_this_cpu_set
The IndexSet for the problem without considering any ghost element for the vector FE
Definition at line 419 of file bem_problem.h.
The documentation for this class was generated from the following files:
bem_problem.h
bem_problem.cc