pi-BEM: Parallel BEM Solver: BEMFMA< dim > Class Template Reference
BEMFMA< dim > Class Template Reference
#include <bem_fma.h>
Public Types
typedef DoFHandler< dim-1, dim >::active_cell_iterator cell_it
Just renaming the cell iterator type.
Public Member Functions
BEMFMA (MPI_Comm mpi_commy=MPI_COMM_WORLD)
~BEMFMA ()
void init_fma (const DoFHandler< dim - 1, dim > &input_dh, const std::vector< std::set< types::global_dof_index > > &db_in, const TrilinosWrappers::MPI::Vector &input_sn, const Mapping< dim - 1, dim > &input_mapping=StaticMappingQ1< dim - 1, dim >::mapping, unsigned int quad_order=4, unsigned int sing_quad_order=5)
virtual void declare_parameters (ParameterHandler &prm) override
virtual void parse_parameters (ParameterHandler &prm) override
Parameter parsing from input file.
void direct_integrals ()
void multipole_integrals ()
void generate_multipole_expansions (const TrilinosWrappers::MPI::Vector &phi_values, const TrilinosWrappers::MPI::Vector &dphi_dn_values) const
void multipole_matr_vect_products (const TrilinosWrappers::MPI::Vector &phi_values, const TrilinosWrappers::MPI::Vector &dphi_dn_values, TrilinosWrappers::MPI::Vector &matrVectProdN, TrilinosWrappers::MPI::Vector &matrVectProdD) const
void generate_octree_blocking ()
void compute_geometry_cache ()
TrilinosWrappers::PreconditionILU & FMA_preconditioner (const TrilinosWrappers::MPI::Vector &alpha, AffineConstraints< double > &c)
void multipole_integrals ()
void generate_multipole_expansions (const TrilinosWrappers::MPI::Vector &, const TrilinosWrappers::MPI::Vector &) const
void multipole_matr_vect_products (const TrilinosWrappers::MPI::Vector &, const TrilinosWrappers::MPI::Vector &, TrilinosWrappers::MPI::Vector &, TrilinosWrappers::MPI::Vector &) const
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
unsigned int get_acceptor_id () const
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Protected Attributes
SmartPointer< const DoFHandler< dim - 1, dim > > fma_dh
SmartPointer< const Mapping< dim - 1, dim > > fma_mapping
unsigned int trunc_order
TrilinosWrappers::SparsityPattern init_prec_sparsity_pattern
TrilinosWrappers::SparsityPattern final_prec_sparsity_pattern
TrilinosWrappers::SparseMatrix prec_neumann_matrix
TrilinosWrappers::SparseMatrix prec_dirichlet_matrix
TrilinosWrappers::SparseMatrix init_preconditioner
Initial sparse preconditioning matrix (without constraints)
TrilinosWrappers::SparseMatrix final_preconditioner
Final sparse preconditioning matrix (with constraints)
std::map< types::global_dof_index, std::map< cell_it, std::vector< MultipoleExpansion > > > elemMultipoleExpansionsKer1
std::map< types::global_dof_index, std::map< cell_it, std::vector< MultipoleExpansion > > > elemMultipoleExpansionsKer2
std::vector< MultipoleExpansion > blockMultipoleExpansionsKer1
std::vector< MultipoleExpansion > blockMultipoleExpansionsKer2
std::vector< LocalExpansion > blockLocalExpansionsKer1
std::vector< LocalExpansion > blockLocalExpansionsKer2
AssLegFunction assLegFunction
Associated Legendre functions class.
TrilinosWrappers::PreconditionILU preconditioner
unsigned int quadrature_order
unsigned int singular_quadrature_order
MPI_Comm mpi_communicator
mpi related variables
unsigned int n_mpi_processes
unsigned int this_mpi_process
unsigned int max_num_nodes_per_block
unsigned int num_octree_levels
unsigned int tbb_granularity
Granularity for TBB cycles. Simple parallel_for at the moment.
std::map< types::global_dof_index, std::vector< cell_it > > dof_to_elems
std::map< types::global_dof_index, std::vector< cell_it > > gradient_dof_to_elems
std::vector< unsigned int > gradient_dof_components
std::map< types::global_dof_index, std::vector< types::global_dof_index > > dof_to_block
std::map< cell_it, std::vector< std::vector< types::global_dof_index > > > quad_point_to_block
std::map< cell_it, std::set< cell_it > > elem_to_surr_elems
std::vector< OctreeBlock< dim > * > blocks
types::global_dof_index num_blocks
the total blocks number
std::vector< types::global_dof_index > endLevel
std::vector< types::global_dof_index > startLevel
std::vector< types::global_dof_index > childlessList
std::vector< types::global_dof_index > numParent
std::vector< std::vector< types::global_dof_index > > parentList
std::map< cell_it, std::vector< Point< dim > > > quadPoints
std::map< cell_it, std::vector< Tensor< 1, dim > > > quadNormals
std::map< cell_it, std::vector< std::vector< double > > > quadShapeFunValues
std::map< cell_it, std::vector< double > > quadJxW
std::vector< std::vector< types::global_dof_index > > dofs_filled_blocks
std::vector< std::vector< types::global_dof_index > > quad_points_filled_blocks
ConditionalOStream pcout
std::shared_ptr< Quadrature< dim - 1 > > quadrature
TODO parsed quadrature?
SmartPointer< const Vector< double > > dirichlet_nodes
const std::vector< std::set< types::global_dof_index > > * double_nodes_set
This should be erased by the usage of the constraint matrix.
std::vector< std::vector< types::global_dof_index > > m2l_flags
IndexSet this_cpu_set
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Friends
class Operator::MinBEMOperator< dim >
Function to be used in the tests, it can access everything inside bemfma.
template<int gdim>
void test (BEMFMA< gdim > &)
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Detailed Description
template<int dim>
class BEMFMA< dim >
A class for the handling of the Fast Multiple Method coupled with the Bundary Element Method. It is derived from ParameterAcceptor to have a common interface with parameter files. In particular this class performs the matrix vector products approximating long range interactions via Multipole and Local Expansions that are contained in dedicated classes.
Definition at line 71 of file bem_fma.h.
Member Typedef Documentation
cell_it
template<int dim> typedef DoFHandler<dim-1,dim>::active_cell_iterator BEMFMA< dim >::cell_it
Just renaming the cell iterator type.
Definition at line 86 of file bem_fma.h.
Constructor & Destructor Documentation
BEMFMA()
template<int dim> BEMFMA< dim >::BEMFMA (MPI_Comm mpi_commy = MPI_COMM_WORLD)
Contructor: needs only a MPI communicator to be consistent with the other classes of the problem.
Definition at line 29 of file bem_fma.cc.
References n_mpi_processes(), and this_mpi_process().
~BEMFMA()
template<int dim> BEMFMA< dim >::~BEMFMA
Destructor: does not need anything. It frees all the block pointer in the octree lists.
Definition at line 38 of file bem_fma.cc.
Member Function Documentation
compute_geometry_cache()
template<int dim> void BEMFMA< dim >::compute_geometry_cache
Definition at line 3643 of file bem_fma.cc.
declare_parameters()
template<int dim> void BEMFMA< dim >::declare_parameters (ParameterHandler & prm) override virtual
Parameters declaration: we take the number of octree level and the level of approximation of the Kernels
Reimplemented from ParameterAcceptor.
Definition at line 75 of file bem_fma.cc.
References ParameterHandler::declare_entry(), ParameterHandler::enter_subsection(), and ParameterHandler::leave_subsection().
direct_integrals()
template<int dim> void BEMFMA< dim >::direct_integrals
Method computing the parts of the BEM system matrices in which the integrals have to be performed directly. It also sets up the preconditioner. We don't consider any constraints in this function. We have set up the function to work with two levels of parallelism, TBB and MPI. We build up the direct contribution for all those block that doesn't satisfy the accuracy bounds for multipole (and consequently) local expansions.
TODO understand the bandwith of the preconditioner
Definition at line 132 of file bem_fma.cc.
References DirInt, OctreeBlock< dim >::GetBlockNodeList(), OctreeBlock< dim >::GetBlockQuadPointsList(), OctreeBlock< dim >::GetIntList(), OctreeBlock< dim >::GetIntListSize(), OctreeBlock< dim >::GetNonIntList(), LaplaceKernel::kernels(), level, DoFTools::map_dofs_to_support_points(), OctreeBlock< dim >::NumNearNeighLevels(), and WorkStream::run().
FMA_preconditioner()
template<int dim> TrilinosWrappers::PreconditionILU & BEMFMA< dim >::FMA_preconditioner (const TrilinosWrappers::MPI::Vector & alpha, AffineConstraints< double > & c)
Method for the assembling of the sparse preconitioning matrix for FMA. In this function we actually build up the final preconditioner taking great care of all the constraints, through a constraint matrix, we need to impose on our system. We need the vector alpha to properly build up the band of the BEM system we are going to invert (with ILU in this case). This function takes a lot of time to properly compute the preconditioner sparsity pattern and fill it. For this very reason we have taken great care in providing a double parallelisation strategy. Firstly we split among different nodes the computations with MPI and then we use TBB to ensure a parallelisation between different threads on multicore architectures.
Definition at line 3292 of file bem_fma.cc.
generate_multipole_expansions() [1/2]
void BEMFMA< 2 >::generate_multipole_expansions (const TrilinosWrappers::MPI::Vector & , const TrilinosWrappers::MPI::Vector &) const
Definition at line 2119 of file bem_fma.cc.
References AssertThrow.
generate_multipole_expansions() [2/2]
template<int dim> void BEMFMA< dim >::generate_multipole_expansions (const TrilinosWrappers::MPI::Vector & phi_values, const TrilinosWrappers::MPI::Vector & dphi_dn_values) const
[TODO] TO BE MOVED INSIDE multipole_matr_vect_products and made private Ascending phase of the FMA method. Multipole expansions are genarated at the bottom level blocks, and then translated to their parent blocks up to the highest level. It is called once per matrix-vector multiplication. We need to ensure that the proper structure as been set through the function multipole_integral(). We have chosen to use only one level of parallelism inside this function: multithreading with TBB.
Definition at line 2132 of file bem_fma.cc.
References BEMFMA< dim >::assLegFunction, OctreeBlock< dim >::GetBlockQuadPointsList(), OctreeBlock< dim >::GetDelta(), level, MultGen, parallel_for(), WorkStream::run(), MultipoleExpansion::SetCenter(), and BEMFMA< dim >::trunc_order.
generate_octree_blocking()
template<int dim> void BEMFMA< dim >::generate_octree_blocking
this methods creates the adaptive octree partitioning of the domain, needed by the FMA algorithm. Since it takes a very small relative amount of time, and it is called just once in our program we have chosen not to parallelise it.
Definition at line 3852 of file bem_fma.cc.
References OctreeBlock< dim >::AddChild(), OctreeBlock< dim >::GetBlockNodeList(), OctreeBlock< dim >::GetBlockQuadPointsList(), OctreeBlock< dim >::GetPMin(), level, and pow().
init_fma()
template<int dim> void BEMFMA< dim >::init_fma (const DoFHandler< dim - 1, dim > & input_dh, const std::vector< std::set< types::global_dof_index > > & db_in, const TrilinosWrappers::MPI::Vector & input_sn, const Mapping< dim - 1, dim > & input_mapping = StaticMappingQ1<dim - 1, dim>::mapping, unsigned int quad_order = 4, unsigned int sing_quad_order = 5)
Initialization function. It sets up the DoFHandler, FiniteElement, Mapping in the BEMFMA class. It also sets up some useful vector for, mixed boundary conditions and double nodes handling.
Definition at line 49 of file bem_fma.cc.
multipole_integrals() [1/2]
template<int dim> void BEMFMA< dim >::multipole_integrals
Method computing the multipole expansion containing the integrals values for each bottom level block. It is called once for each GMRES solved. This function set up the structure to build the actual multipoles associated with quadrature points. For this reason it has to be called just once.
Definition at line 1752 of file bem_fma.cc.
References OctreeBlock< dim >::GetBlockQuadPointsList(), OctreeBlock< dim >::GetDelta(), OctreeBlock< dim >::GetPMin(), MultInt, numbers::PI, and WorkStream::run().
multipole_integrals() [2/2]
void BEMFMA< 2 >::multipole_integrals ()
Definition at line 1746 of file bem_fma.cc.
multipole_matr_vect_products() [1/2]
void BEMFMA< 2 >::multipole_matr_vect_products (const TrilinosWrappers::MPI::Vector & , const TrilinosWrappers::MPI::Vector & , TrilinosWrappers::MPI::Vector & , TrilinosWrappers::MPI::Vector &) const
Definition at line 2563 of file bem_fma.cc.
multipole_matr_vect_products() [2/2]
template<int dim> void BEMFMA< dim >::multipole_matr_vect_products (const TrilinosWrappers::MPI::Vector & phi_values, const TrilinosWrappers::MPI::Vector & dphi_dn_values, TrilinosWrappers::MPI::Vector & matrVectProdN, TrilinosWrappers::MPI::Vector & matrVectProdD) const
Descending phase of the FMA method. Local Expansions are obtained for each block starting from the top level and down to the bottom ones, where they are used to approximete the values of the integrals, i.e. the BEM matrix-vector product values. This function is called once per every matrix-vector product. We need to call this function after having generating the multipole expansions. Since this function takes a considerable amount of time we have chosen to parallelise it using multithreaded TBB on a single node and MPI to allow even a greater level of parallelism. In this case we don't need any communication because we have made sure that the multipole expansions are replicated on each node. Thus we can safely split the descending phase.
Definition at line 2571 of file bem_fma.cc.
References BEMFMA< dim >::assLegFunction, center, OctreeBlock< dim >::GetBlockNodeList(), OctreeBlock< dim >::GetBlockQuadPointsList(), OctreeBlock< dim >::GetNonIntList(), OctreeBlock< dim >::GetParentId(), level, DoFTools::map_dofs_to_support_points(), MatrVec, OctreeBlock< dim >::NumNearNeighLevels(), parallel_for(), and BEMFMA< dim >::trunc_order.
parse_parameters()
template<int dim> void BEMFMA< dim >::parse_parameters (ParameterHandler & prm) override virtual
Parameter parsing from input file.
Reimplemented from ParameterAcceptor.
Definition at line 105 of file bem_fma.cc.
References ParameterHandler::enter_subsection(), ParameterHandler::get_integer(), and ParameterHandler::leave_subsection().
Friends And Related Symbol Documentation
Operator::MinBEMOperator< dim >
template<int dim> friend class Operator::MinBEMOperator< dim > friend
Function to be used in the tests, it can access everything inside bemfma.
Class that implements a minimal operator
Definition at line 1 of file bem_fma.h.
test
template<int dim> template<int gdim> void test (BEMFMA< gdim > &) friend
Member Data Documentation
assLegFunction
template<int dim> AssLegFunction BEMFMA< dim >::assLegFunction protected
Associated Legendre functions class.
Definition at line 309 of file bem_fma.h.
Referenced by BEMFMA< dim >::generate_multipole_expansions(), and BEMFMA< dim >::multipole_matr_vect_products().
blockLocalExpansionsKer1
template<int dim> std::vector<LocalExpansion> BEMFMA< dim >::blockLocalExpansionsKer1 mutable protected
Vector storing the Dirichlet integrals local expansions for each block
Definition at line 299 of file bem_fma.h.
blockLocalExpansionsKer2
template<int dim> std::vector<LocalExpansion> BEMFMA< dim >::blockLocalExpansionsKer2 mutable protected
Vector storing the Neumann integrals local expansions for each block
Definition at line 305 of file bem_fma.h.
blockMultipoleExpansionsKer1
template<int dim> std::vector<MultipoleExpansion> BEMFMA< dim >::blockMultipoleExpansionsKer1 mutable protected
Vector storing the Dirichlet integrals multipole expansions for each block
Definition at line 287 of file bem_fma.h.
blockMultipoleExpansionsKer2
template<int dim> std::vector<MultipoleExpansion> BEMFMA< dim >::blockMultipoleExpansionsKer2 mutable protected
Vector storing the Neumann integrals multipole expansions for each block
Definition at line 293 of file bem_fma.h.
blocks
template<int dim> std::vector<OctreeBlock<dim> *> BEMFMA< dim >::blocks mutable protected
a vector to store all OctreeBlocks in which the geometry is divided
Definition at line 385 of file bem_fma.h.
childlessList
template<int dim> std::vector<types::global_dof_index> BEMFMA< dim >::childlessList protected
a list of the indices of all the childless blocks
Definition at line 400 of file bem_fma.h.
dirichlet_nodes
template<int dim> SmartPointer<const Vector<double> > BEMFMA< dim >::dirichlet_nodes protected
Definition at line 451 of file bem_fma.h.
dof_to_block
template<int dim> std::map<types::global_dof_index, std::vector<types::global_dof_index> > BEMFMA< dim >::dof_to_block protected
a map associating each DoF to the block it belongs to for each level
Definition at line 367 of file bem_fma.h.
dof_to_elems
template<int dim> std::map<types::global_dof_index, std::vector<cell_it> > BEMFMA< dim >::dof_to_elems protected
here are declared dome structures which will be created in the framework of the octree partitioning of the mesh, and will be used in the FMA a map associating each DoF with the cells it belongs to
Definition at line 350 of file bem_fma.h.
dofs_filled_blocks
template<int dim> std::vector<std::vector<types::global_dof_index> > BEMFMA< dim >::dofs_filled_blocks protected
a std::vector containing std::vectors with the IDs of blocks with at least one dof, for each level
Definition at line 438 of file bem_fma.h.
double_nodes_set
template<int dim> const std::vector<std::set<types::global_dof_index> >* BEMFMA< dim >::double_nodes_set protected
This should be erased by the usage of the constraint matrix.
Definition at line 453 of file bem_fma.h.
elem_to_surr_elems
template<int dim> std::map<cell_it, std::set<cell_it> > BEMFMA< dim >::elem_to_surr_elems protected
a map associating each cell with a std::set containing the surrounding cells
Definition at line 380 of file bem_fma.h.
elemMultipoleExpansionsKer1
template<int dim> std::map<types::global_dof_index, std::map<cell_it, std::vector<MultipoleExpansion> > > BEMFMA< dim >::elemMultipoleExpansionsKer1 mutable protected
Structures where the Dirichlet matrix multipole integrals are stored: for each cell there are as many multipole expansions as the lowest level blocks in which element's quad points lie.
Definition at line 268 of file bem_fma.h.
elemMultipoleExpansionsKer2
template<int dim> std::map<types::global_dof_index, std::map<cell_it, std::vector<MultipoleExpansion> > > BEMFMA< dim >::elemMultipoleExpansionsKer2 mutable protected
Structures where the Neumann matrix multipole integrals are stored: for each cell there are as many multipole expansions as the lowest level blocks in which element's quad points lie.
Definition at line 281 of file bem_fma.h.
endLevel
template<int dim> std::vector<types::global_dof_index> BEMFMA< dim >::endLevel protected
the indices in the blocks vector, at which each of the levels start or end
Definition at line 394 of file bem_fma.h.
final_prec_sparsity_pattern
template<int dim> TrilinosWrappers::SparsityPattern BEMFMA< dim >::final_prec_sparsity_pattern protected
Sparsity pattern for the final preconditioning matrix (constraints applied)
Definition at line 237 of file bem_fma.h.
final_preconditioner
template<int dim> TrilinosWrappers::SparseMatrix BEMFMA< dim >::final_preconditioner protected
Final sparse preconditioning matrix (with constraints)
Definition at line 256 of file bem_fma.h.
fma_dh
template<int dim> SmartPointer<const DoFHandler<dim - 1, dim> > BEMFMA< dim >::fma_dh protected
Three pointers to the problem parameters to be set equal to the ones in the calling problem through the init function
Definition at line 217 of file bem_fma.h.
fma_mapping
template<int dim> SmartPointer<const Mapping<dim - 1, dim> > BEMFMA< dim >::fma_mapping protected
Definition at line 218 of file bem_fma.h.
gradient_dof_components
template<int dim> std::vector<unsigned int> BEMFMA< dim >::gradient_dof_components protected
a vector associating each gradient DoF with the component it represents
Definition at line 360 of file bem_fma.h.
gradient_dof_to_elems
template<int dim> std::map<types::global_dof_index, std::vector<cell_it> > BEMFMA< dim >::gradient_dof_to_elems protected
a map associating each gradient DoF with the cells it belongs to
Definition at line 355 of file bem_fma.h.
init_prec_sparsity_pattern
template<int dim> TrilinosWrappers::SparsityPattern BEMFMA< dim >::init_prec_sparsity_pattern protected
Sparsity pattern for the initial preconditioning matrix (no constraints applied)
Definition at line 231 of file bem_fma.h.
init_preconditioner
template<int dim> TrilinosWrappers::SparseMatrix BEMFMA< dim >::init_preconditioner protected
Initial sparse preconditioning matrix (without constraints)
Definition at line 252 of file bem_fma.h.
m2l_flags
template<int dim> std::vector<std::vector<types::global_dof_index> > BEMFMA< dim >::m2l_flags protected
Definition at line 455 of file bem_fma.h.
max_num_nodes_per_block
template<int dim> unsigned int BEMFMA< dim >::max_num_nodes_per_block protected
maximum number of collocation points that can be contained by a childless block: if a block contains less nodes than this number it is not further refined
Definition at line 333 of file bem_fma.h.
mpi_communicator
template<int dim> MPI_Comm BEMFMA< dim >::mpi_communicator protected
mpi related variables
Definition at line 322 of file bem_fma.h.
n_mpi_processes
template<int dim> unsigned int BEMFMA< dim >::n_mpi_processes protected
Definition at line 324 of file bem_fma.h.
num_blocks
template<int dim> types::global_dof_index BEMFMA< dim >::num_blocks protected
the total blocks number
Definition at line 389 of file bem_fma.h.
num_octree_levels
template<int dim> unsigned int BEMFMA< dim >::num_octree_levels protected
number of levels of the octree partitioning
Definition at line 338 of file bem_fma.h.
numParent
template<int dim> std::vector<types::global_dof_index> BEMFMA< dim >::numParent protected
a list of the number of parent blocks for each level
Definition at line 404 of file bem_fma.h.
parentList
template<int dim> std::vector<std::vector<types::global_dof_index> > BEMFMA< dim >::parentList protected
a std::vector containing the list of parent blocks for each level
Definition at line 409 of file bem_fma.h.
pcout
template<int dim> ConditionalOStream BEMFMA< dim >::pcout protected
Definition at line 446 of file bem_fma.h.
prec_dirichlet_matrix
template<int dim> TrilinosWrappers::SparseMatrix BEMFMA< dim >::prec_dirichlet_matrix protected
Sparse Dirichlet matrix containing only direct integrals contributions
Definition at line 247 of file bem_fma.h.
prec_neumann_matrix
template<int dim> TrilinosWrappers::SparseMatrix BEMFMA< dim >::prec_neumann_matrix protected
Sparse Neumann matrix containing only direct integrals contributions
Definition at line 241 of file bem_fma.h.
preconditioner
template<int dim> TrilinosWrappers::PreconditionILU BEMFMA< dim >::preconditioner protected
the preconditioner to be passed to bem_problem contributi diretti del multipolo, assembla la parte diretta in una vera matrice.
Definition at line 314 of file bem_fma.h.
quad_point_to_block
template<int dim> std::map<cell_it, std::vector<std::vector<types::global_dof_index> > > BEMFMA< dim >::quad_point_to_block protected
a map associating each quad point to the block it belongs to for each level
Definition at line 374 of file bem_fma.h.
quad_points_filled_blocks
template<int dim> std::vector<std::vector<types::global_dof_index> > BEMFMA< dim >::quad_points_filled_blocks protected
a std::vector containing std::vectors with the IDs of blocks with at least one quad point, for each level
Definition at line 444 of file bem_fma.h.
quadJxW
template<int dim> std::map<cell_it, std::vector<double> > BEMFMA< dim >::quadJxW protected
a std::map of std::vectors containing the list of JxW values at quadrature points
Definition at line 432 of file bem_fma.h.
quadNormals
template<int dim> std::map<cell_it, std::vector<Tensor<1, dim> > > BEMFMA< dim >::quadNormals protected
a std::map of std::vectors containing the list of normals at quadrature points
Definition at line 420 of file bem_fma.h.
quadPoints
template<int dim> std::map<cell_it, std::vector<Point<dim> > > BEMFMA< dim >::quadPoints protected
a std::map of std::vectors containing the list of quadrature points
Definition at line 414 of file bem_fma.h.
quadrature
template<int dim> std::shared_ptr<Quadrature<dim - 1> > BEMFMA< dim >::quadrature protected
TODO parsed quadrature?
Definition at line 450 of file bem_fma.h.
quadrature_order
template<int dim> unsigned int BEMFMA< dim >::quadrature_order protected
Definition at line 316 of file bem_fma.h.
quadShapeFunValues
template<int dim> std::map<cell_it, std::vector<std::vector<double> > > BEMFMA< dim >::quadShapeFunValues protected
a std::map of std::vectors containing the list of shape function values at quadrature points
Definition at line 426 of file bem_fma.h.
singular_quadrature_order
template<int dim> unsigned int BEMFMA< dim >::singular_quadrature_order protected
Definition at line 318 of file bem_fma.h.
startLevel
template<int dim> std::vector<types::global_dof_index> BEMFMA< dim >::startLevel protected
Definition at line 395 of file bem_fma.h.
tbb_granularity
template<int dim> unsigned int BEMFMA< dim >::tbb_granularity protected
Granularity for TBB cycles. Simple parallel_for at the moment.
Definition at line 341 of file bem_fma.h.
this_cpu_set
template<int dim> IndexSet BEMFMA< dim >::this_cpu_set protected
Definition at line 456 of file bem_fma.h.
this_mpi_process
template<int dim> unsigned int BEMFMA< dim >::this_mpi_process protected
Definition at line 326 of file bem_fma.h.
trunc_order
template<int dim> unsigned int BEMFMA< dim >::trunc_order protected
Truncation order for the multipole and local expansion series: it is read from the parameters input file.
Definition at line 225 of file bem_fma.h.
Referenced by BEMFMA< dim >::generate_multipole_expansions(), and BEMFMA< dim >::multipole_matr_vect_products().
The documentation for this class was generated from the following files:
bem_fma.h
bem_fma.cc