pi-BEM: Parallel BEM Solver: LocalExpansionCoeff Class Reference
LocalExpansionCoeff Class Reference
#include <local_expansion_coeff.h>
Public Member Functions
LocalExpansionCoeff ()
LocalExpansionCoeff (const unsigned int &p)
LocalExpansionCoeff (const LocalExpansionCoeff &orig)
double get (const unsigned int &n, const unsigned int &m, const unsigned int &nn, const unsigned int &mm)
void set (const unsigned int &n, const unsigned int &m, const unsigned int &nn, const unsigned int &mm, const double &value)
unsigned int getNumberOfElements ()
unsigned int getNNOffset (const unsigned int &nn)
unsigned int getMOffset (const unsigned int &m)
unsigned int getNOffset (const unsigned int &n)
virtual ~LocalExpansionCoeff ()
Private Attributes
unsigned int _p
double * _coeff
Detailed Description
Definition at line 18 of file local_expansion_coeff.h.
Constructor & Destructor Documentation
LocalExpansionCoeff() [1/3]
LocalExpansionCoeff::LocalExpansionCoeff ()
Definition at line 17 of file local_expansion_coeff.cc.
References _coeff, and _p.
LocalExpansionCoeff() [2/3]
LocalExpansionCoeff::LocalExpansionCoeff (const unsigned int & p)
Definition at line 23 of file local_expansion_coeff.cc.
References _coeff, and _p.
LocalExpansionCoeff() [3/3]
LocalExpansionCoeff::LocalExpansionCoeff (const LocalExpansionCoeff & orig)
Definition at line 29 of file local_expansion_coeff.cc.
References _coeff, and _p.
~LocalExpansionCoeff()
LocalExpansionCoeff::~LocalExpansionCoeff () virtual
Definition at line 36 of file local_expansion_coeff.cc.
References _coeff.
Member Function Documentation
get()
double LocalExpansionCoeff::get (const unsigned int & n, const unsigned int & m, const unsigned int & nn, const unsigned int & mm)
Definition at line 48 of file local_expansion_coeff.cc.
References _coeff, getMOffset(), getNNOffset(), and getNOffset().
Referenced by LocalExpansion::Add().
getMOffset()
unsigned int LocalExpansionCoeff::getMOffset (const unsigned int & m)
Definition at line 73 of file local_expansion_coeff.cc.
References _p.
Referenced by get(), and set().
getNNOffset()
unsigned int LocalExpansionCoeff::getNNOffset (const unsigned int & nn)
Definition at line 67 of file local_expansion_coeff.cc.
Referenced by get(), and set().
getNOffset()
unsigned int LocalExpansionCoeff::getNOffset (const unsigned int & n)
Definition at line 79 of file local_expansion_coeff.cc.
References _p.
Referenced by get(), and set().
getNumberOfElements()
unsigned int LocalExpansionCoeff::getNumberOfElements () inline
Definition at line 42 of file local_expansion_coeff.cc.
References _p.
set()
void LocalExpansionCoeff::set (const unsigned int & n, const unsigned int & m, const unsigned int & nn, const unsigned int & mm, const double & value)
Definition at line 57 of file local_expansion_coeff.cc.
References _coeff, getMOffset(), getNNOffset(), and getNOffset().
Referenced by LocalExpansion::mExp_to_lExp_Coeff_Build().
Member Data Documentation
_coeff
double* LocalExpansionCoeff::_coeff private
Definition at line 52 of file local_expansion_coeff.h.
Referenced by get(), LocalExpansionCoeff(), LocalExpansionCoeff(), LocalExpansionCoeff(), set(), and ~LocalExpansionCoeff().
_p
unsigned int LocalExpansionCoeff::_p private
Definition at line 51 of file local_expansion_coeff.h.
Referenced by getMOffset(), getNOffset(), getNumberOfElements(), LocalExpansionCoeff(), LocalExpansionCoeff(), and LocalExpansionCoeff().
The documentation for this class was generated from the following files:
local_expansion_coeff.h
local_expansion_coeff.cc