pi-BEM: Parallel BEM Solver: Driver< dim > Class Template Reference
Driver< dim > Class Template Reference
#include <driver.h>
Public Member Functions
Driver ()
~Driver ()
virtual void declare_parameters (ParameterHandler &prm) override
virtual void parse_parameters (ParameterHandler &prm) override
void run ()
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
unsigned int get_acceptor_id () const
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Protected Attributes
ConditionalOStream pcout
MPI_Comm mpi_communicator
ComputationalDomain< dim > computational_domain
BEMProblem< dim > bem_problem
BoundaryConditions< dim > boundary_conditions
ParameterHandler prm
bool global_refinement
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Detailed Description
template<int dim>
class Driver< dim >
This class is in charge of organising the overall BEM simulation. It has interfaces with all the other classes in order to have a complete simulation.
Definition at line 92 of file driver.h.
Constructor & Destructor Documentation
Driver()
template<int dim> Driver< dim >::Driver
Definition at line 19 of file driver.cc.
References n_mpi_processes(), Driver< dim >::pcout, ConditionalOStream::set_condition(), this_mpi_process(), and Driver< dim >::this_mpi_process.
~Driver()
template<int dim> Driver< dim >::~Driver
Definition at line 60 of file driver.cc.
Member Function Documentation
declare_parameters()
template<int dim> void Driver< dim >::declare_parameters (ParameterHandler & prm) override virtual
method to declare the parameters to be read from the parameters file
Reimplemented from ParameterAcceptor.
Definition at line 66 of file driver.cc.
References ParameterHandler::declare_entry().
parse_parameters()
template<int dim> void Driver< dim >::parse_parameters (ParameterHandler & prm) override virtual
method to parse the needed parameters from the parameters file
Reimplemented from ParameterAcceptor.
Definition at line 73 of file driver.cc.
References ParameterHandler::get_bool().
run()
template<int dim> void Driver< dim >::run
Definition at line 81 of file driver.cc.
References SolveTime, and TotalTime.
Referenced by main().
Member Data Documentation
bem_problem
template<int dim> BEMProblem<dim> Driver< dim >::bem_problem protected
Definition at line 122 of file driver.h.
boundary_conditions
template<int dim> BoundaryConditions<dim> Driver< dim >::boundary_conditions protected
Definition at line 124 of file driver.h.
computational_domain
template<int dim> ComputationalDomain<dim> Driver< dim >::computational_domain protected
Definition at line 120 of file driver.h.
global_refinement
template<int dim> bool Driver< dim >::global_refinement protected
Definition at line 128 of file driver.h.
mpi_communicator
template<int dim> MPI_Comm Driver< dim >::mpi_communicator protected
Definition at line 118 of file driver.h.
n_mpi_processes
template<int dim> const unsigned int Driver< dim >::n_mpi_processes protected
Definition at line 130 of file driver.h.
pcout
template<int dim> ConditionalOStream Driver< dim >::pcout protected
Definition at line 116 of file driver.h.
Referenced by Driver< dim >::Driver().
prm
template<int dim> ParameterHandler Driver< dim >::prm protected
Definition at line 126 of file driver.h.
this_mpi_process
template<int dim> const unsigned int Driver< dim >::this_mpi_process protected
Definition at line 131 of file driver.h.
Referenced by Driver< dim >::Driver().
The documentation for this class was generated from the following files:
driver.h
driver.cc