pi-BEM: Parallel BEM Solver: LocalExpansion Class Reference
LocalExpansion Class Reference
#include <local_expansion.h>
Public Member Functions
LocalExpansion ()
LocalExpansion (const unsigned int order, const dealii::Point< 3 > &center, const AssLegFunction *assLegFunction)
LocalExpansion (const LocalExpansion &other)
~LocalExpansion ()
void Add (const std::vector< double > &real, const std::vector< double > &imag)
void Add (const LocalExpansion &parent)
void Add (const MultipoleExpansion &multipole)
double Evaluate (const dealii::Point< 3 > &evalPoint)
dealii::Point< 3 > & GetCenter () const
void SetCenter (const dealii::Point< 3 > &new_center)
FullMatrix< double > GetA_n_m () const
unsigned int GetOrder () const
std::complex< double > * GetCoeffs () const
std::complex< double > & GetCoeff (unsigned int n, unsigned int m) const
void SetCoeff (unsigned int n, unsigned int m, std::complex< double > &value) const
void AddToCoeff (unsigned int n, unsigned int m, std::complex< double > &value) const
LocalExpansion & operator= (const LocalExpansion &other)
Static Public Member Functions
static FullMatrix< double > A_n_m_Matrix (unsigned int dimension)
static LocalExpansionCoeff mExp_to_lExp_Coeff_Build (FullMatrix< double > A_n_m, unsigned int p)
static std::vector< std::vector< std::map< int, std::map< int, double > > > > lExp_to_lExp_Coeff_Build (FullMatrix< double > A_n_m, unsigned int p)
Public Attributes
bool is_zero
Static Public Attributes
static FullMatrix< double > A_n_m = LocalExpansion::A_n_m_Matrix(20)
static std::vector< std::vector< std::map< int, std::map< int, double > > > > lExp_to_lExp_Coeff
static LocalExpansionCoeff mExp_to_lExp_Coeff
Private Attributes
unsigned int p
dealii::Point< 3 > center
const AssLegFunction * assLegFunction
std::complex< double > * _L_n_m
Detailed Description
Definition at line 16 of file local_expansion.h.
Constructor & Destructor Documentation
LocalExpansion() [1/3]
LocalExpansion::LocalExpansion ()
Definition at line 18 of file local_expansion.cc.
References _L_n_m, assLegFunction, center, is_zero, and p.
LocalExpansion() [2/3]
LocalExpansion::LocalExpansion (const unsigned int order, const dealii::Point< 3 > & center, const AssLegFunction * assLegFunction)
Definition at line 29 of file local_expansion.cc.
References _L_n_m, assLegFunction, center, is_zero, and p.
LocalExpansion() [3/3]
LocalExpansion::LocalExpansion (const LocalExpansion & other)
Definition at line 44 of file local_expansion.cc.
References _L_n_m, assLegFunction, center, GetCoeffs(), is_zero, lExp_to_lExp_Coeff, mExp_to_lExp_Coeff, and p.
~LocalExpansion()
LocalExpansion::~LocalExpansion ()
Definition at line 58 of file local_expansion.cc.
References _L_n_m.
Member Function Documentation
A_n_m_Matrix()
static FullMatrix< double > LocalExpansion::A_n_m_Matrix (unsigned int dimension) inline static
Definition at line 119 of file local_expansion.h.
References A_n_m, pow(), and sqrt().
Add() [1/3]
void LocalExpansion::Add (const LocalExpansion & parent)
Definition at line 108 of file local_expansion.cc.
References abs(), AddToCoeff(), assLegFunction, atan2(), center, cos(), e(), AssLegFunction::GetAssLegFunSph(), GetCenter(), GetCoeff(), GSL_SIGN, is_zero, lExp_to_lExp_Coeff, p, pow(), sin(), and sqrt().
Add() [2/3]
void LocalExpansion::Add (const MultipoleExpansion & multipole)
Definition at line 180 of file local_expansion.cc.
References abs(), AddToCoeff(), assLegFunction, atan2(), center, cos(), LocalExpansionCoeff::get(), AssLegFunction::GetAssLegFunSph(), MultipoleExpansion::GetCenter(), MultipoleExpansion::GetCoeff(), is_zero, MultipoleExpansion::is_zero, mExp_to_lExp_Coeff, p, pow(), sin(), and sqrt().
Add() [3/3]
void LocalExpansion::Add (const std::vector< double > & real, const std::vector< double > & imag)
Definition at line 83 of file local_expansion.cc.
References AddToCoeff(), e(), is_zero, and p.
AddToCoeff()
void LocalExpansion::AddToCoeff (unsigned int n, unsigned int m, std::complex< double > & value) const inline
Definition at line 109 of file local_expansion.h.
Referenced by Add(), Add(), and Add().
Evaluate()
double LocalExpansion::Evaluate (const dealii::Point< 3 > & evalPoint)
Definition at line 252 of file local_expansion.cc.
References assLegFunction, atan2(), center, cos(), AssLegFunction::GetAssLegFunSph(), GetCoeff(), is_zero, p, pow(), sin(), and sqrt().
GetA_n_m()
FullMatrix< double > LocalExpansion::GetA_n_m () const inline
Definition at line 79 of file local_expansion.h.
References A_n_m.
GetCenter()
dealii::Point< 3 > & LocalExpansion::GetCenter () const inline
Definition at line 67 of file local_expansion.h.
References center.
Referenced by Add().
GetCoeff()
std::complex< double > & LocalExpansion::GetCoeff (unsigned int n, unsigned int m) const inline
Definition at line 97 of file local_expansion.h.
Referenced by Add(), and Evaluate().
GetCoeffs()
std::complex< double > * LocalExpansion::GetCoeffs () const inline
Definition at line 91 of file local_expansion.h.
References _L_n_m.
Referenced by LocalExpansion(), and operator=().
GetOrder()
unsigned int LocalExpansion::GetOrder () const inline
Definition at line 85 of file local_expansion.h.
References p.
lExp_to_lExp_Coeff_Build()
static std::vector< std::vector< std::map< int, std::map< int, double > > > > LocalExpansion::lExp_to_lExp_Coeff_Build (FullMatrix< double > A_n_m, unsigned int p) inline static
Definition at line 183 of file local_expansion.h.
References A_n_m, abs(), p, and pow().
mExp_to_lExp_Coeff_Build()
static LocalExpansionCoeff LocalExpansion::mExp_to_lExp_Coeff_Build (FullMatrix< double > A_n_m, unsigned int p) inline static
Definition at line 146 of file local_expansion.h.
References A_n_m, abs(), p, pow(), and LocalExpansionCoeff::set().
operator=()
LocalExpansion & LocalExpansion::operator= (const LocalExpansion & other)
Definition at line 65 of file local_expansion.cc.
References _L_n_m, assLegFunction, center, GetCoeffs(), is_zero, lExp_to_lExp_Coeff, mExp_to_lExp_Coeff, and p.
SetCenter()
void LocalExpansion::SetCenter (const dealii::Point< 3 > & new_center) inline
Definition at line 73 of file local_expansion.h.
SetCoeff()
void LocalExpansion::SetCoeff (unsigned int n, unsigned int m, std::complex< double > & value) const inline
Definition at line 103 of file local_expansion.h.
Member Data Documentation
_L_n_m
std::complex<double>* LocalExpansion::_L_n_m mutable private
Definition at line 39 of file local_expansion.h.
Referenced by GetCoeffs(), LocalExpansion(), LocalExpansion(), LocalExpansion(), operator=(), and ~LocalExpansion().
A_n_m
FullMatrix< double > LocalExpansion::A_n_m = LocalExpansion::A_n_m_Matrix(20) static
Definition at line 19 of file local_expansion.h.
Referenced by A_n_m_Matrix(), GetA_n_m(), lExp_to_lExp_Coeff_Build(), and mExp_to_lExp_Coeff_Build().
assLegFunction
const AssLegFunction* LocalExpansion::assLegFunction mutable private
Definition at line 37 of file local_expansion.h.
Referenced by Add(), Add(), Evaluate(), LocalExpansion(), LocalExpansion(), LocalExpansion(), and operator=().
center
dealii::Point<3> LocalExpansion::center mutable private
Definition at line 35 of file local_expansion.h.
Referenced by Add(), Add(), Evaluate(), GetCenter(), LocalExpansion(), LocalExpansion(), LocalExpansion(), and operator=().
is_zero
bool LocalExpansion::is_zero mutable
Definition at line 29 of file local_expansion.h.
Referenced by Add(), Add(), Add(), Evaluate(), LocalExpansion(), LocalExpansion(), LocalExpansion(), and operator=().
lExp_to_lExp_Coeff
std::vector< std::vector< std::map< int, std::map< int, double > > > > LocalExpansion::lExp_to_lExp_Coeff static
Initial value:
=
    LocalExpansion::lExp_to_lExp_Coeff_Build(LocalExpansion::A_n_m, 10)
Definition at line 25 of file local_expansion.h.
Referenced by Add(), LocalExpansion(), and operator=().
mExp_to_lExp_Coeff
LocalExpansionCoeff LocalExpansion::mExp_to_lExp_Coeff static
Initial value:
=
  LocalExpansion::mExp_to_lExp_Coeff_Build(LocalExpansion::A_n_m, 10)
Definition at line 27 of file local_expansion.h.
Referenced by Add(), LocalExpansion(), and operator=().
p
unsigned int LocalExpansion::p mutable private
Definition at line 33 of file local_expansion.h.
Referenced by Add(), Add(), Add(), Evaluate(), GetOrder(), lExp_to_lExp_Coeff_Build(), LocalExpansion(), LocalExpansion(), LocalExpansion(), mExp_to_lExp_Coeff_Build(), and operator=().
The documentation for this class was generated from the following files:
local_expansion.h
local_expansion.cc