pi-BEM: Parallel BEM Solver: ComputationalDomain< dim > Class Template Reference
ComputationalDomain< dim > Class Template Reference
#include <computational_domain.h>
Public Member Functions
ComputationalDomain (MPI_Comm comm=MPI_COMM_WORLD)
~ComputationalDomain ()
virtual void declare_parameters (ParameterHandler &prm) override
virtual void parse_parameters (ParameterHandler &prm) override
void create_initial_mesh ()
method to create initial mesh
void read_domain ()
void refine_and_resize (const unsigned int refinement_level)
void conditional_refine_and_resize (const unsigned int refinement_level)
void update_triangulation ()
void make_edges_conformal (const bool with_double_nodes=true, const bool isotropic_ref_on_opposite_side=false)
void compute_double_vertex_cache ()
void create_initial_mesh ()
void refine_and_resize (const unsigned int refinement_level)
void make_edges_conformal (const bool with_double_nodes, const bool isotropic_ref_on_opposite_side)
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
unsigned int get_acceptor_id () const
virtual ~ParameterAcceptor () override
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from EnableObserverPointer
EnableObserverPointer ()
EnableObserverPointer (const EnableObserverPointer &)
EnableObserverPointer (EnableObserverPointer &&) noexcept
virtual ~EnableObserverPointer ()
EnableObserverPointer & operator= (const EnableObserverPointer &)
EnableObserverPointer & operator= (EnableObserverPointer &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Attributes
Triangulation< dim - 1, dim > tria
unsigned int n_cycles
number of refining cycles
unsigned int pre_global_refinements
number of global refinement to executed before a local refinement cycle;
double max_element_aspect_ratio
maximum cell aspect ratio
bool use_cad_surface_and_curves
bool surface_curvature_refinement
double cells_per_circle
unsigned int max_curvature_ref_cycles
double cad_to_projectors_tolerance_ratio
std::string input_grid_name
Strings identifying the input grid name and format.
std::string input_grid_format
std::string input_cad_path
std::vector< unsigned int > dirichlet_boundary_ids
std::vector< unsigned int > neumann_boundary_ids
MPI_Comm mpi_communicator
unsigned int n_mpi_processes
unsigned int this_mpi_process
std::vector< bool > vertex_on_boundary
std::vector< std::vector< unsigned int > > double_vertex_vector
std::map< unsigned int, std::vector< typename Triangulation< dim - 1, dim >::active_cell_iterator > > vert_to_elems
std::set< typename Triangulation< dim - 1, dim >::active_cell_iterator > edge_cells
Manifold< dim - 1, dim > * manifold
bool spheroid_bool
bool used_spherical_manifold
double spheroid_x_axis
double spheroid_y_axis
double spheroid_z_axis
ConditionalOStream pcout
std::vector< TopoDS_Shape > cad_surfaces
std::vector< TopoDS_Shape > cad_curves
std::vector< std::shared_ptr< OpenCASCADE::NormalToMeshProjectionManifold< 2, 3 > > > normal_to_mesh_projectors
std::vector< std::shared_ptr< OpenCASCADE::ArclengthProjectionLineManifold< 2, 3 > > > line_projectors
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from EnableObserverPointer
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Detailed Description
template<int dim>
class ComputationalDomain< dim >
ComputationalDomain. This class handles, and provides to the other classes, ONLY the geometry of the problem. In particular
it handles the domain decomposition using a graph partitioning tool (METIS);
it reads the domain from an external file.
Definition at line 95 of file computational_domain.h.
Constructor & Destructor Documentation
ComputationalDomain()
template<int dim> ComputationalDomain< dim >::ComputationalDomain (MPI_Comm comm = MPI_COMM_WORLD)
constructor: since this is the class containing all the geometry and the base instruments needed by all the other classes, it is created first and the constructor does not need arguments. For the same reason, most of the class attributes are public: we can leter make them public end introduce suitable Get and Set methods, if needed
Definition at line 38 of file computational_domain.cc.
References comm, MPI, ComputationalDomain< dim >::pcout, ConditionalOStream::set_condition(), and ComputationalDomain< dim >::this_mpi_process.
~ComputationalDomain()
template<int dim> ComputationalDomain< dim >::~ComputationalDomain ()
Definition at line 50 of file computational_domain.cc.
Member Function Documentation
compute_double_vertex_cache()
template<int dim> void ComputationalDomain< dim >::compute_double_vertex_cache ()
Definition at line 1119 of file computational_domain.cc.
References e().
conditional_refine_and_resize()
template<int dim> void ComputationalDomain< dim >::conditional_refine_and_resize (const unsigned int refinement_level)
Definition at line 893 of file computational_domain.cc.
References Point< int dim, typename Number >::distance().
create_initial_mesh() [1/2]
template<int dim> void ComputationalDomain< dim >::create_initial_mesh ()
method to create initial mesh
Definition at line 280 of file computational_domain.cc.
References GridTools::consistently_order_cells(), and GridTools::delete_unused_vertices().
create_initial_mesh() [2/2]
void ComputationalDomain< 2 >::create_initial_mesh ()
Definition at line 273 of file computational_domain.cc.
References AssertThrow.
declare_parameters()
template<int dim> void ComputationalDomain< dim >::declare_parameters (ParameterHandler & prm) override virtual
method to declare the parameters to be read from the parameters file
Reimplemented from ParameterAcceptor.
Definition at line 69 of file computational_domain.cc.
References ParameterHandler::declare_entry(), ParameterHandler::enter_subsection(), and ParameterHandler::leave_subsection().
make_edges_conformal() [1/2]
void ComputationalDomain< 2 >::make_edges_conformal (const bool with_double_nodes, const bool isotropic_ref_on_opposite_side)
Definition at line 969 of file computational_domain.cc.
References AssertThrow.
make_edges_conformal() [2/2]
template<int dim> void ComputationalDomain< dim >::make_edges_conformal (const bool with_double_nodes = true, const bool isotropic_ref_on_opposite_side = false)
Here are the members of the class: they are all public, as the upper level classes (bem_problem, bem_fma, free_surface) will all need to perform operations based on the greometry (and the tools to handle it) contained in this class here are some basic classes needed by the program: a triangulation, and the FiniteElement and DoFHandler classes. A second DoF handler and FiniteElement must be created in order to compute the solution gradients, which are vectorial functions The double nodes treatment that we are using requires that the computational mesh is conformal in correspondence with the sharp edges. The next function detects if after a refinement step, non conformities appear across the edges. If any is found, it is fixed by refining the cell on the coarser side of the non conformity. The optional parameter isotropic_ref_on_opposite_side can be used to decide if such cell is refined isotropically (true) or only in one direction (false), which is the one needed to obtain conformity. As said the procedure is particularly important when double nodes are used to treat sharp edges. Yet, it is also possible to employ the procedure without double nodes. This can be specified assigning false to the value of the with_double_nodes parameter. Please note that the present function is able to make conformal all the triangulations that have at most one level of non conformity between cells that are neighboring across the edge. That is why, it should be called after every single refinement cycle that is carried out in the program execution.
Definition at line 980 of file computational_domain.cc.
References d(), Point< int dim, typename Number >::distance(), e(), CellAccessor< int dim, int spacedim >::neighbor(), and size.
parse_parameters()
template<int dim> void ComputationalDomain< dim >::parse_parameters (ParameterHandler & prm) override virtual
method to parse the needed parameters from the parameters file
Reimplemented from ParameterAcceptor.
Definition at line 132 of file computational_domain.cc.
References ParameterHandler::enter_subsection(), ParameterHandler::get(), ParameterHandler::get_bool(), ParameterHandler::get_double(), ParameterHandler::get_integer(), ParameterHandler::leave_subsection(), and Utilities::split_string_list().
read_domain()
template<int dim> void ComputationalDomain< dim >::read_domain ()
alternative method to read initial mesh from file
Definition at line 243 of file computational_domain.cc.
References Assert, and GridIn< int dim, int spacedim >::attach_triangulation().
refine_and_resize() [1/2]
template<int dim> void ComputationalDomain< dim >::refine_and_resize (const unsigned int refinement_level)
method to refine the imported mesh according to the level requested in the parameters file
Definition at line 557 of file computational_domain.cc.
References Triangulation< int dim, int spacedim >::begin_active(), OpenCASCADE::closest_point_and_differential_forms(), e(), Triangulation< int dim, int spacedim >::end(), fabs(), OpenCASCADE::get_shape_tolerance(), Utilities::int_to_string(), OpenCASCADE::line_intersection(), Point< int dim, typename Number >::norm(), GridTools::partition_triangulation(), OpenCASCADE::read_IGES(), and GridOut::write_ucd().
refine_and_resize() [2/2]
void ComputationalDomain< 2 >::refine_and_resize (const unsigned int refinement_level)
Definition at line 540 of file computational_domain.cc.
References GridTools::partition_triangulation(), and GridOut::write_ucd().
update_triangulation()
template<int dim> void ComputationalDomain< dim >::update_triangulation ()
Definition at line 930 of file computational_domain.cc.
References GridTools::get_subdomain_association(), GridTools::partition_triangulation(), and GridOut::write_ucd().
Member Data Documentation
cad_curves
template<int dim> std::vector<TopoDS_Shape> ComputationalDomain< dim >::cad_curves
Definition at line 284 of file computational_domain.h.
cad_surfaces
template<int dim> std::vector<TopoDS_Shape> ComputationalDomain< dim >::cad_surfaces
vectors containing the CAD surfaces and curves to be (optionally) used for refinement of the triangulation
Definition at line 283 of file computational_domain.h.
cad_to_projectors_tolerance_ratio
template<int dim> double ComputationalDomain< dim >::cad_to_projectors_tolerance_ratio
Definition at line 243 of file computational_domain.h.
cells_per_circle
template<int dim> double ComputationalDomain< dim >::cells_per_circle
Definition at line 236 of file computational_domain.h.
dirichlet_boundary_ids
template<int dim> std::vector<unsigned int> ComputationalDomain< dim >::dirichlet_boundary_ids
the material ID numbers in the mesh input file, for the dirichlet_nodes
Definition at line 252 of file computational_domain.h.
double_vertex_vector
template<int dim> std::vector<std::vector<unsigned int> > ComputationalDomain< dim >::double_vertex_vector
Definition at line 266 of file computational_domain.h.
edge_cells
template<int dim> std::set<typename Triangulation<dim - 1, dim>::active_cell_iterator> ComputationalDomain< dim >::edge_cells
Definition at line 272 of file computational_domain.h.
input_cad_path
template<int dim> std::string ComputationalDomain< dim >::input_cad_path
Definition at line 248 of file computational_domain.h.
input_grid_format
template<int dim> std::string ComputationalDomain< dim >::input_grid_format
Definition at line 247 of file computational_domain.h.
input_grid_name
template<int dim> std::string ComputationalDomain< dim >::input_grid_name
Strings identifying the input grid name and format.
Definition at line 246 of file computational_domain.h.
line_projectors
template<int dim> std::vector< std::shared_ptr<OpenCASCADE::ArclengthProjectionLineManifold<2, 3> > > ComputationalDomain< dim >::line_projectors
Definition at line 293 of file computational_domain.h.
manifold
template<int dim> Manifold<dim - 1, dim>* ComputationalDomain< dim >::manifold
Definition at line 273 of file computational_domain.h.
max_curvature_ref_cycles
template<int dim> unsigned int ComputationalDomain< dim >::max_curvature_ref_cycles
Definition at line 239 of file computational_domain.h.
max_element_aspect_ratio
template<int dim> double ComputationalDomain< dim >::max_element_aspect_ratio
maximum cell aspect ratio
Definition at line 217 of file computational_domain.h.
mpi_communicator
template<int dim> MPI_Comm ComputationalDomain< dim >::mpi_communicator
Definition at line 258 of file computational_domain.h.
n_cycles
template<int dim> unsigned int ComputationalDomain< dim >::n_cycles
number of refining cycles
here we are just renaming the cell iterator
Definition at line 209 of file computational_domain.h.
n_mpi_processes
template<int dim> unsigned int ComputationalDomain< dim >::n_mpi_processes
Definition at line 260 of file computational_domain.h.
neumann_boundary_ids
template<int dim> std::vector<unsigned int> ComputationalDomain< dim >::neumann_boundary_ids
the material ID numbers in the mesh input file, for the neumann_nodes
Definition at line 255 of file computational_domain.h.
normal_to_mesh_projectors
template<int dim> std::vector< std::shared_ptr<OpenCASCADE::NormalToMeshProjectionManifold<2, 3> > > ComputationalDomain< dim >::normal_to_mesh_projectors
vectors containing the CAD surfaces and curves projectors to be (optionally) used for refinement of the triangulation
Definition at line 290 of file computational_domain.h.
pcout
template<int dim> ConditionalOStream ComputationalDomain< dim >::pcout
Definition at line 278 of file computational_domain.h.
Referenced by ComputationalDomain< dim >::ComputationalDomain().
pre_global_refinements
template<int dim> unsigned int ComputationalDomain< dim >::pre_global_refinements
number of global refinement to executed before a local refinement cycle;
Definition at line 213 of file computational_domain.h.
spheroid_bool
template<int dim> bool ComputationalDomain< dim >::spheroid_bool
Definition at line 275 of file computational_domain.h.
spheroid_x_axis
template<int dim> double ComputationalDomain< dim >::spheroid_x_axis
Definition at line 276 of file computational_domain.h.
spheroid_y_axis
template<int dim> double ComputationalDomain< dim >::spheroid_y_axis
Definition at line 276 of file computational_domain.h.
spheroid_z_axis
template<int dim> double ComputationalDomain< dim >::spheroid_z_axis
Definition at line 276 of file computational_domain.h.
surface_curvature_refinement
template<int dim> bool ComputationalDomain< dim >::surface_curvature_refinement
Definition at line 230 of file computational_domain.h.
this_mpi_process
template<int dim> unsigned int ComputationalDomain< dim >::this_mpi_process
Definition at line 262 of file computational_domain.h.
Referenced by ComputationalDomain< dim >::ComputationalDomain().
tria
template<int dim> Triangulation<dim - 1, dim> ComputationalDomain< dim >::tria
Definition at line 197 of file computational_domain.h.
use_cad_surface_and_curves
template<int dim> bool ComputationalDomain< dim >::use_cad_surface_and_curves
Definition at line 225 of file computational_domain.h.
used_spherical_manifold
template<int dim> bool ComputationalDomain< dim >::used_spherical_manifold
Definition at line 275 of file computational_domain.h.
vert_to_elems
template<int dim> std::map< unsigned int, std::vector<typename Triangulation<dim - 1, dim>::active_cell_iterator> > ComputationalDomain< dim >::vert_to_elems
Definition at line 270 of file computational_domain.h.
vertex_on_boundary
template<int dim> std::vector<bool> ComputationalDomain< dim >::vertex_on_boundary
Definition at line 265 of file computational_domain.h.
The documentation for this class was generated from the following files:
computational_domain.h
computational_domain.cc