pi-BEM: Parallel BEM Solver: SingularKernelIntegral< dim > Class Template Reference
SingularKernelIntegral< dim > Class Template Reference
#include <singular_kernel_integral.h>
Public Member Functions
SingularKernelIntegral (const typename DoFHandler< dim - 1, dim >::active_cell_iterator &in_cell, const FiniteElement< dim - 1, dim > &in_fe, const Mapping< dim - 1, dim > &in_mapping, const Point< dim - 1 > &in_eta)
Tensor< 1, dim > evaluate_free_term_b ()
std::vector< Tensor< 1, dim > > evaluate_VkNj_integrals ()
std::vector< Tensor< 1, dim > > evaluate_WkNj_integrals ()
SingularKernelIntegral (const DoFHandler< 2, 3 >::active_cell_iterator &in_cell, const FiniteElement< 2, 3 > &in_fe, const Mapping< 2, 3 > &in_mapping, const Point< 2 > &in_eta)
SingularKernelIntegral (const DoFHandler< 1, 2 >::active_cell_iterator &in_cell, const FiniteElement< 1, 2 > &in_fe, const Mapping< 1, 2 > &in_mapping, const Point< 1 > &in_eta)
std::vector< Tensor< 1, 2 > > evaluate_VkNj_integrals ()
std::vector< Tensor< 1, 3 > > evaluate_VkNj_integrals ()
std::vector< Tensor< 1, 2 > > evaluate_WkNj_integrals ()
std::vector< Tensor< 1, 3 > > evaluate_WkNj_integrals ()
Tensor< 1, 2 > evaluate_free_term_b ()
Tensor< 1, 3 > evaluate_free_term_b ()
Private Attributes
const DoFHandler< dim-1, dim >::active_cell_iterator & cell
const FiniteElement< dim - 1, dim > & fe
const Mapping< dim - 1, dim > & mapping
const Point< dim - 1 > & eta
unsigned int rho_quadrature_order = 4
unsigned int theta_quadrature_order = 20
Detailed Description
template<int dim>
class SingularKernelIntegral< dim >
Definition at line 58 of file singular_kernel_integral.h.
Constructor & Destructor Documentation
SingularKernelIntegral() [1/3]
template<int dim> SingularKernelIntegral< dim >::SingularKernelIntegral (const typename DoFHandler< dim - 1, dim >::active_cell_iterator & in_cell, const FiniteElement< dim - 1, dim > & in_fe, const Mapping< dim - 1, dim > & in_mapping, const Point< dim - 1 > & in_eta)
SingularKernelIntegral() [2/3]
SingularKernelIntegral< 3 >::SingularKernelIntegral (const DoFHandler< 2, 3 >::active_cell_iterator & in_cell, const FiniteElement< 2, 3 > & in_fe, const Mapping< 2, 3 > & in_mapping, const Point< 2 > & in_eta)
Definition at line 5 of file singular_kernel_integral.cc.
SingularKernelIntegral() [3/3]
SingularKernelIntegral< 2 >::SingularKernelIntegral (const DoFHandler< 1, 2 >::active_cell_iterator & in_cell, const FiniteElement< 1, 2 > & in_fe, const Mapping< 1, 2 > & in_mapping, const Point< 1 > & in_eta)
Definition at line 17 of file singular_kernel_integral.cc.
Member Function Documentation
evaluate_free_term_b() [1/3]
template<int dim> Tensor< 1, dim > SingularKernelIntegral< dim >::evaluate_free_term_b ()
Referenced by BEMProblem< dim >::compute_hypersingular_free_coeffs().
evaluate_free_term_b() [2/3]
Tensor< 1, 2 > SingularKernelIntegral< 2 >::evaluate_free_term_b ()
Definition at line 1222 of file singular_kernel_integral.cc.
evaluate_free_term_b() [3/3]
Tensor< 1, 3 > SingularKernelIntegral< 3 >::evaluate_free_term_b ()
Definition at line 1231 of file singular_kernel_integral.cc.
References atan2(), b(), DoFHandler< dim, spacedim >::begin_active(), GridTools::consistently_order_cells(), cos(), Triangulation< dim, spacedim >::create_triangulation(), FE_Q< dim, spacedim >::degree, GridTools::delete_unused_vertices(), DoFHandler< dim, spacedim >::distribute_dofs(), FEValues< dim, spacedim >::get_quadrature_points(), FEValues< dim, spacedim >::jacobian(), FEValues< dim, spacedim >::jacobian_grad(), FEValues< dim, spacedim >::JxW(), Tensor< rank_, dim, class >::norm(), pow(), FEValues< dim, spacedim >::reinit(), sin(), update_gradients, update_jacobian_grads, update_jacobians, update_JxW_values, update_normal_vectors, update_quadrature_points, and update_values.
evaluate_VkNj_integrals() [1/3]
template<int dim> std::vector< Tensor< 1, dim > > SingularKernelIntegral< dim >::evaluate_VkNj_integrals ()
Referenced by BEMProblem< dim >::compute_gradients_hypersingular().
evaluate_VkNj_integrals() [2/3]
std::vector< Tensor< 1, 2 > > SingularKernelIntegral< 2 >::evaluate_VkNj_integrals ()
Definition at line 31 of file singular_kernel_integral.cc.
evaluate_VkNj_integrals() [3/3]
std::vector< Tensor< 1, 3 > > SingularKernelIntegral< 3 >::evaluate_VkNj_integrals ()
Definition at line 40 of file singular_kernel_integral.cc.
References atan2(), b(), DoFHandler< dim, spacedim >::begin_active(), GridTools::consistently_order_cells(), cos(), Triangulation< dim, spacedim >::create_triangulation(), FE_Q< dim, spacedim >::degree, GridTools::delete_unused_vertices(), DoFHandler< dim, spacedim >::distribute_dofs(), fabs(), gamma(), FEValues< dim, spacedim >::get_JxW_values(), FEValues< dim, spacedim >::get_normal_vectors(), FEValues< dim, spacedim >::get_quadrature_points(), FEValues< dim, spacedim >::jacobian(), FEValues< dim, spacedim >::jacobian_grad(), FEValues< dim, spacedim >::JxW(), log(), Tensor< rank_, dim, class >::norm(), numbers::PI, pow(), FEValues< dim, spacedim >::reinit(), FEValues< dim, spacedim >::shape_grad(), FEValues< dim, spacedim >::shape_value(), sin(), update_gradients, update_jacobian_grads, update_jacobians, update_JxW_values, update_normal_vectors, update_quadrature_points, and update_values.
evaluate_WkNj_integrals() [1/3]
template<int dim> std::vector< Tensor< 1, dim > > SingularKernelIntegral< dim >::evaluate_WkNj_integrals ()
Referenced by BEMProblem< dim >::compute_gradients_hypersingular().
evaluate_WkNj_integrals() [2/3]
std::vector< Tensor< 1, 2 > > SingularKernelIntegral< 2 >::evaluate_WkNj_integrals ()
Definition at line 629 of file singular_kernel_integral.cc.
evaluate_WkNj_integrals() [3/3]
std::vector< Tensor< 1, 3 > > SingularKernelIntegral< 3 >::evaluate_WkNj_integrals ()
Definition at line 638 of file singular_kernel_integral.cc.
References atan2(), b(), DoFHandler< dim, spacedim >::begin_active(), GridTools::consistently_order_cells(), cos(), Triangulation< dim, spacedim >::create_triangulation(), FE_Q< dim, spacedim >::degree, GridTools::delete_unused_vertices(), DoFHandler< dim, spacedim >::distribute_dofs(), fabs(), FEValues< dim, spacedim >::get_JxW_values(), FEValues< dim, spacedim >::get_quadrature_points(), FEValues< dim, spacedim >::jacobian(), FEValues< dim, spacedim >::jacobian_grad(), FEValues< dim, spacedim >::JxW(), log(), Tensor< rank_, dim, class >::norm(), numbers::PI, pow(), FEValues< dim, spacedim >::reinit(), FEValues< dim, spacedim >::shape_grad(), FEValues< dim, spacedim >::shape_value(), sin(), update_gradients, update_jacobian_grads, update_jacobians, update_JxW_values, update_normal_vectors, update_quadrature_points, and update_values.
Member Data Documentation
cell
template<int dim> const DoFHandler<dim-1,dim>::active_cell_iterator& SingularKernelIntegral< dim >::cell private
Definition at line 82 of file singular_kernel_integral.h.
eta
template<int dim> const Point<dim - 1>& SingularKernelIntegral< dim >::eta private
Definition at line 85 of file singular_kernel_integral.h.
fe
template<int dim> const FiniteElement<dim - 1, dim>& SingularKernelIntegral< dim >::fe private
Definition at line 83 of file singular_kernel_integral.h.
mapping
template<int dim> const Mapping<dim - 1, dim>& SingularKernelIntegral< dim >::mapping private
Definition at line 84 of file singular_kernel_integral.h.
rho_quadrature_order
template<int dim> unsigned int SingularKernelIntegral< dim >::rho_quadrature_order = 4 private
Definition at line 87 of file singular_kernel_integral.h.
theta_quadrature_order
template<int dim> unsigned int SingularKernelIntegral< dim >::theta_quadrature_order = 20 private
Definition at line 88 of file singular_kernel_integral.h.
The documentation for this class was generated from the following file:
singular_kernel_integral.h