pi-BEM: Parallel BEM Solver: MultipoleExpansion Class Reference
MultipoleExpansion Class Reference
#include <multipole_expansion.h>
Public Member Functions
MultipoleExpansion ()
MultipoleExpansion (const unsigned int order, const dealii::Point< 3 > &center, const AssLegFunction *assLegFunction)
MultipoleExpansion (const MultipoleExpansion &other)
~MultipoleExpansion ()
void Add (const MultipoleExpansion &multipole, const double sol)
void Add (const double strength, const dealii::Point< 3 > &point)
void Add (const MultipoleExpansion &child)
void AddNormDer (const double strength, const dealii::Point< 3 > &point, const dealii::Tensor< 1, 3 > &normal)
double Evaluate (const dealii::Point< 3 > &evalPoint)
dealii::Point< 3 > GetCenter () const
void SetCenter (const dealii::Point< 3 > &new_center)
FullMatrix< double > & GetA_n_m () const
std::complex< double > * GetCoeffs () const
std::complex< double > & GetCoeff (unsigned int n, unsigned int m) const
void SetCoeff (unsigned int n, unsigned int m, std::complex< double > &value) const
void AddToCoeff (unsigned int n, unsigned int m, std::complex< double > &value) const
MultipoleExpansion & operator= (const MultipoleExpansion &other)
Static Public Member Functions
static FullMatrix< double > A_n_m_Matrix (unsigned int dim)
Public Attributes
bool is_zero
Static Public Attributes
static FullMatrix< double > A_n_m
Private Attributes
unsigned int p
dealii::Point< 3 > center
const AssLegFunction * assLegFunction
std::complex< double > * _M_n_m
Detailed Description
Definition at line 31 of file multipole_expansion.h.
Constructor & Destructor Documentation
MultipoleExpansion() [1/3]
MultipoleExpansion::MultipoleExpansion ()
Definition at line 12 of file multipole_expansion.cc.
References _M_n_m, assLegFunction, center, is_zero, and p.
MultipoleExpansion() [2/3]
MultipoleExpansion::MultipoleExpansion (const unsigned int order, const dealii::Point< 3 > & center, const AssLegFunction * assLegFunction)
Definition at line 23 of file multipole_expansion.cc.
References _M_n_m, assLegFunction, center, is_zero, and p.
MultipoleExpansion() [3/3]
MultipoleExpansion::MultipoleExpansion (const MultipoleExpansion & other)
Definition at line 37 of file multipole_expansion.cc.
References _M_n_m, assLegFunction, center, GetCoeffs(), is_zero, and p.
~MultipoleExpansion()
MultipoleExpansion::~MultipoleExpansion ()
Definition at line 68 of file multipole_expansion.cc.
References _M_n_m.
Member Function Documentation
A_n_m_Matrix()
static FullMatrix< double > MultipoleExpansion::A_n_m_Matrix (unsigned int dim) inline static
Definition at line 124 of file multipole_expansion.h.
References A_n_m, pow(), and sqrt().
Add() [1/3]
void MultipoleExpansion::Add (const double strength, const dealii::Point< 3 > & point)
Definition at line 94 of file multipole_expansion.cc.
References abs(), AddToCoeff(), assLegFunction, atan2(), center, exp(), AssLegFunction::GetAssLegFunSph(), is_zero, p, pow(), and sqrt().
Add() [2/3]
void MultipoleExpansion::Add (const MultipoleExpansion & child)
Definition at line 185 of file multipole_expansion.cc.
References A_n_m, abs(), AddToCoeff(), assLegFunction, atan2(), center, e(), exp(), GetA_n_m(), AssLegFunction::GetAssLegFunSph(), GetCoeff(), GSL_SIGN, is_zero, p, pow(), and sqrt().
Add() [3/3]
void MultipoleExpansion::Add (const MultipoleExpansion & multipole, const double sol)
Definition at line 75 of file multipole_expansion.cc.
References AddToCoeff(), GetCoeff(), is_zero, and p.
AddNormDer()
void MultipoleExpansion::AddNormDer (const double strength, const dealii::Point< 3 > & point, const dealii::Tensor< 1, 3 > & normal)
Definition at line 125 of file multipole_expansion.cc.
References abs(), AddToCoeff(), assLegFunction, atan2(), center, cos(), exp(), AssLegFunction::GetAssLegFunSph(), AssLegFunction::GetAssLegFunSphDeriv(), is_zero, p, pow(), sin(), and sqrt().
AddToCoeff()
void MultipoleExpansion::AddToCoeff (unsigned int n, unsigned int m, std::complex< double > & value) const inline
Definition at line 114 of file multipole_expansion.h.
Referenced by Add(), Add(), Add(), and AddNormDer().
Evaluate()
double MultipoleExpansion::Evaluate (const dealii::Point< 3 > & evalPoint)
Definition at line 265 of file multipole_expansion.cc.
References abs(), assLegFunction, atan2(), center, exp(), AssLegFunction::GetAssLegFunSph(), GetCoeff(), is_zero, p, pow(), and sqrt().
GetA_n_m()
FullMatrix< double > & MultipoleExpansion::GetA_n_m () const inline
Definition at line 90 of file multipole_expansion.h.
References A_n_m.
Referenced by Add().
GetCenter()
dealii::Point< 3 > MultipoleExpansion::GetCenter () const inline
Definition at line 78 of file multipole_expansion.h.
References center.
Referenced by LocalExpansion::Add().
GetCoeff()
std::complex< double > & MultipoleExpansion::GetCoeff (unsigned int n, unsigned int m) const inline
Definition at line 102 of file multipole_expansion.h.
Referenced by LocalExpansion::Add(), Add(), Add(), and Evaluate().
GetCoeffs()
std::complex< double > * MultipoleExpansion::GetCoeffs () const inline
Definition at line 96 of file multipole_expansion.h.
References _M_n_m.
Referenced by MultipoleExpansion(), and operator=().
operator=()
MultipoleExpansion & MultipoleExpansion::operator= (const MultipoleExpansion & other)
Definition at line 52 of file multipole_expansion.cc.
References _M_n_m, assLegFunction, center, GetCoeffs(), is_zero, and p.
SetCenter()
void MultipoleExpansion::SetCenter (const dealii::Point< 3 > & new_center) inline
Definition at line 84 of file multipole_expansion.h.
Referenced by BEMFMA< dim >::generate_multipole_expansions().
SetCoeff()
void MultipoleExpansion::SetCoeff (unsigned int n, unsigned int m, std::complex< double > & value) const inline
Definition at line 108 of file multipole_expansion.h.
Member Data Documentation
_M_n_m
std::complex<double>* MultipoleExpansion::_M_n_m mutable private
Definition at line 45 of file multipole_expansion.h.
Referenced by GetCoeffs(), MultipoleExpansion(), MultipoleExpansion(), MultipoleExpansion(), operator=(), and ~MultipoleExpansion().
A_n_m
FullMatrix< double > MultipoleExpansion::A_n_m static
Initial value:
=
  MultipoleExpansion::A_n_m_Matrix(20)
Definition at line 34 of file multipole_expansion.h.
Referenced by A_n_m_Matrix(), Add(), and GetA_n_m().
assLegFunction
const AssLegFunction* MultipoleExpansion::assLegFunction mutable private
Definition at line 43 of file multipole_expansion.h.
Referenced by Add(), Add(), AddNormDer(), Evaluate(), MultipoleExpansion(), MultipoleExpansion(), MultipoleExpansion(), and operator=().
center
dealii::Point<3> MultipoleExpansion::center mutable private
Definition at line 41 of file multipole_expansion.h.
Referenced by Add(), Add(), AddNormDer(), Evaluate(), GetCenter(), MultipoleExpansion(), MultipoleExpansion(), MultipoleExpansion(), and operator=().
is_zero
bool MultipoleExpansion::is_zero mutable
Definition at line 36 of file multipole_expansion.h.
Referenced by LocalExpansion::Add(), Add(), Add(), Add(), AddNormDer(), Evaluate(), MultipoleExpansion(), MultipoleExpansion(), MultipoleExpansion(), and operator=().
p
unsigned int MultipoleExpansion::p mutable private
Definition at line 39 of file multipole_expansion.h.
Referenced by Add(), Add(), Add(), AddNormDer(), Evaluate(), MultipoleExpansion(), MultipoleExpansion(), MultipoleExpansion(), and operator=().
The documentation for this class was generated from the following files:
multipole_expansion.h
multipole_expansion.cc