pi-BEM: Parallel BEM Solver: AssLegFunction Class Reference
AssLegFunction Class Reference
#include <ass_leg_function.h>
Public Member Functions
AssLegFunction ()
~AssLegFunction ()
void AssLegFunSph (const unsigned int p, const unsigned int m, double x, double y[])
void AssLegFunSphDeriv (const unsigned int p, const unsigned int m, double x, double y[], double dy[])
double GetAssLegFunSph (const unsigned int n, const unsigned int m, double x) const
double GetAssLegFunSphDeriv (const unsigned int n, const unsigned int m, double x) const
Private Member Functions
double P_0_0 (const double x) const
double P_0_0_Deriv (const double x) const
double P_1_0 (const double x) const
double P_1_0_Deriv (const double x) const
double P_1_1 (const double x) const
double P_1_1_Deriv (const double x) const
double P_2_0 (const double x) const
double P_2_0_Deriv (const double x) const
double P_2_1 (const double x) const
double P_2_1_Deriv (const double x) const
double P_2_2 (const double x) const
double P_2_2_Deriv (const double x) const
double P_3_0 (const double x) const
double P_3_0_Deriv (const double x) const
double P_3_1 (const double x) const
double P_3_1_Deriv (const double x) const
double P_3_2 (const double x) const
double P_3_2_Deriv (const double x) const
double P_3_3 (const double x) const
double P_3_3_Deriv (const double x) const
double P_4_0 (const double x) const
double P_4_0_Deriv (const double x) const
double P_4_1 (const double x) const
double P_4_1_Deriv (const double x) const
double P_4_2 (const double x) const
double P_4_2_Deriv (const double x) const
double P_4_3 (const double x) const
double P_4_3_Deriv (const double x) const
double P_4_4 (const double x) const
double P_4_4_Deriv (const double x) const
double P_5_0 (const double x) const
double P_5_0_Deriv (const double x) const
double P_5_1 (const double x) const
double P_5_1_Deriv (const double x) const
double P_5_2 (const double x) const
double P_5_2_Deriv (const double x) const
double P_5_3 (const double x) const
double P_5_3_Deriv (const double x) const
double P_5_4 (const double x) const
double P_5_4_Deriv (const double x) const
double P_5_5 (const double x) const
double P_5_5_Deriv (const double x) const
double P_6_0 (const double x) const
double P_6_0_Deriv (const double x) const
double P_6_1 (const double x) const
double P_6_1_Deriv (const double x) const
double P_6_2 (const double x) const
double P_6_2_Deriv (const double x) const
double P_6_3 (const double x) const
double P_6_3_Deriv (const double x) const
double P_6_4 (const double x) const
double P_6_4_Deriv (const double x) const
double P_6_5 (const double x) const
double P_6_5_Deriv (const double x) const
double P_6_6 (const double x) const
double P_6_6_Deriv (const double x) const
double P_7_0 (const double x) const
double P_7_0_Deriv (const double x) const
double P_7_1 (const double x) const
double P_7_1_Deriv (const double x) const
double P_7_2 (const double x) const
double P_7_2_Deriv (const double x) const
double P_7_3 (const double x) const
double P_7_3_Deriv (const double x) const
double P_7_4 (const double x) const
double P_7_4_Deriv (const double x) const
double P_7_5 (const double x) const
double P_7_5_Deriv (const double x) const
double P_7_6 (const double x) const
double P_7_6_Deriv (const double x) const
double P_7_7 (const double x) const
double P_7_7_Deriv (const double x) const
double P_8_0 (const double x) const
double P_8_0_Deriv (const double x) const
double P_8_1 (const double x) const
double P_8_1_Deriv (const double x) const
double P_8_2 (const double x) const
double P_8_2_Deriv (const double x) const
double P_8_3 (const double x) const
double P_8_3_Deriv (const double x) const
double P_8_4 (const double x) const
double P_8_4_Deriv (const double x) const
double P_8_5 (const double x) const
double P_8_5_Deriv (const double x) const
double P_8_6 (const double x) const
double P_8_6_Deriv (const double x) const
double P_8_7 (const double x) const
double P_8_7_Deriv (const double x) const
double P_8_8 (const double x) const
double P_8_8_Deriv (const double x) const
double P_9_0 (const double x) const
double P_9_0_Deriv (const double x) const
double P_9_1 (const double x) const
double P_9_1_Deriv (const double x) const
double P_9_2 (const double x) const
double P_9_2_Deriv (const double x) const
double P_9_3 (const double x) const
double P_9_3_Deriv (const double x) const
double P_9_4 (const double x) const
double P_9_4_Deriv (const double x) const
double P_9_5 (const double x) const
double P_9_5_Deriv (const double x) const
double P_9_6 (const double x) const
double P_9_6_Deriv (const double x) const
double P_9_7 (const double x) const
double P_9_7_Deriv (const double x) const
double P_9_8 (const double x) const
double P_9_8_Deriv (const double x) const
double P_9_9 (const double x) const
double P_9_9_Deriv (const double x) const
double P_10_0 (const double x) const
double P_10_0_Deriv (const double x) const
double P_10_1 (const double x) const
double P_10_1_Deriv (const double x) const
double P_10_2 (const double x) const
double P_10_2_Deriv (const double x) const
double P_10_3 (const double x) const
double P_10_3_Deriv (const double x) const
double P_10_4 (const double x) const
double P_10_4_Deriv (const double x) const
double P_10_5 (const double x) const
double P_10_5_Deriv (const double x) const
double P_10_6 (const double x) const
double P_10_6_Deriv (const double x) const
double P_10_7 (const double x) const
double P_10_7_Deriv (const double x) const
double P_10_8 (const double x) const
double P_10_8_Deriv (const double x) const
double P_10_9 (const double x) const
double P_10_9_Deriv (const double x) const
double P_10_10 (const double x) const
double P_10_10_Deriv (const double x) const
double P_11_0 (const double x) const
double P_11_0_Deriv (const double x) const
double P_11_1 (const double x) const
double P_11_1_Deriv (const double x) const
double P_11_2 (const double x) const
double P_11_2_Deriv (const double x) const
double P_11_3 (const double x) const
double P_11_3_Deriv (const double x) const
double P_11_4 (const double x) const
double P_11_4_Deriv (const double x) const
double P_11_5 (const double x) const
double P_11_5_Deriv (const double x) const
double P_11_6 (const double x) const
double P_11_6_Deriv (const double x) const
double P_11_7 (const double x) const
double P_11_7_Deriv (const double x) const
double P_11_8 (const double x) const
double P_11_8_Deriv (const double x) const
double P_11_9 (const double x) const
double P_11_9_Deriv (const double x) const
double P_11_10 (const double x) const
double P_11_10_Deriv (const double x) const
double P_11_11 (const double x) const
double P_11_11_Deriv (const double x) const
double P_12_0 (const double x) const
double P_12_0_Deriv (const double x) const
double P_12_1 (const double x) const
double P_12_1_Deriv (const double x) const
double P_12_2 (const double x) const
double P_12_2_Deriv (const double x) const
double P_12_3 (const double x) const
double P_12_3_Deriv (const double x) const
double P_12_4 (const double x) const
double P_12_4_Deriv (const double x) const
double P_12_5 (const double x) const
double P_12_5_Deriv (const double x) const
double P_12_6 (const double x) const
double P_12_6_Deriv (const double x) const
double P_12_7 (const double x) const
double P_12_7_Deriv (const double x) const
double P_12_8 (const double x) const
double P_12_8_Deriv (const double x) const
double P_12_9 (const double x) const
double P_12_9_Deriv (const double x) const
double P_12_10 (const double x) const
double P_12_10_Deriv (const double x) const
double P_12_11 (const double x) const
double P_12_11_Deriv (const double x) const
double P_12_12 (const double x) const
double P_12_12_Deriv (const double x) const
double P_13_0 (const double x) const
double P_13_0_Deriv (const double x) const
double P_13_1 (const double x) const
double P_13_1_Deriv (const double x) const
double P_13_2 (const double x) const
double P_13_2_Deriv (const double x) const
double P_13_3 (const double x) const
double P_13_3_Deriv (const double x) const
double P_13_4 (const double x) const
double P_13_4_Deriv (const double x) const
double P_13_5 (const double x) const
double P_13_5_Deriv (const double x) const
double P_13_6 (const double x) const
double P_13_6_Deriv (const double x) const
double P_13_7 (const double x) const
double P_13_7_Deriv (const double x) const
double P_13_8 (const double x) const
double P_13_8_Deriv (const double x) const
double P_13_9 (const double x) const
double P_13_9_Deriv (const double x) const
double P_13_10 (const double x) const
double P_13_10_Deriv (const double x) const
double P_13_11 (const double x) const
double P_13_11_Deriv (const double x) const
double P_13_12 (const double x) const
double P_13_12_Deriv (const double x) const
double P_13_13 (const double x) const
double P_13_13_Deriv (const double x) const
double P_14_0 (const double x) const
double P_14_0_Deriv (const double x) const
double P_14_1 (const double x) const
double P_14_1_Deriv (const double x) const
double P_14_2 (const double x) const
double P_14_2_Deriv (const double x) const
double P_14_3 (const double x) const
double P_14_3_Deriv (const double x) const
double P_14_4 (const double x) const
double P_14_4_Deriv (const double x) const
double P_14_5 (const double x) const
double P_14_5_Deriv (const double x) const
double P_14_6 (const double x) const
double P_14_6_Deriv (const double x) const
double P_14_7 (const double x) const
double P_14_7_Deriv (const double x) const
double P_14_8 (const double x) const
double P_14_8_Deriv (const double x) const
double P_14_9 (const double x) const
double P_14_9_Deriv (const double x) const
double P_14_10 (const double x) const
double P_14_10_Deriv (const double x) const
double P_14_11 (const double x) const
double P_14_11_Deriv (const double x) const
double P_14_12 (const double x) const
double P_14_12_Deriv (const double x) const
double P_14_13 (const double x) const
double P_14_13_Deriv (const double x) const
double P_14_14 (const double x) const
double P_14_14_Deriv (const double x) const
double P_15_0 (const double x) const
double P_15_0_Deriv (const double x) const
double P_15_1 (const double x) const
double P_15_1_Deriv (const double x) const
double P_15_2 (const double x) const
double P_15_2_Deriv (const double x) const
double P_15_3 (const double x) const
double P_15_3_Deriv (const double x) const
double P_15_4 (const double x) const
double P_15_4_Deriv (const double x) const
double P_15_5 (const double x) const
double P_15_5_Deriv (const double x) const
double P_15_6 (const double x) const
double P_15_6_Deriv (const double x) const
double P_15_7 (const double x) const
double P_15_7_Deriv (const double x) const
double P_15_8 (const double x) const
double P_15_8_Deriv (const double x) const
double P_15_9 (const double x) const
double P_15_9_Deriv (const double x) const
double P_15_10 (const double x) const
double P_15_10_Deriv (const double x) const
double P_15_11 (const double x) const
double P_15_11_Deriv (const double x) const
double P_15_12 (const double x) const
double P_15_12_Deriv (const double x) const
double P_15_13 (const double x) const
double P_15_13_Deriv (const double x) const
double P_15_14 (const double x) const
double P_15_14_Deriv (const double x) const
double P_15_15 (const double x) const
double P_15_15_Deriv (const double x) const
double P_16_0 (const double x) const
double P_16_0_Deriv (const double x) const
double P_16_1 (const double x) const
double P_16_1_Deriv (const double x) const
double P_16_2 (const double x) const
double P_16_2_Deriv (const double x) const
double P_16_3 (const double x) const
double P_16_3_Deriv (const double x) const
double P_16_4 (const double x) const
double P_16_4_Deriv (const double x) const
double P_16_5 (const double x) const
double P_16_5_Deriv (const double x) const
double P_16_6 (const double x) const
double P_16_6_Deriv (const double x) const
double P_16_7 (const double x) const
double P_16_7_Deriv (const double x) const
double P_16_8 (const double x) const
double P_16_8_Deriv (const double x) const
double P_16_9 (const double x) const
double P_16_9_Deriv (const double x) const
double P_16_10 (const double x) const
double P_16_10_Deriv (const double x) const
double P_16_11 (const double x) const
double P_16_11_Deriv (const double x) const
double P_16_12 (const double x) const
double P_16_12_Deriv (const double x) const
double P_16_13 (const double x) const
double P_16_13_Deriv (const double x) const
double P_16_14 (const double x) const
double P_16_14_Deriv (const double x) const
double P_16_15 (const double x) const
double P_16_15_Deriv (const double x) const
double P_16_16 (const double x) const
double P_16_16_Deriv (const double x) const
double P_17_0 (const double x) const
double P_17_0_Deriv (const double x) const
double P_17_1 (const double x) const
double P_17_1_Deriv (const double x) const
double P_17_2 (const double x) const
double P_17_2_Deriv (const double x) const
double P_17_3 (const double x) const
double P_17_3_Deriv (const double x) const
double P_17_4 (const double x) const
double P_17_4_Deriv (const double x) const
double P_17_5 (const double x) const
double P_17_5_Deriv (const double x) const
double P_17_6 (const double x) const
double P_17_6_Deriv (const double x) const
double P_17_7 (const double x) const
double P_17_7_Deriv (const double x) const
double P_17_8 (const double x) const
double P_17_8_Deriv (const double x) const
double P_17_9 (const double x) const
double P_17_9_Deriv (const double x) const
double P_17_10 (const double x) const
double P_17_10_Deriv (const double x) const
double P_17_11 (const double x) const
double P_17_11_Deriv (const double x) const
double P_17_12 (const double x) const
double P_17_12_Deriv (const double x) const
double P_17_13 (const double x) const
double P_17_13_Deriv (const double x) const
double P_17_14 (const double x) const
double P_17_14_Deriv (const double x) const
double P_17_15 (const double x) const
double P_17_15_Deriv (const double x) const
double P_17_16 (const double x) const
double P_17_16_Deriv (const double x) const
double P_17_17 (const double x) const
double P_17_17_Deriv (const double x) const
double P_18_0 (const double x) const
double P_18_0_Deriv (const double x) const
double P_18_1 (const double x) const
double P_18_1_Deriv (const double x) const
double P_18_2 (const double x) const
double P_18_2_Deriv (const double x) const
double P_18_3 (const double x) const
double P_18_3_Deriv (const double x) const
double P_18_4 (const double x) const
double P_18_4_Deriv (const double x) const
double P_18_5 (const double x) const
double P_18_5_Deriv (const double x) const
double P_18_6 (const double x) const
double P_18_6_Deriv (const double x) const
double P_18_7 (const double x) const
double P_18_7_Deriv (const double x) const
double P_18_8 (const double x) const
double P_18_8_Deriv (const double x) const
double P_18_9 (const double x) const
double P_18_9_Deriv (const double x) const
double P_18_10 (const double x) const
double P_18_10_Deriv (const double x) const
double P_18_11 (const double x) const
double P_18_11_Deriv (const double x) const
double P_18_12 (const double x) const
double P_18_12_Deriv (const double x) const
double P_18_13 (const double x) const
double P_18_13_Deriv (const double x) const
double P_18_14 (const double x) const
double P_18_14_Deriv (const double x) const
double P_18_15 (const double x) const
double P_18_15_Deriv (const double x) const
double P_18_16 (const double x) const
double P_18_16_Deriv (const double x) const
double P_18_17 (const double x) const
double P_18_17_Deriv (const double x) const
double P_18_18 (const double x) const
double P_18_18_Deriv (const double x) const
double P_19_0 (const double x) const
double P_19_0_Deriv (const double x) const
double P_19_1 (const double x) const
double P_19_1_Deriv (const double x) const
double P_19_2 (const double x) const
double P_19_2_Deriv (const double x) const
double P_19_3 (const double x) const
double P_19_3_Deriv (const double x) const
double P_19_4 (const double x) const
double P_19_4_Deriv (const double x) const
double P_19_5 (const double x) const
double P_19_5_Deriv (const double x) const
double P_19_6 (const double x) const
double P_19_6_Deriv (const double x) const
double P_19_7 (const double x) const
double P_19_7_Deriv (const double x) const
double P_19_8 (const double x) const
double P_19_8_Deriv (const double x) const
double P_19_9 (const double x) const
double P_19_9_Deriv (const double x) const
double P_19_10 (const double x) const
double P_19_10_Deriv (const double x) const
double P_19_11 (const double x) const
double P_19_11_Deriv (const double x) const
double P_19_12 (const double x) const
double P_19_12_Deriv (const double x) const
double P_19_13 (const double x) const
double P_19_13_Deriv (const double x) const
double P_19_14 (const double x) const
double P_19_14_Deriv (const double x) const
double P_19_15 (const double x) const
double P_19_15_Deriv (const double x) const
double P_19_16 (const double x) const
double P_19_16_Deriv (const double x) const
double P_19_17 (const double x) const
double P_19_17_Deriv (const double x) const
double P_19_18 (const double x) const
double P_19_18_Deriv (const double x) const
double P_19_19 (const double x) const
double P_19_19_Deriv (const double x) const
double P_20_0 (const double x) const
double P_20_0_Deriv (const double x) const
double P_20_1 (const double x) const
double P_20_1_Deriv (const double x) const
double P_20_2 (const double x) const
double P_20_2_Deriv (const double x) const
double P_20_3 (const double x) const
double P_20_3_Deriv (const double x) const
double P_20_4 (const double x) const
double P_20_4_Deriv (const double x) const
double P_20_5 (const double x) const
double P_20_5_Deriv (const double x) const
double P_20_6 (const double x) const
double P_20_6_Deriv (const double x) const
double P_20_7 (const double x) const
double P_20_7_Deriv (const double x) const
double P_20_8 (const double x) const
double P_20_8_Deriv (const double x) const
double P_20_9 (const double x) const
double P_20_9_Deriv (const double x) const
double P_20_10 (const double x) const
double P_20_10_Deriv (const double x) const
double P_20_11 (const double x) const
double P_20_11_Deriv (const double x) const
double P_20_12 (const double x) const
double P_20_12_Deriv (const double x) const
double P_20_13 (const double x) const
double P_20_13_Deriv (const double x) const
double P_20_14 (const double x) const
double P_20_14_Deriv (const double x) const
double P_20_15 (const double x) const
double P_20_15_Deriv (const double x) const
double P_20_16 (const double x) const
double P_20_16_Deriv (const double x) const
double P_20_17 (const double x) const
double P_20_17_Deriv (const double x) const
double P_20_18 (const double x) const
double P_20_18_Deriv (const double x) const
double P_20_19 (const double x) const
double P_20_19_Deriv (const double x) const
double P_20_20 (const double x) const
double P_20_20_Deriv (const double x) const
Private Attributes
std::vector< std::vector< double(AssLegFunction::*)(const double) const > > leg_pointers
std::vector< std::vector< double(AssLegFunction::*)(const double) const > > leg_der_pointers
Detailed Description
Definition at line 47 of file ass_leg_function.h.
Constructor & Destructor Documentation
AssLegFunction()
AssLegFunction::AssLegFunction ()
Definition at line 6 of file ass_leg_function.cc.
References leg_der_pointers, leg_pointers, P_0_0(), P_0_0_Deriv(), P_10_0(), P_10_0_Deriv(), P_10_1(), P_10_10(), P_10_10_Deriv(), P_10_1_Deriv(), P_10_2(), P_10_2_Deriv(), P_10_3(), P_10_3_Deriv(), P_10_4(), P_10_4_Deriv(), P_10_5(), P_10_5_Deriv(), P_10_6(), P_10_6_Deriv(), P_10_7(), P_10_7_Deriv(), P_10_8(), P_10_8_Deriv(), P_10_9(), P_10_9_Deriv(), P_11_0(), P_11_0_Deriv(), P_11_1(), P_11_10(), P_11_10_Deriv(), P_11_11(), P_11_11_Deriv(), P_11_1_Deriv(), P_11_2(), P_11_2_Deriv(), P_11_3(), P_11_3_Deriv(), P_11_4(), P_11_4_Deriv(), P_11_5(), P_11_5_Deriv(), P_11_6(), P_11_6_Deriv(), P_11_7(), P_11_7_Deriv(), P_11_8(), P_11_8_Deriv(), P_11_9(), P_11_9_Deriv(), P_12_0(), P_12_0_Deriv(), P_12_1(), P_12_10(), P_12_10_Deriv(), P_12_11(), P_12_11_Deriv(), P_12_12(), P_12_12_Deriv(), P_12_1_Deriv(), P_12_2(), P_12_2_Deriv(), P_12_3(), P_12_3_Deriv(), P_12_4(), P_12_4_Deriv(), P_12_5(), P_12_5_Deriv(), P_12_6(), P_12_6_Deriv(), P_12_7(), P_12_7_Deriv(), P_12_8(), P_12_8_Deriv(), P_12_9(), P_12_9_Deriv(), P_13_0(), P_13_0_Deriv(), P_13_1(), P_13_10(), P_13_10_Deriv(), P_13_11(), P_13_11_Deriv(), P_13_12(), P_13_12_Deriv(), P_13_13(), P_13_13_Deriv(), P_13_1_Deriv(), P_13_2(), P_13_2_Deriv(), P_13_3(), P_13_3_Deriv(), P_13_4(), P_13_4_Deriv(), P_13_5(), P_13_5_Deriv(), P_13_6(), P_13_6_Deriv(), P_13_7(), P_13_7_Deriv(), P_13_8(), P_13_8_Deriv(), P_13_9(), P_13_9_Deriv(), P_14_0(), P_14_0_Deriv(), P_14_1(), P_14_10(), P_14_10_Deriv(), P_14_11(), P_14_11_Deriv(), P_14_12(), P_14_12_Deriv(), P_14_13(), P_14_13_Deriv(), P_14_14(), P_14_14_Deriv(), P_14_1_Deriv(), P_14_2(), P_14_2_Deriv(), P_14_3(), P_14_3_Deriv(), P_14_4(), P_14_4_Deriv(), P_14_5(), P_14_5_Deriv(), P_14_6(), P_14_6_Deriv(), P_14_7(), P_14_7_Deriv(), P_14_8(), P_14_8_Deriv(), P_14_9(), P_14_9_Deriv(), P_15_0(), P_15_0_Deriv(), P_15_1(), P_15_10(), P_15_10_Deriv(), P_15_11(), P_15_11_Deriv(), P_15_12(), P_15_12_Deriv(), P_15_13(), P_15_13_Deriv(), P_15_14(), P_15_14_Deriv(), P_15_15(), P_15_15_Deriv(), P_15_1_Deriv(), P_15_2(), P_15_2_Deriv(), P_15_3(), P_15_3_Deriv(), P_15_4(), P_15_4_Deriv(), P_15_5(), P_15_5_Deriv(), P_15_6(), P_15_6_Deriv(), P_15_7(), P_15_7_Deriv(), P_15_8(), P_15_8_Deriv(), P_15_9(), P_15_9_Deriv(), P_16_0(), P_16_0_Deriv(), P_16_1(), P_16_10(), P_16_10_Deriv(), P_16_11(), P_16_11_Deriv(), P_16_12(), P_16_12_Deriv(), P_16_13(), P_16_13_Deriv(), P_16_14(), P_16_14_Deriv(), P_16_15(), P_16_15_Deriv(), P_16_16(), P_16_16_Deriv(), P_16_1_Deriv(), P_16_2(), P_16_2_Deriv(), P_16_3(), P_16_3_Deriv(), P_16_4(), P_16_4_Deriv(), P_16_5(), P_16_5_Deriv(), P_16_6(), P_16_6_Deriv(), P_16_7(), P_16_7_Deriv(), P_16_8(), P_16_8_Deriv(), P_16_9(), P_16_9_Deriv(), P_17_0(), P_17_0_Deriv(), P_17_1(), P_17_10(), P_17_10_Deriv(), P_17_11(), P_17_11_Deriv(), P_17_12(), P_17_12_Deriv(), P_17_13(), P_17_13_Deriv(), P_17_14(), P_17_14_Deriv(), P_17_15(), P_17_15_Deriv(), P_17_16(), P_17_16_Deriv(), P_17_17(), P_17_17_Deriv(), P_17_1_Deriv(), P_17_2(), P_17_2_Deriv(), P_17_3(), P_17_3_Deriv(), P_17_4(), P_17_4_Deriv(), P_17_5(), P_17_5_Deriv(), P_17_6(), P_17_6_Deriv(), P_17_7(), P_17_7_Deriv(), P_17_8(), P_17_8_Deriv(), P_17_9(), P_17_9_Deriv(), P_18_0(), P_18_0_Deriv(), P_18_1(), P_18_10(), P_18_10_Deriv(), P_18_11(), P_18_11_Deriv(), P_18_12(), P_18_12_Deriv(), P_18_13(), P_18_13_Deriv(), P_18_14(), P_18_14_Deriv(), P_18_15(), P_18_15_Deriv(), P_18_16(), P_18_16_Deriv(), P_18_17(), P_18_17_Deriv(), P_18_18(), P_18_18_Deriv(), P_18_1_Deriv(), P_18_2(), P_18_2_Deriv(), P_18_3(), P_18_3_Deriv(), P_18_4(), P_18_4_Deriv(), P_18_5(), P_18_5_Deriv(), P_18_6(), P_18_6_Deriv(), P_18_7(), P_18_7_Deriv(), P_18_8(), P_18_8_Deriv(), P_18_9(), P_18_9_Deriv(), P_19_0(), P_19_0_Deriv(), P_19_1(), P_19_10(), P_19_10_Deriv(), P_19_11(), P_19_11_Deriv(), P_19_12(), P_19_12_Deriv(), P_19_13(), P_19_13_Deriv(), P_19_14(), P_19_14_Deriv(), P_19_15(), P_19_15_Deriv(), P_19_16(), P_19_16_Deriv(), P_19_17(), P_19_17_Deriv(), P_19_18(), P_19_18_Deriv(), P_19_19(), P_19_19_Deriv(), P_19_1_Deriv(), P_19_2(), P_19_2_Deriv(), P_19_3(), P_19_3_Deriv(), P_19_4(), P_19_4_Deriv(), P_19_5(), P_19_5_Deriv(), P_19_6(), P_19_6_Deriv(), P_19_7(), P_19_7_Deriv(), P_19_8(), P_19_8_Deriv(), P_19_9(), P_19_9_Deriv(), P_1_0(), P_1_0_Deriv(), P_1_1(), P_1_1_Deriv(), P_20_0(), P_20_0_Deriv(), P_20_1(), P_20_10(), P_20_10_Deriv(), P_20_11(), P_20_11_Deriv(), P_20_12(), P_20_12_Deriv(), P_20_13(), P_20_13_Deriv(), P_20_14(), P_20_14_Deriv(), P_20_15(), P_20_15_Deriv(), P_20_16(), P_20_16_Deriv(), P_20_17(), P_20_17_Deriv(), P_20_18(), P_20_18_Deriv(), P_20_19(), P_20_19_Deriv(), P_20_1_Deriv(), P_20_2(), P_20_20(), P_20_20_Deriv(), P_20_2_Deriv(), P_20_3(), P_20_3_Deriv(), P_20_4(), P_20_4_Deriv(), P_20_5(), P_20_5_Deriv(), P_20_6(), P_20_6_Deriv(), P_20_7(), P_20_7_Deriv(), P_20_8(), P_20_8_Deriv(), P_20_9(), P_20_9_Deriv(), P_2_0(), P_2_0_Deriv(), P_2_1(), P_2_1_Deriv(), P_2_2(), P_2_2_Deriv(), P_3_0(), P_3_0_Deriv(), P_3_1(), P_3_1_Deriv(), P_3_2(), P_3_2_Deriv(), P_3_3(), P_3_3_Deriv(), P_4_0(), P_4_0_Deriv(), P_4_1(), P_4_1_Deriv(), P_4_2(), P_4_2_Deriv(), P_4_3(), P_4_3_Deriv(), P_4_4(), P_4_4_Deriv(), P_5_0(), P_5_0_Deriv(), P_5_1(), P_5_1_Deriv(), P_5_2(), P_5_2_Deriv(), P_5_3(), P_5_3_Deriv(), P_5_4(), P_5_4_Deriv(), P_5_5(), P_5_5_Deriv(), P_6_0(), P_6_0_Deriv(), P_6_1(), P_6_1_Deriv(), P_6_2(), P_6_2_Deriv(), P_6_3(), P_6_3_Deriv(), P_6_4(), P_6_4_Deriv(), P_6_5(), P_6_5_Deriv(), P_6_6(), P_6_6_Deriv(), P_7_0(), P_7_0_Deriv(), P_7_1(), P_7_1_Deriv(), P_7_2(), P_7_2_Deriv(), P_7_3(), P_7_3_Deriv(), P_7_4(), P_7_4_Deriv(), P_7_5(), P_7_5_Deriv(), P_7_6(), P_7_6_Deriv(), P_7_7(), P_7_7_Deriv(), P_8_0(), P_8_0_Deriv(), P_8_1(), P_8_1_Deriv(), P_8_2(), P_8_2_Deriv(), P_8_3(), P_8_3_Deriv(), P_8_4(), P_8_4_Deriv(), P_8_5(), P_8_5_Deriv(), P_8_6(), P_8_6_Deriv(), P_8_7(), P_8_7_Deriv(), P_8_8(), P_8_8_Deriv(), P_9_0(), P_9_0_Deriv(), P_9_1(), P_9_1_Deriv(), P_9_2(), P_9_2_Deriv(), P_9_3(), P_9_3_Deriv(), P_9_4(), P_9_4_Deriv(), P_9_5(), P_9_5_Deriv(), P_9_6(), P_9_6_Deriv(), P_9_7(), P_9_7_Deriv(), P_9_8(), P_9_8_Deriv(), P_9_9(), and P_9_9_Deriv().
~AssLegFunction()
AssLegFunction::~AssLegFunction ()
Definition at line 485 of file ass_leg_function.cc.
Member Function Documentation
AssLegFunSph()
void AssLegFunction::AssLegFunSph (const unsigned int p, const unsigned int m, double x, double y[])
Definition at line 491 of file ass_leg_function.cc.
References leg_pointers.
AssLegFunSphDeriv()
void AssLegFunction::AssLegFunSphDeriv (const unsigned int p, const unsigned int m, double x, double y[], double dy[])
Definition at line 505 of file ass_leg_function.cc.
References leg_der_pointers, and leg_pointers.
GetAssLegFunSph()
double AssLegFunction::GetAssLegFunSph (const unsigned int n, const unsigned int m, double x) const
Definition at line 521 of file ass_leg_function.cc.
References leg_pointers.
Referenced by LocalExpansion::Add(), LocalExpansion::Add(), MultipoleExpansion::Add(), MultipoleExpansion::Add(), MultipoleExpansion::AddNormDer(), LocalExpansion::Evaluate(), and MultipoleExpansion::Evaluate().
GetAssLegFunSphDeriv()
double AssLegFunction::GetAssLegFunSphDeriv (const unsigned int n, const unsigned int m, double x) const
Definition at line 530 of file ass_leg_function.cc.
References leg_der_pointers.
Referenced by MultipoleExpansion::AddNormDer().
P_0_0()
double AssLegFunction::P_0_0 (const double x) const private
Declaration of each of the functions.
Definition at line 539 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_0_0_Deriv()
double AssLegFunction::P_0_0_Deriv (const double x) const private
Definition at line 545 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_10_0()
double AssLegFunction::P_10_0 (const double x) const private
Definition at line 2552 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_10_0_Deriv()
double AssLegFunction::P_10_0_Deriv (const double x) const private
Definition at line 2572 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_10_1()
double AssLegFunction::P_10_1 (const double x) const private
Definition at line 2596 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_10()
double AssLegFunction::P_10_10 (const double x) const private
Definition at line 3083 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_10_Deriv()
double AssLegFunction::P_10_10_Deriv (const double x) const private
Definition at line 3101 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_10_1_Deriv()
double AssLegFunction::P_10_1_Deriv (const double x) const private
Definition at line 2628 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_2()
double AssLegFunction::P_10_2 (const double x) const private
Definition at line 2667 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_2_Deriv()
double AssLegFunction::P_10_2_Deriv (const double x) const private
Definition at line 2695 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_3()
double AssLegFunction::P_10_3 (const double x) const private
Definition at line 2730 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_3_Deriv()
double AssLegFunction::P_10_3_Deriv (const double x) const private
Definition at line 2758 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_4()
double AssLegFunction::P_10_4 (const double x) const private
Definition at line 2792 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_4_Deriv()
double AssLegFunction::P_10_4_Deriv (const double x) const private
Definition at line 2817 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_5()
double AssLegFunction::P_10_5 (const double x) const private
Definition at line 2847 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_5_Deriv()
double AssLegFunction::P_10_5_Deriv (const double x) const private
Definition at line 2875 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_6()
double AssLegFunction::P_10_6 (const double x) const private
Definition at line 2907 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_6_Deriv()
double AssLegFunction::P_10_6_Deriv (const double x) const private
Definition at line 2932 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_7()
double AssLegFunction::P_10_7 (const double x) const private
Definition at line 2961 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_7_Deriv()
double AssLegFunction::P_10_7_Deriv (const double x) const private
Definition at line 2981 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_8()
double AssLegFunction::P_10_8 (const double x) const private
Definition at line 3005 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_10_8_Deriv()
double AssLegFunction::P_10_8_Deriv (const double x) const private
Definition at line 3022 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_9()
double AssLegFunction::P_10_9 (const double x) const private
Definition at line 3043 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_10_9_Deriv()
double AssLegFunction::P_10_9_Deriv (const double x) const private
Definition at line 3063 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_0()
double AssLegFunction::P_11_0 (const double x) const private
Definition at line 3115 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_11_0_Deriv()
double AssLegFunction::P_11_0_Deriv (const double x) const private
Definition at line 3138 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_11_1()
double AssLegFunction::P_11_1 (const double x) const private
Definition at line 3160 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_10()
double AssLegFunction::P_11_10 (const double x) const private
Definition at line 3700 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_10_Deriv()
double AssLegFunction::P_11_10_Deriv (const double x) const private
Definition at line 3718 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_11()
double AssLegFunction::P_11_11 (const double x) const private
Definition at line 3736 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_11_Deriv()
double AssLegFunction::P_11_11_Deriv (const double x) const private
Definition at line 3756 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_1_Deriv()
double AssLegFunction::P_11_1_Deriv (const double x) const private
Definition at line 3191 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_2()
double AssLegFunction::P_11_2 (const double x) const private
Definition at line 3231 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_2_Deriv()
double AssLegFunction::P_11_2_Deriv (const double x) const private
Definition at line 3262 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_3()
double AssLegFunction::P_11_3 (const double x) const private
Definition at line 3298 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_3_Deriv()
double AssLegFunction::P_11_3_Deriv (const double x) const private
Definition at line 3328 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_4()
double AssLegFunction::P_11_4 (const double x) const private
Definition at line 3368 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_4_Deriv()
double AssLegFunction::P_11_4_Deriv (const double x) const private
Definition at line 3397 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_5()
double AssLegFunction::P_11_5 (const double x) const private
Definition at line 3432 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_5_Deriv()
double AssLegFunction::P_11_5_Deriv (const double x) const private
Definition at line 3460 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_6()
double AssLegFunction::P_11_6 (const double x) const private
Definition at line 3493 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_6_Deriv()
double AssLegFunction::P_11_6_Deriv (const double x) const private
Definition at line 3519 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_7()
double AssLegFunction::P_11_7 (const double x) const private
Definition at line 3550 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_7_Deriv()
double AssLegFunction::P_11_7_Deriv (const double x) const private
Definition at line 3578 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_8()
double AssLegFunction::P_11_8 (const double x) const private
Definition at line 3610 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_8_Deriv()
double AssLegFunction::P_11_8_Deriv (const double x) const private
Definition at line 3631 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_9()
double AssLegFunction::P_11_9 (const double x) const private
Definition at line 3655 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_11_9_Deriv()
double AssLegFunction::P_11_9_Deriv (const double x) const private
Definition at line 3677 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_0()
double AssLegFunction::P_12_0 (const double x) const private
Definition at line 3774 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_12_0_Deriv()
double AssLegFunction::P_12_0_Deriv (const double x) const private
Definition at line 3795 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_12_1()
double AssLegFunction::P_12_1 (const double x) const private
Definition at line 3820 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_10()
double AssLegFunction::P_12_10 (const double x) const private
Definition at line 4413 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_10_Deriv()
double AssLegFunction::P_12_10_Deriv (const double x) const private
Definition at line 4433 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_11()
double AssLegFunction::P_12_11 (const double x) const private
Definition at line 4455 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_11_Deriv()
double AssLegFunction::P_12_11_Deriv (const double x) const private
Definition at line 4475 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_12()
double AssLegFunction::P_12_12 (const double x) const private
Definition at line 4495 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_12_12_Deriv()
double AssLegFunction::P_12_12_Deriv (const double x) const private
Definition at line 4511 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_1_Deriv()
double AssLegFunction::P_12_1_Deriv (const double x) const private
Definition at line 3854 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_2()
double AssLegFunction::P_12_2 (const double x) const private
Definition at line 3898 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_2_Deriv()
double AssLegFunction::P_12_2_Deriv (const double x) const private
Definition at line 3927 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_3()
double AssLegFunction::P_12_3 (const double x) const private
Definition at line 3965 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_3_Deriv()
double AssLegFunction::P_12_3_Deriv (const double x) const private
Definition at line 3999 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_4()
double AssLegFunction::P_12_4 (const double x) const private
Definition at line 4041 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_4_Deriv()
double AssLegFunction::P_12_4_Deriv (const double x) const private
Definition at line 4072 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_5()
double AssLegFunction::P_12_5 (const double x) const private
Definition at line 4113 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_5_Deriv()
double AssLegFunction::P_12_5_Deriv (const double x) const private
Definition at line 4144 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_6()
double AssLegFunction::P_12_6 (const double x) const private
Definition at line 4183 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_6_Deriv()
double AssLegFunction::P_12_6_Deriv (const double x) const private
Definition at line 4210 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_7()
double AssLegFunction::P_12_7 (const double x) const private
Definition at line 4242 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_7_Deriv()
double AssLegFunction::P_12_7_Deriv (const double x) const private
Definition at line 4270 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_8()
double AssLegFunction::P_12_8 (const double x) const private
Definition at line 4303 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_8_Deriv()
double AssLegFunction::P_12_8_Deriv (const double x) const private
Definition at line 4331 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_9()
double AssLegFunction::P_12_9 (const double x) const private
Definition at line 4363 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_12_9_Deriv()
double AssLegFunction::P_12_9_Deriv (const double x) const private
Definition at line 4386 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_0()
double AssLegFunction::P_13_0 (const double x) const private
Definition at line 4527 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_13_0_Deriv()
double AssLegFunction::P_13_0_Deriv (const double x) const private
Definition at line 4552 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_13_1()
double AssLegFunction::P_13_1 (const double x) const private
Definition at line 4576 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_10()
double AssLegFunction::P_13_10 (const double x) const private
Definition at line 5217 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_10_Deriv()
double AssLegFunction::P_13_10_Deriv (const double x) const private
Definition at line 5238 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_11()
double AssLegFunction::P_13_11 (const double x) const private
Definition at line 5263 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_11_Deriv()
double AssLegFunction::P_13_11_Deriv (const double x) const private
Definition at line 5286 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_12()
double AssLegFunction::P_13_12 (const double x) const private
Definition at line 5310 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_13_12_Deriv()
double AssLegFunction::P_13_12_Deriv (const double x) const private
Definition at line 5326 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_13()
double AssLegFunction::P_13_13 (const double x) const private
Definition at line 5345 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_13_Deriv()
double AssLegFunction::P_13_13_Deriv (const double x) const private
Definition at line 5365 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_1_Deriv()
double AssLegFunction::P_13_1_Deriv (const double x) const private
Definition at line 4610 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_2()
double AssLegFunction::P_13_2 (const double x) const private
Definition at line 4657 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_2_Deriv()
double AssLegFunction::P_13_2_Deriv (const double x) const private
Definition at line 4690 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_3()
double AssLegFunction::P_13_3 (const double x) const private
Definition at line 4732 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_3_Deriv()
double AssLegFunction::P_13_3_Deriv (const double x) const private
Definition at line 4764 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_4()
double AssLegFunction::P_13_4 (const double x) const private
Definition at line 4808 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_4_Deriv()
double AssLegFunction::P_13_4_Deriv (const double x) const private
Definition at line 4842 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_5()
double AssLegFunction::P_13_5 (const double x) const private
Definition at line 4885 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_5_Deriv()
double AssLegFunction::P_13_5_Deriv (const double x) const private
Definition at line 4919 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_6()
double AssLegFunction::P_13_6 (const double x) const private
Definition at line 4963 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_6_Deriv()
double AssLegFunction::P_13_6_Deriv (const double x) const private
Definition at line 4992 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_7()
double AssLegFunction::P_13_7 (const double x) const private
Definition at line 5029 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_7_Deriv()
double AssLegFunction::P_13_7_Deriv (const double x) const private
Definition at line 5058 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_8()
double AssLegFunction::P_13_8 (const double x) const private
Definition at line 5092 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_8_Deriv()
double AssLegFunction::P_13_8_Deriv (const double x) const private
Definition at line 5120 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_9()
double AssLegFunction::P_13_9 (const double x) const private
Definition at line 5153 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_13_9_Deriv()
double AssLegFunction::P_13_9_Deriv (const double x) const private
Definition at line 5183 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_0()
double AssLegFunction::P_14_0 (const double x) const private
Definition at line 5383 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_14_0_Deriv()
double AssLegFunction::P_14_0_Deriv (const double x) const private
Definition at line 5409 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_14_1()
double AssLegFunction::P_14_1 (const double x) const private
Definition at line 5438 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_10()
double AssLegFunction::P_14_10 (const double x) const private
Definition at line 6117 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_10_Deriv()
double AssLegFunction::P_14_10_Deriv (const double x) const private
Definition at line 6145 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_11()
double AssLegFunction::P_14_11 (const double x) const private
Definition at line 6177 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_11_Deriv()
double AssLegFunction::P_14_11_Deriv (const double x) const private
Definition at line 6200 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_12()
double AssLegFunction::P_14_12 (const double x) const private
Definition at line 6227 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_14_12_Deriv()
double AssLegFunction::P_14_12_Deriv (const double x) const private
Definition at line 6246 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_13()
double AssLegFunction::P_14_13 (const double x) const private
Definition at line 6268 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_13_Deriv()
double AssLegFunction::P_14_13_Deriv (const double x) const private
Definition at line 6288 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_14()
double AssLegFunction::P_14_14 (const double x) const private
Definition at line 6309 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_14_Deriv()
double AssLegFunction::P_14_14_Deriv (const double x) const private
Definition at line 6327 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_14_1_Deriv()
double AssLegFunction::P_14_1_Deriv (const double x) const private
Definition at line 5476 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_2()
double AssLegFunction::P_14_2 (const double x) const private
Definition at line 5529 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_2_Deriv()
double AssLegFunction::P_14_2_Deriv (const double x) const private
Definition at line 5561 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_3()
double AssLegFunction::P_14_3 (const double x) const private
Definition at line 5605 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_3_Deriv()
double AssLegFunction::P_14_3_Deriv (const double x) const private
Definition at line 5640 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_4()
double AssLegFunction::P_14_4 (const double x) const private
Definition at line 5687 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_4_Deriv()
double AssLegFunction::P_14_4_Deriv (const double x) const private
Definition at line 5720 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_5()
double AssLegFunction::P_14_5 (const double x) const private
Definition at line 5764 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_5_Deriv()
double AssLegFunction::P_14_5_Deriv (const double x) const private
Definition at line 5800 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_6()
double AssLegFunction::P_14_6 (const double x) const private
Definition at line 5845 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_6_Deriv()
double AssLegFunction::P_14_6_Deriv (const double x) const private
Definition at line 5877 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_7()
double AssLegFunction::P_14_7 (const double x) const private
Definition at line 5919 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_7_Deriv()
double AssLegFunction::P_14_7_Deriv (const double x) const private
Definition at line 5950 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_8()
double AssLegFunction::P_14_8 (const double x) const private
Definition at line 5989 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_8_Deriv()
double AssLegFunction::P_14_8_Deriv (const double x) const private
Definition at line 6018 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_9()
double AssLegFunction::P_14_9 (const double x) const private
Definition at line 6052 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_14_9_Deriv()
double AssLegFunction::P_14_9_Deriv (const double x) const private
Definition at line 6082 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_0()
double AssLegFunction::P_15_0 (const double x) const private
Definition at line 6341 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_15_0_Deriv()
double AssLegFunction::P_15_0_Deriv (const double x) const private
Definition at line 6372 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_15_1()
double AssLegFunction::P_15_1 (const double x) const private
Definition at line 6400 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_10()
double AssLegFunction::P_15_10 (const double x) const private
Definition at line 7117 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_10_Deriv()
double AssLegFunction::P_15_10_Deriv (const double x) const private
Definition at line 7145 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_11()
double AssLegFunction::P_15_11 (const double x) const private
Definition at line 7178 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_11_Deriv()
double AssLegFunction::P_15_11_Deriv (const double x) const private
Definition at line 7208 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_12()
double AssLegFunction::P_15_12 (const double x) const private
Definition at line 7242 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_12_Deriv()
double AssLegFunction::P_15_12_Deriv (const double x) const private
Definition at line 7263 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_13()
double AssLegFunction::P_15_13 (const double x) const private
Definition at line 7288 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_13_Deriv()
double AssLegFunction::P_15_13_Deriv (const double x) const private
Definition at line 7311 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_14()
double AssLegFunction::P_15_14 (const double x) const private
Definition at line 7335 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_14_Deriv()
double AssLegFunction::P_15_14_Deriv (const double x) const private
Definition at line 7353 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_15()
double AssLegFunction::P_15_15 (const double x) const private
Definition at line 7372 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_15_Deriv()
double AssLegFunction::P_15_15_Deriv (const double x) const private
Definition at line 7392 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_1_Deriv()
double AssLegFunction::P_15_1_Deriv (const double x) const private
Definition at line 6439 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_2()
double AssLegFunction::P_15_2 (const double x) const private
Definition at line 6495 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_2_Deriv()
double AssLegFunction::P_15_2_Deriv (const double x) const private
Definition at line 6531 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_3()
double AssLegFunction::P_15_3 (const double x) const private
Definition at line 6580 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_3_Deriv()
double AssLegFunction::P_15_3_Deriv (const double x) const private
Definition at line 6614 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_4()
double AssLegFunction::P_15_4 (const double x) const private
Definition at line 6662 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_4_Deriv()
double AssLegFunction::P_15_4_Deriv (const double x) const private
Definition at line 6697 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_5()
double AssLegFunction::P_15_5 (const double x) const private
Definition at line 6744 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_5_Deriv()
double AssLegFunction::P_15_5_Deriv (const double x) const private
Definition at line 6779 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_6()
double AssLegFunction::P_15_6 (const double x) const private
Definition at line 6825 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_6_Deriv()
double AssLegFunction::P_15_6_Deriv (const double x) const private
Definition at line 6859 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_7()
double AssLegFunction::P_15_7 (const double x) const private
Definition at line 6902 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_7_Deriv()
double AssLegFunction::P_15_7_Deriv (const double x) const private
Definition at line 6936 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_8()
double AssLegFunction::P_15_8 (const double x) const private
Definition at line 6980 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_8_Deriv()
double AssLegFunction::P_15_8_Deriv (const double x) const private
Definition at line 7011 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_9()
double AssLegFunction::P_15_9 (const double x) const private
Definition at line 7050 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_15_9_Deriv()
double AssLegFunction::P_15_9_Deriv (const double x) const private
Definition at line 7081 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_0()
double AssLegFunction::P_16_0 (const double x) const private
Definition at line 7410 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_16_0_Deriv()
double AssLegFunction::P_16_0_Deriv (const double x) const private
Definition at line 7440 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_16_1()
double AssLegFunction::P_16_1 (const double x) const private
Definition at line 7473 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_10()
double AssLegFunction::P_16_10 (const double x) const private
Definition at line 8235 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_10_Deriv()
double AssLegFunction::P_16_10_Deriv (const double x) const private
Definition at line 8264 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_11()
double AssLegFunction::P_16_11 (const double x) const private
Definition at line 8298 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_11_Deriv()
double AssLegFunction::P_16_11_Deriv (const double x) const private
Definition at line 8328 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_12()
double AssLegFunction::P_16_12 (const double x) const private
Definition at line 8363 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_12_Deriv()
double AssLegFunction::P_16_12_Deriv (const double x) const private
Definition at line 8391 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_13()
double AssLegFunction::P_16_13 (const double x) const private
Definition at line 8423 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_13_Deriv()
double AssLegFunction::P_16_13_Deriv (const double x) const private
Definition at line 8446 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_14()
double AssLegFunction::P_16_14 (const double x) const private
Definition at line 8473 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_14_Deriv()
double AssLegFunction::P_16_14_Deriv (const double x) const private
Definition at line 8494 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_15()
double AssLegFunction::P_16_15 (const double x) const private
Definition at line 8516 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_15_Deriv()
double AssLegFunction::P_16_15_Deriv (const double x) const private
Definition at line 8536 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_16()
double AssLegFunction::P_16_16 (const double x) const private
Definition at line 8557 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_16_16_Deriv()
double AssLegFunction::P_16_16_Deriv (const double x) const private
Definition at line 8575 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_1_Deriv()
double AssLegFunction::P_16_1_Deriv (const double x) const private
Definition at line 7516 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_2()
double AssLegFunction::P_16_2 (const double x) const private
Definition at line 7577 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_2_Deriv()
double AssLegFunction::P_16_2_Deriv (const double x) const private
Definition at line 7614 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_3()
double AssLegFunction::P_16_3 (const double x) const private
Definition at line 7666 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_3_Deriv()
double AssLegFunction::P_16_3_Deriv (const double x) const private
Definition at line 7704 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_4()
double AssLegFunction::P_16_4 (const double x) const private
Definition at line 7757 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_4_Deriv()
double AssLegFunction::P_16_4_Deriv (const double x) const private
Definition at line 7791 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_5()
double AssLegFunction::P_16_5 (const double x) const private
Definition at line 7839 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_5_Deriv()
double AssLegFunction::P_16_5_Deriv (const double x) const private
Definition at line 7876 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_6()
double AssLegFunction::P_16_6 (const double x) const private
Definition at line 7925 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_6_Deriv()
double AssLegFunction::P_16_6_Deriv (const double x) const private
Definition at line 7958 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_7()
double AssLegFunction::P_16_7 (const double x) const private
Definition at line 8002 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_7_Deriv()
double AssLegFunction::P_16_7_Deriv (const double x) const private
Definition at line 8038 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_8()
double AssLegFunction::P_16_8 (const double x) const private
Definition at line 8083 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_8_Deriv()
double AssLegFunction::P_16_8_Deriv (const double x) const private
Definition at line 8117 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_9()
double AssLegFunction::P_16_9 (const double x) const private
Definition at line 8161 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_16_9_Deriv()
double AssLegFunction::P_16_9_Deriv (const double x) const private
Definition at line 8194 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_0()
double AssLegFunction::P_17_0 (const double x) const private
Definition at line 8591 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_17_0_Deriv()
double AssLegFunction::P_17_0_Deriv (const double x) const private
Definition at line 8626 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_17_1()
double AssLegFunction::P_17_1 (const double x) const private
Definition at line 8659 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_10()
double AssLegFunction::P_17_10 (const double x) const private
Definition at line 9465 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_10_Deriv()
double AssLegFunction::P_17_10_Deriv (const double x) const private
Definition at line 9496 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_11()
double AssLegFunction::P_17_11 (const double x) const private
Definition at line 9535 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_11_Deriv()
double AssLegFunction::P_17_11_Deriv (const double x) const private
Definition at line 9566 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_12()
double AssLegFunction::P_17_12 (const double x) const private
Definition at line 9602 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_12_Deriv()
double AssLegFunction::P_17_12_Deriv (const double x) const private
Definition at line 9630 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_13()
double AssLegFunction::P_17_13 (const double x) const private
Definition at line 9663 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_13_Deriv()
double AssLegFunction::P_17_13_Deriv (const double x) const private
Definition at line 9693 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_14()
double AssLegFunction::P_17_14 (const double x) const private
Definition at line 9727 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_14_Deriv()
double AssLegFunction::P_17_14_Deriv (const double x) const private
Definition at line 9748 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_15()
double AssLegFunction::P_17_15 (const double x) const private
Definition at line 9773 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_15_Deriv()
double AssLegFunction::P_17_15_Deriv (const double x) const private
Definition at line 9796 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_16()
double AssLegFunction::P_17_16 (const double x) const private
Definition at line 9820 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_17_16_Deriv()
double AssLegFunction::P_17_16_Deriv (const double x) const private
Definition at line 9838 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_17()
double AssLegFunction::P_17_17 (const double x) const private
Definition at line 9859 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_17_Deriv()
double AssLegFunction::P_17_17_Deriv (const double x) const private
Definition at line 9881 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_1_Deriv()
double AssLegFunction::P_17_1_Deriv (const double x) const private
Definition at line 8703 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_2()
double AssLegFunction::P_17_2 (const double x) const private
Definition at line 8769 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_2_Deriv()
double AssLegFunction::P_17_2_Deriv (const double x) const private
Definition at line 8810 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_3()
double AssLegFunction::P_17_3 (const double x) const private
Definition at line 8867 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_3_Deriv()
double AssLegFunction::P_17_3_Deriv (const double x) const private
Definition at line 8906 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_4()
double AssLegFunction::P_17_4 (const double x) const private
Definition at line 8962 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_4_Deriv()
double AssLegFunction::P_17_4_Deriv (const double x) const private
Definition at line 9000 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_5()
double AssLegFunction::P_17_5 (const double x) const private
Definition at line 9053 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_5_Deriv()
double AssLegFunction::P_17_5_Deriv (const double x) const private
Definition at line 9089 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_6()
double AssLegFunction::P_17_6 (const double x) const private
Definition at line 9139 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_6_Deriv()
double AssLegFunction::P_17_6_Deriv (const double x) const private
Definition at line 9174 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_7()
double AssLegFunction::P_17_7 (const double x) const private
Definition at line 9221 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_7_Deriv()
double AssLegFunction::P_17_7_Deriv (const double x) const private
Definition at line 9256 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_8()
double AssLegFunction::P_17_8 (const double x) const private
Definition at line 9302 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_8_Deriv()
double AssLegFunction::P_17_8_Deriv (const double x) const private
Definition at line 9338 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_9()
double AssLegFunction::P_17_9 (const double x) const private
Definition at line 9383 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_17_9_Deriv()
double AssLegFunction::P_17_9_Deriv (const double x) const private
Definition at line 9419 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_0()
double AssLegFunction::P_18_0 (const double x) const private
Definition at line 9899 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_18_0_Deriv()
double AssLegFunction::P_18_0_Deriv (const double x) const private
Definition at line 9931 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_18_1()
double AssLegFunction::P_18_1 (const double x) const private
Definition at line 9970 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_10()
double AssLegFunction::P_18_10 (const double x) const private
Definition at line 10817 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_10_Deriv()
double AssLegFunction::P_18_10_Deriv (const double x) const private
Definition at line 10851 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_11()
double AssLegFunction::P_18_11 (const double x) const private
Definition at line 10895 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_11_Deriv()
double AssLegFunction::P_18_11_Deriv (const double x) const private
Definition at line 10928 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_12()
double AssLegFunction::P_18_12 (const double x) const private
Definition at line 10969 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_12_Deriv()
double AssLegFunction::P_18_12_Deriv (const double x) const private
Definition at line 10998 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_13()
double AssLegFunction::P_18_13 (const double x) const private
Definition at line 11032 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_13_Deriv()
double AssLegFunction::P_18_13_Deriv (const double x) const private
Definition at line 11062 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_14()
double AssLegFunction::P_18_14 (const double x) const private
Definition at line 11097 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_14_Deriv()
double AssLegFunction::P_18_14_Deriv (const double x) const private
Definition at line 11125 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_15()
double AssLegFunction::P_18_15 (const double x) const private
Definition at line 11157 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_15_Deriv()
double AssLegFunction::P_18_15_Deriv (const double x) const private
Definition at line 11180 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_16()
double AssLegFunction::P_18_16 (const double x) const private
Definition at line 11207 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_18_16_Deriv()
double AssLegFunction::P_18_16_Deriv (const double x) const private
Definition at line 11228 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_17()
double AssLegFunction::P_18_17 (const double x) const private
Definition at line 11252 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_17_Deriv()
double AssLegFunction::P_18_17_Deriv (const double x) const private
Definition at line 11274 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_18()
double AssLegFunction::P_18_18 (const double x) const private
Definition at line 11297 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_18_Deriv()
double AssLegFunction::P_18_18_Deriv (const double x) const private
Definition at line 11317 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_18_1_Deriv()
double AssLegFunction::P_18_1_Deriv (const double x) const private
Definition at line 10018 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_2()
double AssLegFunction::P_18_2 (const double x) const private
Definition at line 10085 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_2_Deriv()
double AssLegFunction::P_18_2_Deriv (const double x) const private
Definition at line 10127 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_3()
double AssLegFunction::P_18_3 (const double x) const private
Definition at line 10189 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_3_Deriv()
double AssLegFunction::P_18_3_Deriv (const double x) const private
Definition at line 10232 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_4()
double AssLegFunction::P_18_4 (const double x) const private
Definition at line 10293 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_4_Deriv()
double AssLegFunction::P_18_4_Deriv (const double x) const private
Definition at line 10332 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_5()
double AssLegFunction::P_18_5 (const double x) const private
Definition at line 10388 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_5_Deriv()
double AssLegFunction::P_18_5_Deriv (const double x) const private
Definition at line 10428 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_6()
double AssLegFunction::P_18_6 (const double x) const private
Definition at line 10483 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_6_Deriv()
double AssLegFunction::P_18_6_Deriv (const double x) const private
Definition at line 10517 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_7()
double AssLegFunction::P_18_7 (const double x) const private
Definition at line 10565 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_7_Deriv()
double AssLegFunction::P_18_7_Deriv (const double x) const private
Definition at line 10602 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_8()
double AssLegFunction::P_18_8 (const double x) const private
Definition at line 10651 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_8_Deriv()
double AssLegFunction::P_18_8_Deriv (const double x) const private
Definition at line 10686 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_9()
double AssLegFunction::P_18_9 (const double x) const private
Definition at line 10732 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_18_9_Deriv()
double AssLegFunction::P_18_9_Deriv (const double x) const private
Definition at line 10770 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_0()
double AssLegFunction::P_19_0 (const double x) const private
Definition at line 11333 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_19_0_Deriv()
double AssLegFunction::P_19_0_Deriv (const double x) const private
Definition at line 11370 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_19_1()
double AssLegFunction::P_19_1 (const double x) const private
Definition at line 11405 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_10()
double AssLegFunction::P_19_10 (const double x) const private
Definition at line 12288 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_10_Deriv()
double AssLegFunction::P_19_10_Deriv (const double x) const private
Definition at line 12324 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_11()
double AssLegFunction::P_19_11 (const double x) const private
Definition at line 12369 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_11_Deriv()
double AssLegFunction::P_19_11_Deriv (const double x) const private
Definition at line 12405 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_12()
double AssLegFunction::P_19_12 (const double x) const private
Definition at line 12451 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_12_Deriv()
double AssLegFunction::P_19_12_Deriv (const double x) const private
Definition at line 12482 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_13()
double AssLegFunction::P_19_13 (const double x) const private
Definition at line 12521 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_13_Deriv()
double AssLegFunction::P_19_13_Deriv (const double x) const private
Definition at line 12552 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_14()
double AssLegFunction::P_19_14 (const double x) const private
Definition at line 12588 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_14_Deriv()
double AssLegFunction::P_19_14_Deriv (const double x) const private
Definition at line 12616 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_15()
double AssLegFunction::P_19_15 (const double x) const private
Definition at line 12649 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_15_Deriv()
double AssLegFunction::P_19_15_Deriv (const double x) const private
Definition at line 12679 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_16()
double AssLegFunction::P_19_16 (const double x) const private
Definition at line 12713 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_16_Deriv()
double AssLegFunction::P_19_16_Deriv (const double x) const private
Definition at line 12736 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_17()
double AssLegFunction::P_19_17 (const double x) const private
Definition at line 12763 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_17_Deriv()
double AssLegFunction::P_19_17_Deriv (const double x) const private
Definition at line 12788 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_18()
double AssLegFunction::P_19_18 (const double x) const private
Definition at line 12814 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_18_Deriv()
double AssLegFunction::P_19_18_Deriv (const double x) const private
Definition at line 12834 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_19()
double AssLegFunction::P_19_19 (const double x) const private
Definition at line 12855 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_19_Deriv()
double AssLegFunction::P_19_19_Deriv (const double x) const private
Definition at line 12877 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_1_Deriv()
double AssLegFunction::P_19_1_Deriv (const double x) const private
Definition at line 11450 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_2()
double AssLegFunction::P_19_2 (const double x) const private
Definition at line 11518 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_2_Deriv()
double AssLegFunction::P_19_2_Deriv (const double x) const private
Definition at line 11564 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_3()
double AssLegFunction::P_19_3 (const double x) const private
Definition at line 11627 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_3_Deriv()
double AssLegFunction::P_19_3_Deriv (const double x) const private
Definition at line 11671 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_4()
double AssLegFunction::P_19_4 (const double x) const private
Definition at line 11737 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_4_Deriv()
double AssLegFunction::P_19_4_Deriv (const double x) const private
Definition at line 11780 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_5()
double AssLegFunction::P_19_5 (const double x) const private
Definition at line 11841 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_5_Deriv()
double AssLegFunction::P_19_5_Deriv (const double x) const private
Definition at line 11882 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_6()
double AssLegFunction::P_19_6 (const double x) const private
Definition at line 11940 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_6_Deriv()
double AssLegFunction::P_19_6_Deriv (const double x) const private
Definition at line 11978 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_7()
double AssLegFunction::P_19_7 (const double x) const private
Definition at line 12031 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_7_Deriv()
double AssLegFunction::P_19_7_Deriv (const double x) const private
Definition at line 12067 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_8()
double AssLegFunction::P_19_8 (const double x) const private
Definition at line 12117 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_8_Deriv()
double AssLegFunction::P_19_8_Deriv (const double x) const private
Definition at line 12154 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_9()
double AssLegFunction::P_19_9 (const double x) const private
Definition at line 12203 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_19_9_Deriv()
double AssLegFunction::P_19_9_Deriv (const double x) const private
Definition at line 12240 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_1_0()
double AssLegFunction::P_1_0 (const double x) const private
Definition at line 551 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_1_0_Deriv()
double AssLegFunction::P_1_0_Deriv (const double x) const private
Definition at line 557 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_1_1()
double AssLegFunction::P_1_1 (const double x) const private
Definition at line 563 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_1_1_Deriv()
double AssLegFunction::P_1_1_Deriv (const double x) const private
Definition at line 577 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_0()
double AssLegFunction::P_20_0 (const double x) const private
Definition at line 12897 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_20_0_Deriv()
double AssLegFunction::P_20_0_Deriv (const double x) const private
Definition at line 12931 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_20_1()
double AssLegFunction::P_20_1 (const double x) const private
Definition at line 12970 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_10()
double AssLegFunction::P_20_10 (const double x) const private
Definition at line 13896 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_10_Deriv()
double AssLegFunction::P_20_10_Deriv (const double x) const private
Definition at line 13931 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_11()
double AssLegFunction::P_20_11 (const double x) const private
Definition at line 13977 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_11_Deriv()
double AssLegFunction::P_20_11_Deriv (const double x) const private
Definition at line 14015 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_12()
double AssLegFunction::P_20_12 (const double x) const private
Definition at line 14062 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_12_Deriv()
double AssLegFunction::P_20_12_Deriv (const double x) const private
Definition at line 14096 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_13()
double AssLegFunction::P_20_13 (const double x) const private
Definition at line 14140 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_13_Deriv()
double AssLegFunction::P_20_13_Deriv (const double x) const private
Definition at line 14173 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_14()
double AssLegFunction::P_20_14 (const double x) const private
Definition at line 14214 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_14_Deriv()
double AssLegFunction::P_20_14_Deriv (const double x) const private
Definition at line 14243 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_15()
double AssLegFunction::P_20_15 (const double x) const private
Definition at line 14278 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_15_Deriv()
double AssLegFunction::P_20_15_Deriv (const double x) const private
Definition at line 14308 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_16()
double AssLegFunction::P_20_16 (const double x) const private
Definition at line 14344 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_16_Deriv()
double AssLegFunction::P_20_16_Deriv (const double x) const private
Definition at line 14374 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_17()
double AssLegFunction::P_20_17 (const double x) const private
Definition at line 14408 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_17_Deriv()
double AssLegFunction::P_20_17_Deriv (const double x) const private
Definition at line 14433 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_18()
double AssLegFunction::P_20_18 (const double x) const private
Definition at line 14462 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_18_Deriv()
double AssLegFunction::P_20_18_Deriv (const double x) const private
Definition at line 14485 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_19()
double AssLegFunction::P_20_19 (const double x) const private
Definition at line 14509 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_19_Deriv()
double AssLegFunction::P_20_19_Deriv (const double x) const private
Definition at line 14531 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_1_Deriv()
double AssLegFunction::P_20_1_Deriv (const double x) const private
Definition at line 13019 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_2()
double AssLegFunction::P_20_2 (const double x) const private
Definition at line 13090 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_20()
double AssLegFunction::P_20_20 (const double x) const private
Definition at line 14554 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_20_20_Deriv()
double AssLegFunction::P_20_20_Deriv (const double x) const private
Definition at line 14572 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_2_Deriv()
double AssLegFunction::P_20_2_Deriv (const double x) const private
Definition at line 13133 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_3()
double AssLegFunction::P_20_3 (const double x) const private
Definition at line 13197 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_3_Deriv()
double AssLegFunction::P_20_3_Deriv (const double x) const private
Definition at line 13245 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_4()
double AssLegFunction::P_20_4 (const double x) const private
Definition at line 13312 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_4_Deriv()
double AssLegFunction::P_20_4_Deriv (const double x) const private
Definition at line 13356 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_5()
double AssLegFunction::P_20_5 (const double x) const private
Definition at line 13422 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_5_Deriv()
double AssLegFunction::P_20_5_Deriv (const double x) const private
Definition at line 13467 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_6()
double AssLegFunction::P_20_6 (const double x) const private
Definition at line 13530 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_6_Deriv()
double AssLegFunction::P_20_6_Deriv (const double x) const private
Definition at line 13569 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_7()
double AssLegFunction::P_20_7 (const double x) const private
Definition at line 13625 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_7_Deriv()
double AssLegFunction::P_20_7_Deriv (const double x) const private
Definition at line 13665 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_8()
double AssLegFunction::P_20_8 (const double x) const private
Definition at line 13720 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_8_Deriv()
double AssLegFunction::P_20_8_Deriv (const double x) const private
Definition at line 13756 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_9()
double AssLegFunction::P_20_9 (const double x) const private
Definition at line 13806 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_20_9_Deriv()
double AssLegFunction::P_20_9_Deriv (const double x) const private
Definition at line 13845 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_2_0()
double AssLegFunction::P_2_0 (const double x) const private
Definition at line 589 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_2_0_Deriv()
double AssLegFunction::P_2_0_Deriv (const double x) const private
Definition at line 597 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_2_1()
double AssLegFunction::P_2_1 (const double x) const private
Definition at line 605 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_2_1_Deriv()
double AssLegFunction::P_2_1_Deriv (const double x) const private
Definition at line 619 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_2_2()
double AssLegFunction::P_2_2 (const double x) const private
Definition at line 633 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_2_2_Deriv()
double AssLegFunction::P_2_2_Deriv (const double x) const private
Definition at line 645 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_3_0()
double AssLegFunction::P_3_0 (const double x) const private
Definition at line 653 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_3_0_Deriv()
double AssLegFunction::P_3_0_Deriv (const double x) const private
Definition at line 661 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_3_1()
double AssLegFunction::P_3_1 (const double x) const private
Definition at line 671 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_3_1_Deriv()
double AssLegFunction::P_3_1_Deriv (const double x) const private
Definition at line 685 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_3_2()
double AssLegFunction::P_3_2 (const double x) const private
Definition at line 700 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_3_2_Deriv()
double AssLegFunction::P_3_2_Deriv (const double x) const private
Definition at line 712 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_3_3()
double AssLegFunction::P_3_3 (const double x) const private
Definition at line 724 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_3_3_Deriv()
double AssLegFunction::P_3_3_Deriv (const double x) const private
Definition at line 740 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_4_0()
double AssLegFunction::P_4_0 (const double x) const private
Definition at line 752 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_4_0_Deriv()
double AssLegFunction::P_4_0_Deriv (const double x) const private
Definition at line 766 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_4_1()
double AssLegFunction::P_4_1 (const double x) const private
Definition at line 776 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_4_1_Deriv()
double AssLegFunction::P_4_1_Deriv (const double x) const private
Definition at line 792 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_4_2()
double AssLegFunction::P_4_2 (const double x) const private
Definition at line 809 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_4_2_Deriv()
double AssLegFunction::P_4_2_Deriv (const double x) const private
Definition at line 821 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_4_3()
double AssLegFunction::P_4_3 (const double x) const private
Definition at line 834 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_4_3_Deriv()
double AssLegFunction::P_4_3_Deriv (const double x) const private
Definition at line 850 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_4_4()
double AssLegFunction::P_4_4 (const double x) const private
Definition at line 866 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_4_4_Deriv()
double AssLegFunction::P_4_4_Deriv (const double x) const private
Definition at line 880 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_5_0()
double AssLegFunction::P_5_0 (const double x) const private
Definition at line 890 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_5_0_Deriv()
double AssLegFunction::P_5_0_Deriv (const double x) const private
Definition at line 904 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_5_1()
double AssLegFunction::P_5_1 (const double x) const private
Definition at line 920 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_5_1_Deriv()
double AssLegFunction::P_5_1_Deriv (const double x) const private
Definition at line 943 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_5_2()
double AssLegFunction::P_5_2 (const double x) const private
Definition at line 967 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_5_2_Deriv()
double AssLegFunction::P_5_2_Deriv (const double x) const private
Definition at line 981 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_5_3()
double AssLegFunction::P_5_3 (const double x) const private
Definition at line 996 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_5_3_Deriv()
double AssLegFunction::P_5_3_Deriv (const double x) const private
Definition at line 1012 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_5_4()
double AssLegFunction::P_5_4 (const double x) const private
Definition at line 1029 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_5_4_Deriv()
double AssLegFunction::P_5_4_Deriv (const double x) const private
Definition at line 1043 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_5_5()
double AssLegFunction::P_5_5 (const double x) const private
Definition at line 1059 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_5_5_Deriv()
double AssLegFunction::P_5_5_Deriv (const double x) const private
Definition at line 1077 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_6_0()
double AssLegFunction::P_6_0 (const double x) const private
Definition at line 1091 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_6_0_Deriv()
double AssLegFunction::P_6_0_Deriv (const double x) const private
Definition at line 1106 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_6_1()
double AssLegFunction::P_6_1 (const double x) const private
Definition at line 1123 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_6_1_Deriv()
double AssLegFunction::P_6_1_Deriv (const double x) const private
Definition at line 1148 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_6_2()
double AssLegFunction::P_6_2 (const double x) const private
Definition at line 1176 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_6_2_Deriv()
double AssLegFunction::P_6_2_Deriv (const double x) const private
Definition at line 1198 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_6_3()
double AssLegFunction::P_6_3 (const double x) const private
Definition at line 1219 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_6_3_Deriv()
double AssLegFunction::P_6_3_Deriv (const double x) const private
Definition at line 1236 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_6_4()
double AssLegFunction::P_6_4 (const double x) const private
Definition at line 1254 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_6_4_Deriv()
double AssLegFunction::P_6_4_Deriv (const double x) const private
Definition at line 1268 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_6_5()
double AssLegFunction::P_6_5 (const double x) const private
Definition at line 1285 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_6_5_Deriv()
double AssLegFunction::P_6_5_Deriv (const double x) const private
Definition at line 1303 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_6_6()
double AssLegFunction::P_6_6 (const double x) const private
Definition at line 1321 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_6_6_Deriv()
double AssLegFunction::P_6_6_Deriv (const double x) const private
Definition at line 1337 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_7_0()
double AssLegFunction::P_7_0 (const double x) const private
Definition at line 1349 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_7_0_Deriv()
double AssLegFunction::P_7_0_Deriv (const double x) const private
Definition at line 1366 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_7_1()
double AssLegFunction::P_7_1 (const double x) const private
Definition at line 1383 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_7_1_Deriv()
double AssLegFunction::P_7_1_Deriv (const double x) const private
Definition at line 1408 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_7_2()
double AssLegFunction::P_7_2 (const double x) const private
Definition at line 1437 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_7_2_Deriv()
double AssLegFunction::P_7_2_Deriv (const double x) const private
Definition at line 1460 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_7_3()
double AssLegFunction::P_7_3 (const double x) const private
Definition at line 1485 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_7_3_Deriv()
double AssLegFunction::P_7_3_Deriv (const double x) const private
Definition at line 1510 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_7_4()
double AssLegFunction::P_7_4 (const double x) const private
Definition at line 1537 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_7_4_Deriv()
double AssLegFunction::P_7_4_Deriv (const double x) const private
Definition at line 1554 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_7_5()
double AssLegFunction::P_7_5 (const double x) const private
Definition at line 1573 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_7_5_Deriv()
double AssLegFunction::P_7_5_Deriv (const double x) const private
Definition at line 1592 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_7_6()
double AssLegFunction::P_7_6 (const double x) const private
Definition at line 1612 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_7_6_Deriv()
double AssLegFunction::P_7_6_Deriv (const double x) const private
Definition at line 1628 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_7_7()
double AssLegFunction::P_7_7 (const double x) const private
Definition at line 1644 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_7_7_Deriv()
double AssLegFunction::P_7_7_Deriv (const double x) const private
Definition at line 1662 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_8_0()
double AssLegFunction::P_8_0 (const double x) const private
Definition at line 1678 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_8_0_Deriv()
double AssLegFunction::P_8_0_Deriv (const double x) const private
Definition at line 1697 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_8_1()
double AssLegFunction::P_8_1 (const double x) const private
Definition at line 1716 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_8_1_Deriv()
double AssLegFunction::P_8_1_Deriv (const double x) const private
Definition at line 1743 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_8_2()
double AssLegFunction::P_8_2 (const double x) const private
Definition at line 1776 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_8_2_Deriv()
double AssLegFunction::P_8_2_Deriv (const double x) const private
Definition at line 1799 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_8_3()
double AssLegFunction::P_8_3 (const double x) const private
Definition at line 1824 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_8_3_Deriv()
double AssLegFunction::P_8_3_Deriv (const double x) const private
Definition at line 1849 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_8_4()
double AssLegFunction::P_8_4 (const double x) const private
Definition at line 1878 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_8_4_Deriv()
double AssLegFunction::P_8_4_Deriv (const double x) const private
Definition at line 1903 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_8_5()
double AssLegFunction::P_8_5 (const double x) const private
Definition at line 1931 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_8_5_Deriv()
double AssLegFunction::P_8_5_Deriv (const double x) const private
Definition at line 1951 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_8_6()
double AssLegFunction::P_8_6 (const double x) const private
Definition at line 1973 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_8_6_Deriv()
double AssLegFunction::P_8_6_Deriv (const double x) const private
Definition at line 1990 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_8_7()
double AssLegFunction::P_8_7 (const double x) const private
Definition at line 2008 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_8_7_Deriv()
double AssLegFunction::P_8_7_Deriv (const double x) const private
Definition at line 2026 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_8_8()
double AssLegFunction::P_8_8 (const double x) const private
Definition at line 2045 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_8_8_Deriv()
double AssLegFunction::P_8_8_Deriv (const double x) const private
Definition at line 2061 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_0()
double AssLegFunction::P_9_0 (const double x) const private
Definition at line 2075 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_9_0_Deriv()
double AssLegFunction::P_9_0_Deriv (const double x) const private
Definition at line 2096 of file ass_leg_function.cc.
Referenced by AssLegFunction().
P_9_1()
double AssLegFunction::P_9_1 (const double x) const private
Definition at line 2117 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_1_Deriv()
double AssLegFunction::P_9_1_Deriv (const double x) const private
Definition at line 2147 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_2()
double AssLegFunction::P_9_2 (const double x) const private
Definition at line 2185 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_2_Deriv()
double AssLegFunction::P_9_2_Deriv (const double x) const private
Definition at line 2210 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_3()
double AssLegFunction::P_9_3 (const double x) const private
Definition at line 2239 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_3_Deriv()
double AssLegFunction::P_9_3_Deriv (const double x) const private
Definition at line 2264 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_4()
double AssLegFunction::P_9_4 (const double x) const private
Definition at line 2293 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_4_Deriv()
double AssLegFunction::P_9_4_Deriv (const double x) const private
Definition at line 2318 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_5()
double AssLegFunction::P_9_5 (const double x) const private
Definition at line 2347 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_5_Deriv()
double AssLegFunction::P_9_5_Deriv (const double x) const private
Definition at line 2374 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_6()
double AssLegFunction::P_9_6 (const double x) const private
Definition at line 2404 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_6_Deriv()
double AssLegFunction::P_9_6_Deriv (const double x) const private
Definition at line 2422 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_7()
double AssLegFunction::P_9_7 (const double x) const private
Definition at line 2442 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_7_Deriv()
double AssLegFunction::P_9_7_Deriv (const double x) const private
Definition at line 2462 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_8()
double AssLegFunction::P_9_8 (const double x) const private
Definition at line 2482 of file ass_leg_function.cc.
References pow(), and sqrt().
Referenced by AssLegFunction().
P_9_8_Deriv()
double AssLegFunction::P_9_8_Deriv (const double x) const private
Definition at line 2498 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_9()
double AssLegFunction::P_9_9 (const double x) const private
Definition at line 2516 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
P_9_9_Deriv()
double AssLegFunction::P_9_9_Deriv (const double x) const private
Definition at line 2536 of file ass_leg_function.cc.
References sqrt().
Referenced by AssLegFunction().
Member Data Documentation
leg_der_pointers
std::vector<std::vector<double (AssLegFunction::*)(const double) const> > AssLegFunction::leg_der_pointers private
Definition at line 81 of file ass_leg_function.h.
Referenced by AssLegFunction(), AssLegFunSphDeriv(), and GetAssLegFunSphDeriv().
leg_pointers
std::vector<std::vector<double (AssLegFunction::*)(const double) const> > AssLegFunction::leg_pointers private
Definition at line 79 of file ass_leg_function.h.
Referenced by AssLegFunction(), AssLegFunSph(), AssLegFunSphDeriv(), and GetAssLegFunSph().
The documentation for this class was generated from the following files:
ass_leg_function.h
ass_leg_function.cc