pi-BEM: Parallel BEM Solver: LaplaceKernel Namespace Reference
LaplaceKernel Namespace Reference
Functions
template<int dim>
double single_layer (const Point< dim > &R)
template<int dim>
Point< dim > double_layer (const Point< dim > &R)
template<int dim>
Tensor< 2, dim > hypersingular (const Point< dim > &R)
template<int dim>
void kernels (const Tensor< 1, dim > &R, Tensor< 1, dim > &D, double &d)
template<int dim>
void kernels (const Tensor< 1, dim > &R, Tensor< 2, dim > &H, Tensor< 1, dim > &D, double &d)
Function Documentation
double_layer()
template<int dim> Point< dim > LaplaceKernel::double_layer (const Point< dim > & R)
Definition at line 39 of file laplace_kernel.h.
References Assert, Point< int dim, typename Number >::norm(), numbers::PI, and Point< int dim, typename Number >::square().
hypersingular()
template<int dim> Tensor< 2, dim > LaplaceKernel::hypersingular (const Point< dim > & R)
Definition at line 56 of file laplace_kernel.h.
References Assert, and numbers::PI.
kernels() [1/2]
template<int dim> void LaplaceKernel::kernels (const Tensor< 1, dim > & R, Tensor< 1, dim > & D, double & d)
Definition at line 93 of file laplace_kernel.h.
References Assert, d(), std::log(), Tensor< int rank_, int dim, typename Number >::norm(), and numbers::PI.
Referenced by BEMProblem< dim >::assemble_system(), BEMProblem< dim >::compute_gradients_hypersingular(), and BEMFMA< dim >::direct_integrals().
kernels() [2/2]
template<int dim> void LaplaceKernel::kernels (const Tensor< 1, dim > & R, Tensor< 2, dim > & H, Tensor< 1, dim > & D, double & d)
Definition at line 114 of file laplace_kernel.h.
References Assert, d(), std::log(), Tensor< int rank_, int dim, typename Number >::norm(), and numbers::PI.
single_layer()
template<int dim> double LaplaceKernel::single_layer (const Point< dim > & R)
Definition at line 19 of file laplace_kernel.h.
References Assert, std::log(), Point< int dim, typename Number >::norm(), and numbers::PI.