var topics =
[
    [ "Automatic and symbolic differentiation", "http://www.dealii.org/developer/doxygen/deal.II/group__auto__symb__diff.html", null ],
    [ "deal.II and Modern C++ standards", "http://www.dealii.org/developer/doxygen/deal.II/group__CPP11.html", "group__CPP11" ],
    [ "Concepts, or expectations on template parameters", "http://www.dealii.org/developer/doxygen/deal.II/group__Concepts.html", null ],
    [ "Degrees of Freedom", "http://www.dealii.org/developer/doxygen/deal.II/group__dofs.html", "group__dofs" ],
    [ "Exceptions and assertions", "http://www.dealii.org/developer/doxygen/deal.II/group__Exceptions.html", "group__Exceptions" ],
    [ "Finite elements", "http://www.dealii.org/developer/doxygen/deal.II/group__feall.html", "group__feall" ],
    [ "Functions", "http://www.dealii.org/developer/doxygen/deal.II/group__functions.html", null ],
    [ "The geodynamics demonstration suite", "http://www.dealii.org/developer/doxygen/deal.II/group__geodynamics.html", null ],
    [ "Geometric and other primitives", "http://www.dealii.org/developer/doxygen/deal.II/group__geomprimitives.html", null ],
    [ "Grids and Triangulations", "http://www.dealii.org/developer/doxygen/deal.II/group__grid.html", "group__grid" ],
    [ "hp-finite element support", "http://www.dealii.org/developer/doxygen/deal.II/group__hp.html", "group__hp" ],
    [ "Integrators", "http://www.dealii.org/developer/doxygen/deal.II/group__Integrators.html", "group__Integrators" ],
    [ "Input/Output", "http://www.dealii.org/developer/doxygen/deal.II/group__IO.html", "group__IO" ],
    [ "Linear algebra classes", "http://www.dealii.org/developer/doxygen/deal.II/group__LAC.html", "group__LAC" ],
    [ "Matrix-free infrastructure", "http://www.dealii.org/developer/doxygen/deal.II/group__matrixfree.html", "group__matrixfree" ],
    [ "The MeshWorker interface", "http://www.dealii.org/developer/doxygen/deal.II/group__MeshWorker.html", "group__MeshWorker" ],
    [ "Multilevel support", "http://www.dealii.org/developer/doxygen/deal.II/group__mg.html", "group__mg" ],
    [ "Numerical algorithms", "http://www.dealii.org/developer/doxygen/deal.II/group__numerics.html", null ],
    [ "Parallel computing", "http://www.dealii.org/developer/doxygen/deal.II/group__Parallel.html", "group__Parallel" ],
    [ "PETScWrappers", "http://www.dealii.org/developer/doxygen/deal.II/group__PETScWrappers.html", "group__PETScWrappers" ],
    [ "Physics", "http://www.dealii.org/developer/doxygen/deal.II/group__physics.html", null ],
    [ "Polynomials and polynomial spaces", "http://www.dealii.org/developer/doxygen/deal.II/group__Polynomials.html", null ],
    [ "Quadrature formulas", "http://www.dealii.org/developer/doxygen/deal.II/group__Quadrature.html", null ],
    [ "Simplex support", "http://www.dealii.org/developer/doxygen/deal.II/group__simplex.html", null ],
    [ "SLEPcWrappers", "http://www.dealii.org/developer/doxygen/deal.II/group__SLEPcWrappers.html", null ],
    [ "TrilinosWrappers", "http://www.dealii.org/developer/doxygen/deal.II/group__TrilinosWrappers.html", "group__TrilinosWrappers" ],
    [ "Utility functions and classes", "http://www.dealii.org/developer/doxygen/deal.II/group__utilities.html", "group__utilities" ],
    [ "TpetraWrappers", "http://www.dealii.org/developer/doxygen/deal.II/group__TpetraWrappers.html", null ],
    [ "OpenCASCADE", "http://www.dealii.org/developer/doxygen/deal.II/group__OpenCASCADE.html", null ]
];