var searchData=
[
  ['q1wedgefunction_0',['Q1WedgeFunction',['http://www.dealii.org/developer/doxygen/deal.II/classFunctions_1_1Q1WedgeFunction.html',1,'Functions']]],
  ['qanisotropic_1',['QAnisotropic',['http://www.dealii.org/developer/doxygen/deal.II/classQAnisotropic.html',1,'']]],
  ['qcollection_2',['QCollection',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'hp']]],
  ['qcollection_3c_201_20_3e_3',['QCollection&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'']]],
  ['qcollection_3c_20dim_20_2d_201_20_3e_4',['QCollection&lt; dim - 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'']]],
  ['qcollection_3c_20q_5fdim_20_3e_5',['QCollection&lt; q_dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'']]],
  ['qcollection_3c_20structdim_20_3e_6',['QCollection&lt; structdim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'']]],
  ['qduffy_7',['QDuffy',['http://www.dealii.org/developer/doxygen/deal.II/classQDuffy.html',1,'']]],
  ['qgauss_8',['QGauss',['http://www.dealii.org/developer/doxygen/deal.II/classQGauss.html',1,'']]],
  ['qgausschebyshev_9',['QGaussChebyshev',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussChebyshev.html',1,'']]],
  ['qgausslobatto_10',['QGaussLobatto',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLobatto.html',1,'']]],
  ['qgausslobatto_3c_201_20_3e_11',['QGaussLobatto&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLobatto.html',1,'']]],
  ['qgausslobattochebyshev_12',['QGaussLobattoChebyshev',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLobattoChebyshev.html',1,'']]],
  ['qgausslog_13',['QGaussLog',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLog.html',1,'']]],
  ['qgausslogr_14',['QGaussLogR',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLogR.html',1,'']]],
  ['qgaussoneoverr_15',['QGaussOneOverR',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussOneOverR.html',1,'']]],
  ['qgausspyramid_16',['QGaussPyramid',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussPyramid.html',1,'']]],
  ['qgaussradauchebyshev_17',['QGaussRadauChebyshev',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussRadauChebyshev.html',1,'']]],
  ['qgausssimplex_18',['QGaussSimplex',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussSimplex.html',1,'']]],
  ['qgausswedge_19',['QGaussWedge',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussWedge.html',1,'']]],
  ['qgenerator_20',['QGenerator',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGenerator.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qgenerator_3c_201_2c_20spacedim_20_3e_21',['QGenerator&lt; 1, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGenerator_3_011_00_01spacedim_01_4.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qgenerator_3c_20dim_2c_20dim_20_3e_22',['QGenerator&lt; dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGenerator.html',1,'']]],
  ['qgeneratorbase_23',['QGeneratorBase',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGeneratorBase.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qgeneratorbase_3c_201_2c_20spacedim_20_3e_24',['QGeneratorBase&lt; 1, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGeneratorBase.html',1,'']]],
  ['qiterated_25',['QIterated',['http://www.dealii.org/developer/doxygen/deal.II/classQIterated.html',1,'']]],
  ['qiteratedsimplex_26',['QIteratedSimplex',['http://www.dealii.org/developer/doxygen/deal.II/classQIteratedSimplex.html',1,'']]],
  ['qmidpoint_27',['QMidpoint',['http://www.dealii.org/developer/doxygen/deal.II/classQMidpoint.html',1,'']]],
  ['qmilne_28',['QMilne',['http://www.dealii.org/developer/doxygen/deal.II/classQMilne.html',1,'']]],
  ['qpartitioning_29',['QPartitioning',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QPartitioning.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qprojector_30',['QProjector',['http://www.dealii.org/developer/doxygen/deal.II/classQProjector.html',1,'']]],
  ['qr_31',['QR',['http://www.dealii.org/developer/doxygen/deal.II/classQR.html',1,'']]],
  ['qsimplex_32',['QSimplex',['http://www.dealii.org/developer/doxygen/deal.II/classQSimplex.html',1,'']]],
  ['qsimplex_3c_202_20_3e_33',['QSimplex&lt; 2 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQSimplex.html',1,'']]],
  ['qsimpson_34',['QSimpson',['http://www.dealii.org/developer/doxygen/deal.II/classQSimpson.html',1,'']]],
  ['qsorted_35',['QSorted',['http://www.dealii.org/developer/doxygen/deal.II/classQSorted.html',1,'']]],
  ['qsplit_36',['QSplit',['http://www.dealii.org/developer/doxygen/deal.II/classQSplit.html',1,'']]],
  ['qtelles_37',['QTelles',['http://www.dealii.org/developer/doxygen/deal.II/classQTelles.html',1,'']]],
  ['qtrapezoid_38',['QTrapezoid',['http://www.dealii.org/developer/doxygen/deal.II/classQTrapezoid.html',1,'']]],
  ['qtrianglepolar_39',['QTrianglePolar',['http://www.dealii.org/developer/doxygen/deal.II/classQTrianglePolar.html',1,'']]],
  ['quadrature_40',['Quadrature',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadrature_3c_200_20_3e_41',['Quadrature&lt; 0 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadrature_3c_201_20_3e_42',['Quadrature&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadrature_3c_20dim_20_2d_201_20_3e_43',['Quadrature&lt; dim - 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadrature_3c_20structdim_20_3e_44',['Quadrature&lt; structdim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadraturedescriptor_45',['QuadratureDescriptor',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MatrixFreeFunctions_1_1MappingInfoStorage_1_1QuadratureDescriptor.html',1,'internal::MatrixFreeFunctions::MappingInfoStorage']]],
  ['quadraturegenerator_46',['QuadratureGenerator',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1QuadratureGenerator.html',1,'NonMatching']]],
  ['quadraturegenerator_3c_20dim_20_2d_201_20_3e_47',['QuadratureGenerator&lt; dim - 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1QuadratureGenerator.html',1,'']]],
  ['quadratureselector_48',['QuadratureSelector',['http://www.dealii.org/developer/doxygen/deal.II/classQuadratureSelector.html',1,'']]],
  ['qweddle_49',['QWeddle',['http://www.dealii.org/developer/doxygen/deal.II/classQWeddle.html',1,'']]],
  ['qwitherdenvincentsimplex_50',['QWitherdenVincentSimplex',['http://www.dealii.org/developer/doxygen/deal.II/classQWitherdenVincentSimplex.html',1,'']]]
];
