var searchData=
[
  ['q1wedgefunction_0',['Q1WedgeFunction',['http://www.dealii.org/developer/doxygen/deal.II/classFunctions_1_1Q1WedgeFunction.html',1,'Functions']]],
  ['qanisotropic_1',['QAnisotropic',['http://www.dealii.org/developer/doxygen/deal.II/classQAnisotropic.html',1,'']]],
  ['qcollection_2',['QCollection',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'hp']]],
  ['qcollection_3c_201_20_3e_3',['QCollection&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'hp']]],
  ['qcollection_3c_20dim_20_2d_201_20_3e_4',['QCollection&lt; dim - 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'hp']]],
  ['qcollection_3c_20dim_20_3e_5',['QCollection&lt; dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'hp']]],
  ['qcollection_3c_20q_5fdim_20_3e_6',['QCollection&lt; q_dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'hp']]],
  ['qduffy_7',['QDuffy',['http://www.dealii.org/developer/doxygen/deal.II/classQDuffy.html',1,'']]],
  ['qgauss_8',['QGauss',['http://www.dealii.org/developer/doxygen/deal.II/classQGauss.html',1,'']]],
  ['qgausschebyshev_9',['QGaussChebyshev',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussChebyshev.html',1,'']]],
  ['qgausslobatto_10',['QGaussLobatto',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLobatto.html',1,'']]],
  ['qgausslobatto_3c_201_20_3e_11',['QGaussLobatto&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLobatto.html',1,'']]],
  ['qgausslobattochebyshev_12',['QGaussLobattoChebyshev',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLobattoChebyshev.html',1,'']]],
  ['qgausslog_13',['QGaussLog',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLog.html',1,'']]],
  ['qgausslogr_14',['QGaussLogR',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLogR.html',1,'']]],
  ['qgaussoneoverr_15',['QGaussOneOverR',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussOneOverR.html',1,'']]],
  ['qgausspyramid_16',['QGaussPyramid',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussPyramid.html',1,'']]],
  ['qgaussradau_17',['QGaussRadau',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussRadau.html',1,'']]],
  ['qgaussradauchebyshev_18',['QGaussRadauChebyshev',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussRadauChebyshev.html',1,'']]],
  ['qgausssimplex_19',['QGaussSimplex',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussSimplex.html',1,'']]],
  ['qgausswedge_20',['QGaussWedge',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussWedge.html',1,'']]],
  ['qgenerator_21',['QGenerator',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGenerator.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qgenerator_3c_201_2c_20spacedim_20_3e_22',['QGenerator&lt; 1, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGenerator_3_011_00_01spacedim_01_4.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qgenerator_3c_20dim_2c_20dim_20_3e_23',['QGenerator&lt; dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGenerator.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qgeneratorbase_24',['QGeneratorBase',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGeneratorBase.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qgeneratorbase_3c_201_2c_20spacedim_20_3e_25',['QGeneratorBase&lt; 1, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGeneratorBase.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qiterated_26',['QIterated',['http://www.dealii.org/developer/doxygen/deal.II/classQIterated.html',1,'']]],
  ['qiteratedsimplex_27',['QIteratedSimplex',['http://www.dealii.org/developer/doxygen/deal.II/classQIteratedSimplex.html',1,'']]],
  ['qmidpoint_28',['QMidpoint',['http://www.dealii.org/developer/doxygen/deal.II/classQMidpoint.html',1,'']]],
  ['qmilne_29',['QMilne',['http://www.dealii.org/developer/doxygen/deal.II/classQMilne.html',1,'']]],
  ['qpartitioning_30',['QPartitioning',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QPartitioning.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qpartitioning_3c_20dim_20_3e_31',['QPartitioning&lt; dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QPartitioning.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qprojector_32',['QProjector',['http://www.dealii.org/developer/doxygen/deal.II/classQProjector.html',1,'']]],
  ['qr_33',['QR',['http://www.dealii.org/developer/doxygen/deal.II/classQR.html',1,'']]],
  ['qsimplex_34',['QSimplex',['http://www.dealii.org/developer/doxygen/deal.II/classQSimplex.html',1,'']]],
  ['qsimplex_3c_202_20_3e_35',['QSimplex&lt; 2 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQSimplex.html',1,'']]],
  ['qsimpson_36',['QSimpson',['http://www.dealii.org/developer/doxygen/deal.II/classQSimpson.html',1,'']]],
  ['qsorted_37',['QSorted',['http://www.dealii.org/developer/doxygen/deal.II/classQSorted.html',1,'']]],
  ['qsplit_38',['QSplit',['http://www.dealii.org/developer/doxygen/deal.II/classQSplit.html',1,'']]],
  ['qtelles_39',['QTelles',['http://www.dealii.org/developer/doxygen/deal.II/classQTelles.html',1,'']]],
  ['qtrapezoid_40',['QTrapezoid',['http://www.dealii.org/developer/doxygen/deal.II/classQTrapezoid.html',1,'']]],
  ['qtrianglepolar_41',['QTrianglePolar',['http://www.dealii.org/developer/doxygen/deal.II/classQTrianglePolar.html',1,'']]],
  ['quadrature_42',['Quadrature',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadrature_3c_200_20_3e_43',['Quadrature&lt; 0 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadrature_3c_201_20_3e_44',['Quadrature&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadrature_3c_20dim_20_2d_201_20_3e_45',['Quadrature&lt; dim - 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadrature_3c_20dim_20_3e_46',['Quadrature&lt; dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadrature_3c_20structdim_20_3e_47',['Quadrature&lt; structdim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadraturedescriptor_48',['QuadratureDescriptor',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MatrixFreeFunctions_1_1MappingInfoStorage_1_1QuadratureDescriptor.html',1,'internal::MatrixFreeFunctions::MappingInfoStorage']]],
  ['quadraturegenerator_49',['QuadratureGenerator',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1QuadratureGenerator.html',1,'NonMatching']]],
  ['quadraturegenerator_3c_20dim_20_2d_201_20_3e_50',['QuadratureGenerator&lt; dim - 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1QuadratureGenerator.html',1,'NonMatching']]],
  ['quadratureselector_51',['QuadratureSelector',['http://www.dealii.org/developer/doxygen/deal.II/classQuadratureSelector.html',1,'']]],
  ['qweddle_52',['QWeddle',['http://www.dealii.org/developer/doxygen/deal.II/classQWeddle.html',1,'']]],
  ['qwitherdenvincentsimplex_53',['QWitherdenVincentSimplex',['http://www.dealii.org/developer/doxygen/deal.II/classQWitherdenVincentSimplex.html',1,'']]]
];
