var searchData=
[
  ['field_20modeling_20code_20gallery_20program_0',['The &apos;Crystal growth problem using phase field modeling&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Crystal_Growth_Phase_Field_Model.html',1,'']]],
  ['finite_20element_20mfmfe_20methods_20code_20gallery_20program_1',['The &apos;Higher Order Multipoint Flux Mixed Finite Element (MFMFE) methods&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_MultipointFluxMixedFiniteElementMethods.html',1,'']]],
  ['finite_20strain_20compressible_20elasticity_20code_20gallery_20program_2',['The &apos;Quasi-Static Finite-Strain Compressible Elasticity&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Quasi_static_Finite_strain_Compressible_Elasticity.html',1,'']]],
  ['finite_20strain_20quasi_20incompressible_20visco_20elasticity_20code_20gallery_20program_3',['The &apos;Quasi-Static Finite-Strain Quasi-incompressible Visco-elasticity&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Quasi_static_Finite_strain_Quasi_incompressible_ViscoElasticity.html',1,'']]],
  ['flow_20interaction_20code_20gallery_20program_4',['The &apos;Two phase flow interaction &apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_two_phase_flow.html',1,'']]],
  ['flux_20mixed_20finite_20element_20mfmfe_20methods_20code_20gallery_20program_5',['The &apos;Higher Order Multipoint Flux Mixed Finite Element (MFMFE) methods&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_MultipointFluxMixedFiniteElementMethods.html',1,'']]],
  ['for_20combustion_20waves_20code_20gallery_20program_6',['The &apos;Traveling-wave solutions of a qualitative model for combustion waves.&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_TravelingWaves.html',1,'']]],
  ['for_20the_20incompressible_20navier_20stokes_20equations_20code_20gallery_20program_7',['The &apos;TRBDF2-DG projection solver for the incompressible Navier-Stokes equations&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_NavierStokes_TRBDF2_DG.html',1,'']]],
  ['for_20the_20laplace_20equation_20code_20gallery_20program_8',['The &apos;MCMC for the Laplace equation&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_MCMC_Laplace.html',1,'']]],
  ['for_20the_20maxwell_20eigenvalue_20problem_20code_20gallery_20program_9',['The &apos;Goal-Oriented hp-Adaptivity for the Maxwell Eigenvalue Problem&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Maxwell_Eigenvalue-hp-Refinement.html',1,'']]]
];
