var searchData=
[
  ['eigenvalue_20problem_20code_20gallery_20program_0',['The &apos;Goal-Oriented hp-Adaptivity for the Maxwell Eigenvalue Problem&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Maxwell_Eigenvalue-hp-Refinement.html',1,'']]],
  ['elastic_20active_20skeletal_20muscle_20model_20code_20gallery_20program_1',['The &apos;Linear Elastic Active Skeletal Muscle Model&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Linear_Elastic_Active_Skeletal_Muscle_Model.html',1,'']]],
  ['elasticity_20code_20gallery_20program_2',['The &apos;Quasi-Static Finite-Strain Compressible Elasticity&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Quasi_static_Finite_strain_Compressible_Elasticity.html',1,'']]],
  ['elasticity_20code_20gallery_20program_3',['The &apos;Quasi-Static Finite-Strain Quasi-incompressible Visco-elasticity&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Quasi_static_Finite_strain_Quasi_incompressible_ViscoElasticity.html',1,'']]],
  ['elastoplastic_20torsion_20code_20gallery_20program_4',['The &apos;Elastoplastic Torsion&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_ElastoplasticTorsion.html',1,'']]],
  ['elastoplasticity_20problems_20code_20gallery_20program_5',['The &apos;Goal-oriented mesh adaptivity in elastoplasticity problems&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_goal_oriented_elastoplasticity.html',1,'']]],
  ['element_20mfmfe_20methods_20code_20gallery_20program_6',['The &apos;Higher Order Multipoint Flux Mixed Finite Element (MFMFE) methods&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_MultipointFluxMixedFiniteElementMethods.html',1,'']]],
  ['equation_20code_20gallery_20program_7',['The &apos;Parallel in Time Heat Equation&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_parallel_in_time.html',1,'']]],
  ['equation_20code_20gallery_20program_8',['The &apos;MCMC for the Laplace equation&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_MCMC_Laplace.html',1,'']]],
  ['equation_20coupled_20to_20an_20external_20simulation_20program_20code_20gallery_20program_9',['The &apos;Laplace equation coupled to an external simulation program&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_coupled_laplace_problem.html',1,'']]],
  ['equation_20solve_20code_20gallery_20program_10',['The &apos;Generalized Swift-Hohenberg Equation Solve&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Swift_Hohenberg-Solver.html',1,'']]],
  ['equations_20code_20gallery_20program_11',['The &apos;TRBDF2-DG projection solver for the incompressible Navier-Stokes equations&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_NavierStokes_TRBDF2_DG.html',1,'']]],
  ['evolution_20code_20gallery_20program_12',['The &apos;Viscoelastoplastic topography evolution&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_CeresFE.html',1,'']]],
  ['external_20simulation_20program_20code_20gallery_20program_13',['The &apos;Laplace equation coupled to an external simulation program&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_coupled_laplace_problem.html',1,'']]]
];
