var searchData=
[
  ['simulation_20program_20code_20gallery_20program_0',['The &apos;Laplace equation coupled to an external simulation program&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_coupled_laplace_problem.html',1,'']]],
  ['since_20the_20last_20release_1',['Changes since the last release',['http://www.dealii.org/developer/doxygen/deal.II/recent_changes.html',1,'']]],
  ['skeletal_20muscle_20model_20code_20gallery_20program_2',['The &apos;Linear Elastic Active Skeletal Muscle Model&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Linear_Elastic_Active_Skeletal_Muscle_Model.html',1,'']]],
  ['solutions_20of_20a_20qualitative_20model_20for_20combustion_20waves_20code_20gallery_20program_3',['The &apos;Traveling-wave solutions of a qualitative model for combustion waves.&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_TravelingWaves.html',1,'']]],
  ['solve_20code_20gallery_20program_4',['The &apos;Generalized Swift-Hohenberg Equation Solve&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Swift_Hohenberg-Solver.html',1,'']]],
  ['solver_20for_20the_20incompressible_20navier_20stokes_20equations_20code_20gallery_20program_5',['The &apos;TRBDF2-DG projection solver for the incompressible Navier-Stokes equations&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_NavierStokes_TRBDF2_DG.html',1,'']]],
  ['static_20finite_20strain_20compressible_20elasticity_20code_20gallery_20program_6',['The &apos;Quasi-Static Finite-Strain Compressible Elasticity&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Quasi_static_Finite_strain_Compressible_Elasticity.html',1,'']]],
  ['static_20finite_20strain_20quasi_20incompressible_20visco_20elasticity_20code_20gallery_20program_7',['The &apos;Quasi-Static Finite-Strain Quasi-incompressible Visco-elasticity&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Quasi_static_Finite_strain_Quasi_incompressible_ViscoElasticity.html',1,'']]],
  ['step_201_20tutorial_20program_8',['The step-1 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_1.html',1,'']]],
  ['step_2010_20tutorial_20program_9',['The step-10 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_10.html',1,'']]],
  ['step_2011_20tutorial_20program_10',['The step-11 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_11.html',1,'']]],
  ['step_2012_20tutorial_20program_11',['The step-12 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_12.html',1,'']]],
  ['step_2013_20tutorial_20program_12',['The step-13 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_13.html',1,'']]],
  ['step_2014_20tutorial_20program_13',['The step-14 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_14.html',1,'']]],
  ['step_2015_20tutorial_20program_14',['The step-15 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_15.html',1,'']]],
  ['step_2016_20tutorial_20program_15',['The step-16 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_16.html',1,'']]],
  ['step_2017_20tutorial_20program_16',['The step-17 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_17.html',1,'']]],
  ['step_2018_20tutorial_20program_17',['The step-18 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_18.html',1,'']]],
  ['step_2019_20tutorial_20program_18',['The step-19 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_19.html',1,'']]],
  ['step_202_20tutorial_20program_19',['The step-2 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_2.html',1,'']]],
  ['step_2020_20tutorial_20program_20',['The step-20 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_20.html',1,'']]],
  ['step_2021_20tutorial_20program_21',['The step-21 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_21.html',1,'']]],
  ['step_2022_20tutorial_20program_22',['The step-22 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_22.html',1,'']]],
  ['step_2023_20tutorial_20program_23',['The step-23 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_23.html',1,'']]],
  ['step_2024_20tutorial_20program_24',['The step-24 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_24.html',1,'']]],
  ['step_2025_20tutorial_20program_25',['The step-25 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_25.html',1,'']]],
  ['step_2026_20tutorial_20program_26',['The step-26 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_26.html',1,'']]],
  ['step_2027_20tutorial_20program_27',['The step-27 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_27.html',1,'']]],
  ['step_2028_20tutorial_20program_28',['The step-28 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_28.html',1,'']]],
  ['step_2029_20tutorial_20program_29',['The step-29 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_29.html',1,'']]],
  ['step_203_20tutorial_20program_30',['The step-3 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_3.html',1,'']]],
  ['step_2030_20tutorial_20program_31',['The step-30 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_30.html',1,'']]],
  ['step_2031_20tutorial_20program_32',['The step-31 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_31.html',1,'']]],
  ['step_2032_20tutorial_20program_33',['The step-32 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_32.html',1,'']]],
  ['step_2033_20tutorial_20program_34',['The step-33 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_33.html',1,'']]],
  ['step_2034_20tutorial_20program_35',['The step-34 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_34.html',1,'']]],
  ['step_2035_20tutorial_20program_36',['The step-35 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_35.html',1,'']]],
  ['step_2036_20tutorial_20program_37',['The step-36 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_36.html',1,'']]],
  ['step_2037_20tutorial_20program_38',['The step-37 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_37.html',1,'']]],
  ['step_2038_20tutorial_20program_39',['The step-38 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_38.html',1,'']]],
  ['step_2039_20tutorial_20program_40',['The step-39 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_39.html',1,'']]],
  ['step_204_20tutorial_20program_41',['The step-4 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_4.html',1,'']]],
  ['step_2040_20tutorial_20program_42',['The step-40 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_40.html',1,'']]],
  ['step_2041_20tutorial_20program_43',['The step-41 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_41.html',1,'']]],
  ['step_2042_20tutorial_20program_44',['The step-42 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_42.html',1,'']]],
  ['step_2043_20tutorial_20program_45',['The step-43 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_43.html',1,'']]],
  ['step_2044_20tutorial_20program_46',['The step-44 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_44.html',1,'']]],
  ['step_2045_20tutorial_20program_47',['The step-45 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_45.html',1,'']]],
  ['step_2046_20tutorial_20program_48',['The step-46 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_46.html',1,'']]],
  ['step_2047_20tutorial_20program_49',['The step-47 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_47.html',1,'']]],
  ['step_2048_20tutorial_20program_50',['The step-48 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_48.html',1,'']]],
  ['step_2049_20tutorial_20program_51',['The step-49 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_49.html',1,'']]],
  ['step_205_20tutorial_20program_52',['The step-5 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_5.html',1,'']]],
  ['step_2050_20tutorial_20program_53',['The step-50 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_50.html',1,'']]],
  ['step_2051_20tutorial_20program_54',['The step-51 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_51.html',1,'']]],
  ['step_2053_20tutorial_20program_55',['The step-53 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_53.html',1,'']]],
  ['step_2054_20tutorial_20program_56',['The step-54 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_54.html',1,'']]],
  ['step_2055_20tutorial_20program_57',['The step-55 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_55.html',1,'']]],
  ['step_2056_20tutorial_20program_58',['The step-56 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_56.html',1,'']]],
  ['step_2057_20tutorial_20program_59',['The step-57 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_57.html',1,'']]],
  ['step_2058_20tutorial_20program_60',['The step-58 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_58.html',1,'']]],
  ['step_2059_20tutorial_20program_61',['The step-59 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_59.html',1,'']]],
  ['step_206_20tutorial_20program_62',['The step-6 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_6.html',1,'']]],
  ['step_2060_20tutorial_20program_63',['The step-60 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_60.html',1,'']]],
  ['step_2061_20tutorial_20program_64',['The step-61 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_61.html',1,'']]],
  ['step_2062_20tutorial_20program_65',['The step-62 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_62.html',1,'']]],
  ['step_2063_20tutorial_20program_66',['The step-63 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_63.html',1,'']]],
  ['step_2064_20tutorial_20program_67',['The step-64 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_64.html',1,'']]],
  ['step_2065_20tutorial_20program_68',['The step-65 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_65.html',1,'']]],
  ['step_2066_20tutorial_20program_69',['The step-66 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_66.html',1,'']]],
  ['step_2067_20tutorial_20program_70',['The step-67 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_67.html',1,'']]],
  ['step_2068_20tutorial_20program_71',['The step-68 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_68.html',1,'']]],
  ['step_2069_20tutorial_20program_72',['The step-69 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_69.html',1,'']]],
  ['step_207_20tutorial_20program_73',['The step-7 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_7.html',1,'']]],
  ['step_2070_20tutorial_20program_74',['The step-70 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_70.html',1,'']]],
  ['step_2071_20tutorial_20program_75',['The step-71 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_71.html',1,'']]],
  ['step_2072_20tutorial_20program_76',['The step-72 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_72.html',1,'']]],
  ['step_2074_20tutorial_20program_77',['The step-74 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_74.html',1,'']]],
  ['step_2075_20tutorial_20program_78',['The step-75 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_75.html',1,'']]],
  ['step_2076_20tutorial_20program_79',['The step-76 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_76.html',1,'']]],
  ['step_2077_20tutorial_20program_80',['The step-77 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_77.html',1,'']]],
  ['step_2078_20tutorial_20program_81',['The step-78 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_78.html',1,'']]],
  ['step_2079_20tutorial_20program_82',['The step-79 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_79.html',1,'']]],
  ['step_208_20tutorial_20program_83',['The step-8 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_8.html',1,'']]],
  ['step_2081_20tutorial_20program_84',['The step-81 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_81.html',1,'']]],
  ['step_2082_20tutorial_20program_85',['The step-82 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_82.html',1,'']]],
  ['step_2083_20tutorial_20program_86',['The step-83 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_83.html',1,'']]],
  ['step_2085_20tutorial_20program_87',['The step-85 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_85.html',1,'']]],
  ['step_2086_20tutorial_20program_88',['The step-86 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_86.html',1,'']]],
  ['step_2087_20tutorial_20program_89',['The step-87 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_87.html',1,'']]],
  ['step_2089_20tutorial_20program_90',['The step-89 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_89.html',1,'']]],
  ['step_209_20tutorial_20program_91',['The step-9 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_9.html',1,'']]],
  ['step_2090_20tutorial_20program_92',['The step-90 tutorial program',['http://www.dealii.org/developer/doxygen/deal.II/step_90.html',1,'']]],
  ['stokes_20code_20gallery_20program_93',['The &apos;Time-dependent Navier-Stokes&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_time_dependent_navier_stokes.html',1,'']]],
  ['stokes_20equations_20code_20gallery_20program_94',['The &apos;TRBDF2-DG projection solver for the incompressible Navier-Stokes equations&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_NavierStokes_TRBDF2_DG.html',1,'']]],
  ['strain_20compressible_20elasticity_20code_20gallery_20program_95',['The &apos;Quasi-Static Finite-Strain Compressible Elasticity&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Quasi_static_Finite_strain_Compressible_Elasticity.html',1,'']]],
  ['strain_20quasi_20incompressible_20visco_20elasticity_20code_20gallery_20program_96',['The &apos;Quasi-Static Finite-Strain Quasi-incompressible Visco-elasticity&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Quasi_static_Finite_strain_Quasi_incompressible_ViscoElasticity.html',1,'']]],
  ['swift_20hohenberg_20equation_20solve_20code_20gallery_20program_97',['The &apos;Generalized Swift-Hohenberg Equation Solve&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Swift_Hohenberg-Solver.html',1,'']]]
];
