#!/bin/bash
## ---------------------------------------------------------------------
##
## Copyright (C) 2012 - 2013, 2015 by the deal.II authors
##
## This file is part of the deal.II library.
##
## The deal.II library is free software; you can use it, redistribute
## it, and/or modify it under the terms of the GNU Lesser General
## Public License as published by the Free Software Foundation; either
## version 2.1 of the License, or (at your option) any later version.
## The full text of the license can be found in the file LICENSE at
## the top level of the deal.II distribution.
##
## ---------------------------------------------------------------------

if test ! -d source ; then
  echo "*** This script must be run from the top-level directory of your project."
  exit
fi

if test ! -f .clang-format ; then
  echo "*** No style file .clang-format found."
  exit
fi


# loop over all directories in which we may have source files;
# collect a list of files and then spawn a parallel process to
# indent all of them
echo "--- Indenting all header and source files"
SRC_FILES=`find . -name "*.cc"`
H_FILES=`find . -name "*.h"`
clang-format -i $SRC_FILES
clang-format -i $H_FILES
