name: GitHub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  debug:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test debug
      run: |
         ./scripts/dr.sh "rm -rf build_linux_debug"
         ./scripts/dr.sh "mkdir build_linux_debug; cd build_linux_debug; cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug; ninja"
         ./scripts/dr.sh "cd build_linux_debug; ctest -N; ctest --output-on-failure"

  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test release
      run: |
          ./scripts/dr.sh "rm -rf build_linux_release"
          ./scripts/dr.sh "mkdir build_linux_release; cd build_linux_release; cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release; ninja"
          ./scripts/dr.sh "cd build_linux_release; ctest -N; ctest --output-on-failure"